modLoader="javafml"
loaderVersion="[36,)"
license="All rights reserved"
issueTrackerURL="https://github.com/Samlegamer/Macaw-s-Furnitures-Compat/issues"

[[mods]]
modId="mcwfurnituresbop"
version="1.16.5-1.3"
displayName="Macaw's Furnitures - BOP"
displayURL="https://www.curseforge.com/minecraft/mc-mods/macaws-furnitures-biomes-o-plenty"
logoFile="logo.png"
credits="sketch_macaw"
authors="Samlegamer"
description='''
Compatibility between Macaw's Furnitures and Biome O' Plenty for Minecraft 1.16.5 !
'''

[[dependencies.mcwfurnituresbop]]
    modId="forge"
    mandatory=true
    versionRange="[36,)"
    ordering="NONE"
    side="BOTH"

[[dependencies.mcwfurnituresbop]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.16.5,1.17)"
    ordering="NONE"
    side="BOTH"