package fr.samlegamer.mcwfurnituresbyg;

import fr.samlegamer.mcwfurnituresbyg.block.MFurniBYGBlocksRegistry;
import net.fabricmc.api.ClientModInitializer;
import net.fabricmc.api.EnvType;
import net.fabricmc.api.Environment;
import net.fabricmc.fabric.api.blockrenderlayer.v1.BlockRenderLayerMap;
import net.minecraft.client.render.RenderLayer;

@Environment(EnvType.CLIENT)
public class McwFurnituresBYGClient implements ClientModInitializer
{
	@Override
	public void onInitializeClient()
	{
		//FOR CLIENT
		BlockRenderLayerMap.INSTANCE.putBlocks(RenderLayer.getCutout(),
		MFurniBYGBlocksRegistry.aspen_glass_table, MFurniBYGBlocksRegistry.stripped_aspen_glass_table, MFurniBYGBlocksRegistry.baobab_glass_table, MFurniBYGBlocksRegistry.stripped_baobab_glass_table, MFurniBYGBlocksRegistry.blue_enchanted_glass_table, MFurniBYGBlocksRegistry.stripped_blue_enchanted_glass_table, MFurniBYGBlocksRegistry.cherry_glass_table, MFurniBYGBlocksRegistry.stripped_cherry_glass_table, MFurniBYGBlocksRegistry.cika_glass_table, MFurniBYGBlocksRegistry.stripped_cika_glass_table, MFurniBYGBlocksRegistry.cypress_glass_table, MFurniBYGBlocksRegistry.stripped_cypress_glass_table, MFurniBYGBlocksRegistry.ebony_glass_table, MFurniBYGBlocksRegistry.stripped_ebony_glass_table, MFurniBYGBlocksRegistry.ether_glass_table, MFurniBYGBlocksRegistry.stripped_ether_glass_table, MFurniBYGBlocksRegistry.fir_glass_table, MFurniBYGBlocksRegistry.stripped_fir_glass_table, MFurniBYGBlocksRegistry.green_enchanted_glass_table, MFurniBYGBlocksRegistry.stripped_green_enchanted_glass_table, MFurniBYGBlocksRegistry.holly_glass_table, MFurniBYGBlocksRegistry.stripped_holly_glass_table, MFurniBYGBlocksRegistry.jacaranda_glass_table, MFurniBYGBlocksRegistry.stripped_jacaranda_glass_table, MFurniBYGBlocksRegistry.lament_glass_table, MFurniBYGBlocksRegistry.stripped_lament_glass_table, MFurniBYGBlocksRegistry.mahogany_glass_table, MFurniBYGBlocksRegistry.stripped_mahogany_glass_table, MFurniBYGBlocksRegistry.white_mangrove_glass_table, MFurniBYGBlocksRegistry.stripped_white_mangrove_glass_table, MFurniBYGBlocksRegistry.maple_glass_table, MFurniBYGBlocksRegistry.stripped_maple_glass_table, MFurniBYGBlocksRegistry.nightshade_glass_table, MFurniBYGBlocksRegistry.stripped_nightshade_glass_table, MFurniBYGBlocksRegistry.palm_glass_table, MFurniBYGBlocksRegistry.stripped_palm_glass_table, MFurniBYGBlocksRegistry.pine_glass_table, MFurniBYGBlocksRegistry.stripped_pine_glass_table, MFurniBYGBlocksRegistry.rainbow_eucalyptus_glass_table, MFurniBYGBlocksRegistry.stripped_rainbow_eucalyptus_glass_table, MFurniBYGBlocksRegistry.redwood_glass_table, MFurniBYGBlocksRegistry.stripped_redwood_glass_table, MFurniBYGBlocksRegistry.skyris_glass_table, MFurniBYGBlocksRegistry.stripped_skyris_glass_table, MFurniBYGBlocksRegistry.willow_glass_table, MFurniBYGBlocksRegistry.stripped_willow_glass_table, MFurniBYGBlocksRegistry.witch_hazel_glass_table, MFurniBYGBlocksRegistry.stripped_witch_hazel_glass_table, MFurniBYGBlocksRegistry.zelkova_glass_table, MFurniBYGBlocksRegistry.stripped_zelkova_glass_table, MFurniBYGBlocksRegistry.bulbis_glass_table, MFurniBYGBlocksRegistry.stripped_bulbis_glass_table, MFurniBYGBlocksRegistry.imparius_glass_table, MFurniBYGBlocksRegistry.stripped_imparius_glass_table, MFurniBYGBlocksRegistry.sythian_glass_table, MFurniBYGBlocksRegistry.stripped_sythian_glass_table);
	}
}