package fr.samlegamer.mcwfurnituresbop;

import org.apache.logging.log4j.LogManager;
import org.apache.logging.log4j.Logger;
import fr.samlegamer.mcwfurnituresbop.block.MFurniBOPBlocksRegistry;
import net.fabricmc.api.ModInitializer;
import net.fabricmc.fabric.api.itemgroup.v1.FabricItemGroup;
import net.kikoz.mcwfurnitures.MacawsFurniture;
import net.minecraft.block.Block;
import net.minecraft.item.ItemGroup;
import net.minecraft.item.ItemStack;
import net.minecraft.registry.Registries;
import net.minecraft.registry.Registry;
import net.minecraft.text.Text;
import net.minecraft.util.Identifier;

public class McwFurnituresBOP implements ModInitializer
{
	public static final String MODID = "mcwfurnituresbop";
	private static final Logger LOGGER = LogManager.getLogger();
	
    public static final ItemGroup MFURNIBOP_CT = FabricItemGroup.builder()
            .icon(() -> new ItemStack(MFurniBOPBlocksRegistry.dead_bookshelf))
            .displayName(Text.literal("Macaw's Furnitures - BOP"))
            .entries((context, entries) -> {
            	entries.add(MFurniBOPBlocksRegistry.dead_wardrobe);
            	entries.add(MFurniBOPBlocksRegistry.dead_modern_wardrobe);
            	entries.add(MFurniBOPBlocksRegistry.dead_double_wardrobe);
            	entries.add(MFurniBOPBlocksRegistry.dead_bookshelf);
            	entries.add(MFurniBOPBlocksRegistry.dead_bookshelf_cupboard);
            	entries.add(MFurniBOPBlocksRegistry.dead_drawer);
            	entries.add(MFurniBOPBlocksRegistry.dead_double_drawer);
            	entries.add(MFurniBOPBlocksRegistry.dead_bookshelf_drawer);
            	entries.add(MFurniBOPBlocksRegistry.dead_lower_bookshelf_drawer);
            	entries.add(MFurniBOPBlocksRegistry.dead_large_drawer);
            	entries.add(MFurniBOPBlocksRegistry.dead_lower_triple_drawer);
            	entries.add(MFurniBOPBlocksRegistry.dead_triple_drawer);
            	entries.add(MFurniBOPBlocksRegistry.dead_covered_desk);
            	entries.add(MFurniBOPBlocksRegistry.dead_modern_desk);
            	entries.add(MFurniBOPBlocksRegistry.dead_table);
            	entries.add(MFurniBOPBlocksRegistry.dead_end_table);
            	entries.add(MFurniBOPBlocksRegistry.dead_coffee_table);
            	entries.add(MFurniBOPBlocksRegistry.dead_glass_table);
            	entries.add(MFurniBOPBlocksRegistry.dead_chair);
            	entries.add(MFurniBOPBlocksRegistry.dead_modern_chair);
            	entries.add(MFurniBOPBlocksRegistry.dead_striped_chair);
            	entries.add(MFurniBOPBlocksRegistry.dead_stool_chair);
            	entries.add(MFurniBOPBlocksRegistry.dead_counter);
            	entries.add(MFurniBOPBlocksRegistry.dead_drawer_counter);
            	entries.add(MFurniBOPBlocksRegistry.dead_double_drawer_counter);
            	entries.add(MFurniBOPBlocksRegistry.dead_cupboard_counter);
            	entries.add(MFurniBOPBlocksRegistry.stripped_dead_wardrobe);
            	entries.add(MFurniBOPBlocksRegistry.stripped_dead_modern_wardrobe);
            	entries.add(MFurniBOPBlocksRegistry.stripped_dead_double_wardrobe);
            	entries.add(MFurniBOPBlocksRegistry.stripped_dead_bookshelf);
            	entries.add(MFurniBOPBlocksRegistry.stripped_dead_bookshelf_cupboard);
            	entries.add(MFurniBOPBlocksRegistry.stripped_dead_drawer);
            	entries.add(MFurniBOPBlocksRegistry.stripped_dead_double_drawer);
            	entries.add(MFurniBOPBlocksRegistry.stripped_dead_bookshelf_drawer);
            	entries.add(MFurniBOPBlocksRegistry.stripped_dead_lower_bookshelf_drawer);
            	entries.add(MFurniBOPBlocksRegistry.stripped_dead_large_drawer);
            	entries.add(MFurniBOPBlocksRegistry.stripped_dead_lower_triple_drawer);
            	entries.add(MFurniBOPBlocksRegistry.stripped_dead_triple_drawer);
            	entries.add(MFurniBOPBlocksRegistry.stripped_dead_desk);
            	entries.add(MFurniBOPBlocksRegistry.stripped_dead_covered_desk);
            	entries.add(MFurniBOPBlocksRegistry.stripped_dead_modern_desk);
            	entries.add(MFurniBOPBlocksRegistry.stripped_dead_table);
            	entries.add(MFurniBOPBlocksRegistry.stripped_dead_end_table);
            	entries.add(MFurniBOPBlocksRegistry.stripped_dead_coffee_table);
            	entries.add(MFurniBOPBlocksRegistry.stripped_dead_glass_table);
            	entries.add(MFurniBOPBlocksRegistry.stripped_dead_modern_chair);
            	entries.add(MFurniBOPBlocksRegistry.stripped_dead_striped_chair);
            	entries.add(MFurniBOPBlocksRegistry.stripped_dead_stool_chair);
            	entries.add(MFurniBOPBlocksRegistry.stripped_dead_counter);
            	entries.add(MFurniBOPBlocksRegistry.stripped_dead_drawer_counter);
            	entries.add(MFurniBOPBlocksRegistry.stripped_dead_double_drawer_counter);
            	entries.add(MFurniBOPBlocksRegistry.stripped_dead_cupboard_counter);
            	entries.add(MFurniBOPBlocksRegistry.dead_kitchen_cabinet);
            	entries.add(MFurniBOPBlocksRegistry.dead_double_kitchen_cabinet);
            	entries.add(MFurniBOPBlocksRegistry.dead_glass_kitchen_cabinet);
            	entries.add(MFurniBOPBlocksRegistry.stripped_dead_kitchen_cabinet);
            	entries.add(MFurniBOPBlocksRegistry.stripped_dead_double_kitchen_cabinet);
            	entries.add(MFurniBOPBlocksRegistry.stripped_dead_glass_kitchen_cabinet);
            	entries.add(MFurniBOPBlocksRegistry.fir_wardrobe);
            	entries.add(MFurniBOPBlocksRegistry.fir_modern_wardrobe);
            	entries.add(MFurniBOPBlocksRegistry.fir_double_wardrobe);
            	entries.add(MFurniBOPBlocksRegistry.fir_bookshelf);
            	entries.add(MFurniBOPBlocksRegistry.fir_bookshelf_cupboard);
            	entries.add(MFurniBOPBlocksRegistry.fir_drawer);
            	entries.add(MFurniBOPBlocksRegistry.fir_double_drawer);
            	entries.add(MFurniBOPBlocksRegistry.fir_bookshelf_drawer);
            	entries.add(MFurniBOPBlocksRegistry.fir_lower_bookshelf_drawer);
            	entries.add(MFurniBOPBlocksRegistry.fir_large_drawer);
            	entries.add(MFurniBOPBlocksRegistry.fir_lower_triple_drawer);
            	entries.add(MFurniBOPBlocksRegistry.fir_triple_drawer);
            	entries.add(MFurniBOPBlocksRegistry.fir_covered_desk);
            	entries.add(MFurniBOPBlocksRegistry.fir_modern_desk);
            	entries.add(MFurniBOPBlocksRegistry.fir_table);
            	entries.add(MFurniBOPBlocksRegistry.fir_end_table);
            	entries.add(MFurniBOPBlocksRegistry.fir_coffee_table);
            	entries.add(MFurniBOPBlocksRegistry.fir_glass_table);
            	entries.add(MFurniBOPBlocksRegistry.fir_chair);
            	entries.add(MFurniBOPBlocksRegistry.fir_modern_chair);
            	entries.add(MFurniBOPBlocksRegistry.fir_striped_chair);
            	entries.add(MFurniBOPBlocksRegistry.fir_stool_chair);
            	entries.add(MFurniBOPBlocksRegistry.fir_counter);
            	entries.add(MFurniBOPBlocksRegistry.fir_drawer_counter);
            	entries.add(MFurniBOPBlocksRegistry.fir_double_drawer_counter);
            	entries.add(MFurniBOPBlocksRegistry.fir_cupboard_counter);
            	entries.add(MFurniBOPBlocksRegistry.stripped_fir_wardrobe);
            	entries.add(MFurniBOPBlocksRegistry.stripped_fir_modern_wardrobe);
            	entries.add(MFurniBOPBlocksRegistry.stripped_fir_double_wardrobe);
            	entries.add(MFurniBOPBlocksRegistry.stripped_fir_bookshelf);
            	entries.add(MFurniBOPBlocksRegistry.stripped_fir_bookshelf_cupboard);
            	entries.add(MFurniBOPBlocksRegistry.stripped_fir_drawer);
            	entries.add(MFurniBOPBlocksRegistry.stripped_fir_double_drawer);
            	entries.add(MFurniBOPBlocksRegistry.stripped_fir_bookshelf_drawer);
            	entries.add(MFurniBOPBlocksRegistry.stripped_fir_lower_bookshelf_drawer);
            	entries.add(MFurniBOPBlocksRegistry.stripped_fir_large_drawer);
            	entries.add(MFurniBOPBlocksRegistry.stripped_fir_lower_triple_drawer);
            	entries.add(MFurniBOPBlocksRegistry.stripped_fir_triple_drawer);
            	entries.add(MFurniBOPBlocksRegistry.stripped_fir_desk);
            	entries.add(MFurniBOPBlocksRegistry.stripped_fir_covered_desk);
            	entries.add(MFurniBOPBlocksRegistry.stripped_fir_modern_desk);
            	entries.add(MFurniBOPBlocksRegistry.stripped_fir_table);
            	entries.add(MFurniBOPBlocksRegistry.stripped_fir_end_table);
            	entries.add(MFurniBOPBlocksRegistry.stripped_fir_coffee_table);
            	entries.add(MFurniBOPBlocksRegistry.stripped_fir_glass_table);
            	entries.add(MFurniBOPBlocksRegistry.stripped_fir_modern_chair);
            	entries.add(MFurniBOPBlocksRegistry.stripped_fir_striped_chair);
            	entries.add(MFurniBOPBlocksRegistry.stripped_fir_stool_chair);
            	entries.add(MFurniBOPBlocksRegistry.stripped_fir_counter);
            	entries.add(MFurniBOPBlocksRegistry.stripped_fir_drawer_counter);
            	entries.add(MFurniBOPBlocksRegistry.stripped_fir_double_drawer_counter);
            	entries.add(MFurniBOPBlocksRegistry.stripped_fir_cupboard_counter);
            	entries.add(MFurniBOPBlocksRegistry.fir_kitchen_cabinet);
            	entries.add(MFurniBOPBlocksRegistry.fir_double_kitchen_cabinet);
            	entries.add(MFurniBOPBlocksRegistry.fir_glass_kitchen_cabinet);
            	entries.add(MFurniBOPBlocksRegistry.stripped_fir_kitchen_cabinet);
            	entries.add(MFurniBOPBlocksRegistry.stripped_fir_double_kitchen_cabinet);
            	entries.add(MFurniBOPBlocksRegistry.stripped_fir_glass_kitchen_cabinet);
            	entries.add(MFurniBOPBlocksRegistry.hellbark_wardrobe);
            	entries.add(MFurniBOPBlocksRegistry.hellbark_modern_wardrobe);
            	entries.add(MFurniBOPBlocksRegistry.hellbark_double_wardrobe);
            	entries.add(MFurniBOPBlocksRegistry.hellbark_bookshelf);
            	entries.add(MFurniBOPBlocksRegistry.hellbark_bookshelf_cupboard);
            	entries.add(MFurniBOPBlocksRegistry.hellbark_drawer);
            	entries.add(MFurniBOPBlocksRegistry.hellbark_double_drawer);
            	entries.add(MFurniBOPBlocksRegistry.hellbark_bookshelf_drawer);
            	entries.add(MFurniBOPBlocksRegistry.hellbark_lower_bookshelf_drawer);
            	entries.add(MFurniBOPBlocksRegistry.hellbark_large_drawer);
            	entries.add(MFurniBOPBlocksRegistry.hellbark_lower_triple_drawer);
            	entries.add(MFurniBOPBlocksRegistry.hellbark_triple_drawer);
            	entries.add(MFurniBOPBlocksRegistry.hellbark_covered_desk);
            	entries.add(MFurniBOPBlocksRegistry.hellbark_modern_desk);
            	entries.add(MFurniBOPBlocksRegistry.hellbark_table);
            	entries.add(MFurniBOPBlocksRegistry.hellbark_end_table);
            	entries.add(MFurniBOPBlocksRegistry.hellbark_coffee_table);
            	entries.add(MFurniBOPBlocksRegistry.hellbark_glass_table);
            	entries.add(MFurniBOPBlocksRegistry.hellbark_chair);
            	entries.add(MFurniBOPBlocksRegistry.hellbark_modern_chair);
            	entries.add(MFurniBOPBlocksRegistry.hellbark_striped_chair);
            	entries.add(MFurniBOPBlocksRegistry.hellbark_stool_chair);
            	entries.add(MFurniBOPBlocksRegistry.hellbark_counter);
            	entries.add(MFurniBOPBlocksRegistry.hellbark_drawer_counter);
            	entries.add(MFurniBOPBlocksRegistry.hellbark_double_drawer_counter);
            	entries.add(MFurniBOPBlocksRegistry.hellbark_cupboard_counter);
            	entries.add(MFurniBOPBlocksRegistry.stripped_hellbark_wardrobe);
            	entries.add(MFurniBOPBlocksRegistry.stripped_hellbark_modern_wardrobe);
            	entries.add(MFurniBOPBlocksRegistry.stripped_hellbark_double_wardrobe);
            	entries.add(MFurniBOPBlocksRegistry.stripped_hellbark_bookshelf);
            	entries.add(MFurniBOPBlocksRegistry.stripped_hellbark_bookshelf_cupboard);
            	entries.add(MFurniBOPBlocksRegistry.stripped_hellbark_drawer);
            	entries.add(MFurniBOPBlocksRegistry.stripped_hellbark_double_drawer);
            	entries.add(MFurniBOPBlocksRegistry.stripped_hellbark_bookshelf_drawer);
            	entries.add(MFurniBOPBlocksRegistry.stripped_hellbark_lower_bookshelf_drawer);
            	entries.add(MFurniBOPBlocksRegistry.stripped_hellbark_large_drawer);
            	entries.add(MFurniBOPBlocksRegistry.stripped_hellbark_lower_triple_drawer);
            	entries.add(MFurniBOPBlocksRegistry.stripped_hellbark_triple_drawer);
            	entries.add(MFurniBOPBlocksRegistry.stripped_hellbark_desk);
            	entries.add(MFurniBOPBlocksRegistry.stripped_hellbark_covered_desk);
            	entries.add(MFurniBOPBlocksRegistry.stripped_hellbark_modern_desk);
            	entries.add(MFurniBOPBlocksRegistry.stripped_hellbark_table);
            	entries.add(MFurniBOPBlocksRegistry.stripped_hellbark_end_table);
            	entries.add(MFurniBOPBlocksRegistry.stripped_hellbark_coffee_table);
            	entries.add(MFurniBOPBlocksRegistry.stripped_hellbark_glass_table);
            	entries.add(MFurniBOPBlocksRegistry.stripped_hellbark_modern_chair);
            	entries.add(MFurniBOPBlocksRegistry.stripped_hellbark_striped_chair);
            	entries.add(MFurniBOPBlocksRegistry.stripped_hellbark_stool_chair);
            	entries.add(MFurniBOPBlocksRegistry.stripped_hellbark_counter);
            	entries.add(MFurniBOPBlocksRegistry.stripped_hellbark_drawer_counter);
            	entries.add(MFurniBOPBlocksRegistry.stripped_hellbark_double_drawer_counter);
            	entries.add(MFurniBOPBlocksRegistry.stripped_hellbark_cupboard_counter);
            	entries.add(MFurniBOPBlocksRegistry.hellbark_kitchen_cabinet);
            	entries.add(MFurniBOPBlocksRegistry.hellbark_double_kitchen_cabinet);
            	entries.add(MFurniBOPBlocksRegistry.hellbark_glass_kitchen_cabinet);
            	entries.add(MFurniBOPBlocksRegistry.stripped_hellbark_kitchen_cabinet);
            	entries.add(MFurniBOPBlocksRegistry.stripped_hellbark_double_kitchen_cabinet);
            	entries.add(MFurniBOPBlocksRegistry.stripped_hellbark_glass_kitchen_cabinet);
            	entries.add(MFurniBOPBlocksRegistry.jacaranda_wardrobe);
            	entries.add(MFurniBOPBlocksRegistry.jacaranda_modern_wardrobe);
            	entries.add(MFurniBOPBlocksRegistry.jacaranda_double_wardrobe);
            	entries.add(MFurniBOPBlocksRegistry.jacaranda_bookshelf);
            	entries.add(MFurniBOPBlocksRegistry.jacaranda_bookshelf_cupboard);
            	entries.add(MFurniBOPBlocksRegistry.jacaranda_drawer);
            	entries.add(MFurniBOPBlocksRegistry.jacaranda_double_drawer);
            	entries.add(MFurniBOPBlocksRegistry.jacaranda_bookshelf_drawer);
            	entries.add(MFurniBOPBlocksRegistry.jacaranda_lower_bookshelf_drawer);
            	entries.add(MFurniBOPBlocksRegistry.jacaranda_large_drawer);
            	entries.add(MFurniBOPBlocksRegistry.jacaranda_lower_triple_drawer);
            	entries.add(MFurniBOPBlocksRegistry.jacaranda_triple_drawer);
            	entries.add(MFurniBOPBlocksRegistry.jacaranda_covered_desk);
            	entries.add(MFurniBOPBlocksRegistry.jacaranda_modern_desk);
            	entries.add(MFurniBOPBlocksRegistry.jacaranda_table);
            	entries.add(MFurniBOPBlocksRegistry.jacaranda_end_table);
            	entries.add(MFurniBOPBlocksRegistry.jacaranda_coffee_table);
            	entries.add(MFurniBOPBlocksRegistry.jacaranda_glass_table);
            	entries.add(MFurniBOPBlocksRegistry.jacaranda_chair);
            	entries.add(MFurniBOPBlocksRegistry.jacaranda_modern_chair);
            	entries.add(MFurniBOPBlocksRegistry.jacaranda_striped_chair);
            	entries.add(MFurniBOPBlocksRegistry.jacaranda_stool_chair);
            	entries.add(MFurniBOPBlocksRegistry.jacaranda_counter);
            	entries.add(MFurniBOPBlocksRegistry.jacaranda_drawer_counter);
            	entries.add(MFurniBOPBlocksRegistry.jacaranda_double_drawer_counter);
            	entries.add(MFurniBOPBlocksRegistry.jacaranda_cupboard_counter);
            	entries.add(MFurniBOPBlocksRegistry.stripped_jacaranda_wardrobe);
            	entries.add(MFurniBOPBlocksRegistry.stripped_jacaranda_modern_wardrobe);
            	entries.add(MFurniBOPBlocksRegistry.stripped_jacaranda_double_wardrobe);
            	entries.add(MFurniBOPBlocksRegistry.stripped_jacaranda_bookshelf);
            	entries.add(MFurniBOPBlocksRegistry.stripped_jacaranda_bookshelf_cupboard);
            	entries.add(MFurniBOPBlocksRegistry.stripped_jacaranda_drawer);
            	entries.add(MFurniBOPBlocksRegistry.stripped_jacaranda_double_drawer);
            	entries.add(MFurniBOPBlocksRegistry.stripped_jacaranda_bookshelf_drawer);
            	entries.add(MFurniBOPBlocksRegistry.stripped_jacaranda_lower_bookshelf_drawer);
            	entries.add(MFurniBOPBlocksRegistry.stripped_jacaranda_large_drawer);
            	entries.add(MFurniBOPBlocksRegistry.stripped_jacaranda_lower_triple_drawer);
            	entries.add(MFurniBOPBlocksRegistry.stripped_jacaranda_triple_drawer);
            	entries.add(MFurniBOPBlocksRegistry.stripped_jacaranda_desk);
            	entries.add(MFurniBOPBlocksRegistry.stripped_jacaranda_covered_desk);
            	entries.add(MFurniBOPBlocksRegistry.stripped_jacaranda_modern_desk);
            	entries.add(MFurniBOPBlocksRegistry.stripped_jacaranda_table);
            	entries.add(MFurniBOPBlocksRegistry.stripped_jacaranda_end_table);
            	entries.add(MFurniBOPBlocksRegistry.stripped_jacaranda_coffee_table);
            	entries.add(MFurniBOPBlocksRegistry.stripped_jacaranda_glass_table);
            	entries.add(MFurniBOPBlocksRegistry.stripped_jacaranda_modern_chair);
            	entries.add(MFurniBOPBlocksRegistry.stripped_jacaranda_striped_chair);
            	entries.add(MFurniBOPBlocksRegistry.stripped_jacaranda_stool_chair);
            	entries.add(MFurniBOPBlocksRegistry.stripped_jacaranda_counter);
            	entries.add(MFurniBOPBlocksRegistry.stripped_jacaranda_drawer_counter);
            	entries.add(MFurniBOPBlocksRegistry.stripped_jacaranda_double_drawer_counter);
            	entries.add(MFurniBOPBlocksRegistry.stripped_jacaranda_cupboard_counter);
            	entries.add(MFurniBOPBlocksRegistry.jacaranda_kitchen_cabinet);
            	entries.add(MFurniBOPBlocksRegistry.jacaranda_double_kitchen_cabinet);
            	entries.add(MFurniBOPBlocksRegistry.jacaranda_glass_kitchen_cabinet);
            	entries.add(MFurniBOPBlocksRegistry.stripped_jacaranda_kitchen_cabinet);
            	entries.add(MFurniBOPBlocksRegistry.stripped_jacaranda_double_kitchen_cabinet);
            	entries.add(MFurniBOPBlocksRegistry.stripped_jacaranda_glass_kitchen_cabinet);
            	entries.add(MFurniBOPBlocksRegistry.magic_wardrobe);
            	entries.add(MFurniBOPBlocksRegistry.magic_modern_wardrobe);
            	entries.add(MFurniBOPBlocksRegistry.magic_double_wardrobe);
            	entries.add(MFurniBOPBlocksRegistry.magic_bookshelf);
            	entries.add(MFurniBOPBlocksRegistry.magic_bookshelf_cupboard);
            	entries.add(MFurniBOPBlocksRegistry.magic_drawer);
            	entries.add(MFurniBOPBlocksRegistry.magic_double_drawer);
            	entries.add(MFurniBOPBlocksRegistry.magic_bookshelf_drawer);
            	entries.add(MFurniBOPBlocksRegistry.magic_lower_bookshelf_drawer);
            	entries.add(MFurniBOPBlocksRegistry.magic_large_drawer);
            	entries.add(MFurniBOPBlocksRegistry.magic_lower_triple_drawer);
            	entries.add(MFurniBOPBlocksRegistry.magic_triple_drawer);
            	entries.add(MFurniBOPBlocksRegistry.magic_covered_desk);
            	entries.add(MFurniBOPBlocksRegistry.magic_modern_desk);
            	entries.add(MFurniBOPBlocksRegistry.magic_table);
            	entries.add(MFurniBOPBlocksRegistry.magic_end_table);
            	entries.add(MFurniBOPBlocksRegistry.magic_coffee_table);
            	entries.add(MFurniBOPBlocksRegistry.magic_glass_table);
            	entries.add(MFurniBOPBlocksRegistry.magic_chair);
            	entries.add(MFurniBOPBlocksRegistry.magic_modern_chair);
            	entries.add(MFurniBOPBlocksRegistry.magic_striped_chair);
            	entries.add(MFurniBOPBlocksRegistry.magic_stool_chair);
            	entries.add(MFurniBOPBlocksRegistry.magic_counter);
            	entries.add(MFurniBOPBlocksRegistry.magic_drawer_counter);
            	entries.add(MFurniBOPBlocksRegistry.magic_double_drawer_counter);
            	entries.add(MFurniBOPBlocksRegistry.magic_cupboard_counter);
            	entries.add(MFurniBOPBlocksRegistry.stripped_magic_wardrobe);
            	entries.add(MFurniBOPBlocksRegistry.stripped_magic_modern_wardrobe);
            	entries.add(MFurniBOPBlocksRegistry.stripped_magic_double_wardrobe);
            	entries.add(MFurniBOPBlocksRegistry.stripped_magic_bookshelf);
            	entries.add(MFurniBOPBlocksRegistry.stripped_magic_bookshelf_cupboard);
            	entries.add(MFurniBOPBlocksRegistry.stripped_magic_drawer);
            	entries.add(MFurniBOPBlocksRegistry.stripped_magic_double_drawer);
            	entries.add(MFurniBOPBlocksRegistry.stripped_magic_bookshelf_drawer);
            	entries.add(MFurniBOPBlocksRegistry.stripped_magic_lower_bookshelf_drawer);
            	entries.add(MFurniBOPBlocksRegistry.stripped_magic_large_drawer);
            	entries.add(MFurniBOPBlocksRegistry.stripped_magic_lower_triple_drawer);
            	entries.add(MFurniBOPBlocksRegistry.stripped_magic_triple_drawer);
            	entries.add(MFurniBOPBlocksRegistry.stripped_magic_desk);
            	entries.add(MFurniBOPBlocksRegistry.stripped_magic_covered_desk);
            	entries.add(MFurniBOPBlocksRegistry.stripped_magic_modern_desk);
            	entries.add(MFurniBOPBlocksRegistry.stripped_magic_table);
            	entries.add(MFurniBOPBlocksRegistry.stripped_magic_end_table);
            	entries.add(MFurniBOPBlocksRegistry.stripped_magic_coffee_table);
            	entries.add(MFurniBOPBlocksRegistry.stripped_magic_glass_table);
            	entries.add(MFurniBOPBlocksRegistry.stripped_magic_modern_chair);
            	entries.add(MFurniBOPBlocksRegistry.stripped_magic_striped_chair);
            	entries.add(MFurniBOPBlocksRegistry.stripped_magic_stool_chair);
            	entries.add(MFurniBOPBlocksRegistry.stripped_magic_counter);
            	entries.add(MFurniBOPBlocksRegistry.stripped_magic_drawer_counter);
            	entries.add(MFurniBOPBlocksRegistry.stripped_magic_double_drawer_counter);
            	entries.add(MFurniBOPBlocksRegistry.stripped_magic_cupboard_counter);
            	entries.add(MFurniBOPBlocksRegistry.magic_kitchen_cabinet);
            	entries.add(MFurniBOPBlocksRegistry.magic_double_kitchen_cabinet);
            	entries.add(MFurniBOPBlocksRegistry.magic_glass_kitchen_cabinet);
            	entries.add(MFurniBOPBlocksRegistry.stripped_magic_kitchen_cabinet);
            	entries.add(MFurniBOPBlocksRegistry.stripped_magic_double_kitchen_cabinet);
            	entries.add(MFurniBOPBlocksRegistry.stripped_magic_glass_kitchen_cabinet);
            	entries.add(MFurniBOPBlocksRegistry.mahogany_wardrobe);
            	entries.add(MFurniBOPBlocksRegistry.mahogany_modern_wardrobe);
            	entries.add(MFurniBOPBlocksRegistry.mahogany_double_wardrobe);
            	entries.add(MFurniBOPBlocksRegistry.mahogany_bookshelf);
            	entries.add(MFurniBOPBlocksRegistry.mahogany_bookshelf_cupboard);
            	entries.add(MFurniBOPBlocksRegistry.mahogany_drawer);
            	entries.add(MFurniBOPBlocksRegistry.mahogany_double_drawer);
            	entries.add(MFurniBOPBlocksRegistry.mahogany_bookshelf_drawer);
            	entries.add(MFurniBOPBlocksRegistry.mahogany_lower_bookshelf_drawer);
            	entries.add(MFurniBOPBlocksRegistry.mahogany_large_drawer);
            	entries.add(MFurniBOPBlocksRegistry.mahogany_lower_triple_drawer);
            	entries.add(MFurniBOPBlocksRegistry.mahogany_triple_drawer);
            	entries.add(MFurniBOPBlocksRegistry.mahogany_covered_desk);
            	entries.add(MFurniBOPBlocksRegistry.mahogany_modern_desk);
            	entries.add(MFurniBOPBlocksRegistry.mahogany_table);
            	entries.add(MFurniBOPBlocksRegistry.mahogany_end_table);
            	entries.add(MFurniBOPBlocksRegistry.mahogany_coffee_table);
            	entries.add(MFurniBOPBlocksRegistry.mahogany_glass_table);
            	entries.add(MFurniBOPBlocksRegistry.mahogany_chair);
            	entries.add(MFurniBOPBlocksRegistry.mahogany_modern_chair);
            	entries.add(MFurniBOPBlocksRegistry.mahogany_striped_chair);
            	entries.add(MFurniBOPBlocksRegistry.mahogany_stool_chair);
            	entries.add(MFurniBOPBlocksRegistry.mahogany_counter);
            	entries.add(MFurniBOPBlocksRegistry.mahogany_drawer_counter);
            	entries.add(MFurniBOPBlocksRegistry.mahogany_double_drawer_counter);
            	entries.add(MFurniBOPBlocksRegistry.mahogany_cupboard_counter);
            	entries.add(MFurniBOPBlocksRegistry.stripped_mahogany_wardrobe);
            	entries.add(MFurniBOPBlocksRegistry.stripped_mahogany_modern_wardrobe);
            	entries.add(MFurniBOPBlocksRegistry.stripped_mahogany_double_wardrobe);
            	entries.add(MFurniBOPBlocksRegistry.stripped_mahogany_bookshelf);
            	entries.add(MFurniBOPBlocksRegistry.stripped_mahogany_bookshelf_cupboard);
            	entries.add(MFurniBOPBlocksRegistry.stripped_mahogany_drawer);
            	entries.add(MFurniBOPBlocksRegistry.stripped_mahogany_double_drawer);
            	entries.add(MFurniBOPBlocksRegistry.stripped_mahogany_bookshelf_drawer);
            	entries.add(MFurniBOPBlocksRegistry.stripped_mahogany_lower_bookshelf_drawer);
            	entries.add(MFurniBOPBlocksRegistry.stripped_mahogany_large_drawer);
            	entries.add(MFurniBOPBlocksRegistry.stripped_mahogany_lower_triple_drawer);
            	entries.add(MFurniBOPBlocksRegistry.stripped_mahogany_triple_drawer);
            	entries.add(MFurniBOPBlocksRegistry.stripped_mahogany_desk);
            	entries.add(MFurniBOPBlocksRegistry.stripped_mahogany_covered_desk);
            	entries.add(MFurniBOPBlocksRegistry.stripped_mahogany_modern_desk);
            	entries.add(MFurniBOPBlocksRegistry.stripped_mahogany_table);
            	entries.add(MFurniBOPBlocksRegistry.stripped_mahogany_end_table);
            	entries.add(MFurniBOPBlocksRegistry.stripped_mahogany_coffee_table);
            	entries.add(MFurniBOPBlocksRegistry.stripped_mahogany_glass_table);
            	entries.add(MFurniBOPBlocksRegistry.stripped_mahogany_modern_chair);
            	entries.add(MFurniBOPBlocksRegistry.stripped_mahogany_striped_chair);
            	entries.add(MFurniBOPBlocksRegistry.stripped_mahogany_stool_chair);
            	entries.add(MFurniBOPBlocksRegistry.stripped_mahogany_counter);
            	entries.add(MFurniBOPBlocksRegistry.stripped_mahogany_drawer_counter);
            	entries.add(MFurniBOPBlocksRegistry.stripped_mahogany_double_drawer_counter);
            	entries.add(MFurniBOPBlocksRegistry.stripped_mahogany_cupboard_counter);
            	entries.add(MFurniBOPBlocksRegistry.mahogany_kitchen_cabinet);
            	entries.add(MFurniBOPBlocksRegistry.mahogany_double_kitchen_cabinet);
            	entries.add(MFurniBOPBlocksRegistry.mahogany_glass_kitchen_cabinet);
            	entries.add(MFurniBOPBlocksRegistry.stripped_mahogany_kitchen_cabinet);
            	entries.add(MFurniBOPBlocksRegistry.stripped_mahogany_double_kitchen_cabinet);
            	entries.add(MFurniBOPBlocksRegistry.stripped_mahogany_glass_kitchen_cabinet);
            	entries.add(MFurniBOPBlocksRegistry.palm_wardrobe);
            	entries.add(MFurniBOPBlocksRegistry.palm_modern_wardrobe);
            	entries.add(MFurniBOPBlocksRegistry.palm_double_wardrobe);
            	entries.add(MFurniBOPBlocksRegistry.palm_bookshelf);
            	entries.add(MFurniBOPBlocksRegistry.palm_bookshelf_cupboard);
            	entries.add(MFurniBOPBlocksRegistry.palm_drawer);
            	entries.add(MFurniBOPBlocksRegistry.palm_double_drawer);
            	entries.add(MFurniBOPBlocksRegistry.palm_bookshelf_drawer);
            	entries.add(MFurniBOPBlocksRegistry.palm_lower_bookshelf_drawer);
            	entries.add(MFurniBOPBlocksRegistry.palm_large_drawer);
            	entries.add(MFurniBOPBlocksRegistry.palm_lower_triple_drawer);
            	entries.add(MFurniBOPBlocksRegistry.palm_triple_drawer);
            	entries.add(MFurniBOPBlocksRegistry.palm_covered_desk);
            	entries.add(MFurniBOPBlocksRegistry.palm_modern_desk);
            	entries.add(MFurniBOPBlocksRegistry.palm_table);
            	entries.add(MFurniBOPBlocksRegistry.palm_end_table);
            	entries.add(MFurniBOPBlocksRegistry.palm_coffee_table);
            	entries.add(MFurniBOPBlocksRegistry.palm_glass_table);
            	entries.add(MFurniBOPBlocksRegistry.palm_chair);
            	entries.add(MFurniBOPBlocksRegistry.palm_modern_chair);
            	entries.add(MFurniBOPBlocksRegistry.palm_striped_chair);
            	entries.add(MFurniBOPBlocksRegistry.palm_stool_chair);
            	entries.add(MFurniBOPBlocksRegistry.palm_counter);
            	entries.add(MFurniBOPBlocksRegistry.palm_drawer_counter);
            	entries.add(MFurniBOPBlocksRegistry.palm_double_drawer_counter);
            	entries.add(MFurniBOPBlocksRegistry.palm_cupboard_counter);
            	entries.add(MFurniBOPBlocksRegistry.stripped_palm_wardrobe);
            	entries.add(MFurniBOPBlocksRegistry.stripped_palm_modern_wardrobe);
            	entries.add(MFurniBOPBlocksRegistry.stripped_palm_double_wardrobe);
            	entries.add(MFurniBOPBlocksRegistry.stripped_palm_bookshelf);
            	entries.add(MFurniBOPBlocksRegistry.stripped_palm_bookshelf_cupboard);
            	entries.add(MFurniBOPBlocksRegistry.stripped_palm_drawer);
            	entries.add(MFurniBOPBlocksRegistry.stripped_palm_double_drawer);
            	entries.add(MFurniBOPBlocksRegistry.stripped_palm_bookshelf_drawer);
            	entries.add(MFurniBOPBlocksRegistry.stripped_palm_lower_bookshelf_drawer);
            	entries.add(MFurniBOPBlocksRegistry.stripped_palm_large_drawer);
            	entries.add(MFurniBOPBlocksRegistry.stripped_palm_lower_triple_drawer);
            	entries.add(MFurniBOPBlocksRegistry.stripped_palm_triple_drawer);
            	entries.add(MFurniBOPBlocksRegistry.stripped_palm_desk);
            	entries.add(MFurniBOPBlocksRegistry.stripped_palm_covered_desk);
            	entries.add(MFurniBOPBlocksRegistry.stripped_palm_modern_desk);
            	entries.add(MFurniBOPBlocksRegistry.stripped_palm_table);
            	entries.add(MFurniBOPBlocksRegistry.stripped_palm_end_table);
            	entries.add(MFurniBOPBlocksRegistry.stripped_palm_coffee_table);
            	entries.add(MFurniBOPBlocksRegistry.stripped_palm_glass_table);
            	entries.add(MFurniBOPBlocksRegistry.stripped_palm_modern_chair);
            	entries.add(MFurniBOPBlocksRegistry.stripped_palm_striped_chair);
            	entries.add(MFurniBOPBlocksRegistry.stripped_palm_stool_chair);
            	entries.add(MFurniBOPBlocksRegistry.stripped_palm_counter);
            	entries.add(MFurniBOPBlocksRegistry.stripped_palm_drawer_counter);
            	entries.add(MFurniBOPBlocksRegistry.stripped_palm_double_drawer_counter);
            	entries.add(MFurniBOPBlocksRegistry.stripped_palm_cupboard_counter);
            	entries.add(MFurniBOPBlocksRegistry.palm_kitchen_cabinet);
            	entries.add(MFurniBOPBlocksRegistry.palm_double_kitchen_cabinet);
            	entries.add(MFurniBOPBlocksRegistry.palm_glass_kitchen_cabinet);
            	entries.add(MFurniBOPBlocksRegistry.stripped_palm_kitchen_cabinet);
            	entries.add(MFurniBOPBlocksRegistry.stripped_palm_double_kitchen_cabinet);
            	entries.add(MFurniBOPBlocksRegistry.stripped_palm_glass_kitchen_cabinet);
            	entries.add(MFurniBOPBlocksRegistry.redwood_wardrobe);
            	entries.add(MFurniBOPBlocksRegistry.redwood_modern_wardrobe);
            	entries.add(MFurniBOPBlocksRegistry.redwood_double_wardrobe);
            	entries.add(MFurniBOPBlocksRegistry.redwood_bookshelf);
            	entries.add(MFurniBOPBlocksRegistry.redwood_bookshelf_cupboard);
            	entries.add(MFurniBOPBlocksRegistry.redwood_drawer);
            	entries.add(MFurniBOPBlocksRegistry.redwood_double_drawer);
            	entries.add(MFurniBOPBlocksRegistry.redwood_bookshelf_drawer);
            	entries.add(MFurniBOPBlocksRegistry.redwood_lower_bookshelf_drawer);
            	entries.add(MFurniBOPBlocksRegistry.redwood_large_drawer);
            	entries.add(MFurniBOPBlocksRegistry.redwood_lower_triple_drawer);
            	entries.add(MFurniBOPBlocksRegistry.redwood_triple_drawer);
            	entries.add(MFurniBOPBlocksRegistry.redwood_covered_desk);
            	entries.add(MFurniBOPBlocksRegistry.redwood_modern_desk);
            	entries.add(MFurniBOPBlocksRegistry.redwood_table);
            	entries.add(MFurniBOPBlocksRegistry.redwood_end_table);
            	entries.add(MFurniBOPBlocksRegistry.redwood_coffee_table);
            	entries.add(MFurniBOPBlocksRegistry.redwood_glass_table);
            	entries.add(MFurniBOPBlocksRegistry.redwood_chair);
            	entries.add(MFurniBOPBlocksRegistry.redwood_modern_chair);
            	entries.add(MFurniBOPBlocksRegistry.redwood_striped_chair);
            	entries.add(MFurniBOPBlocksRegistry.redwood_stool_chair);
            	entries.add(MFurniBOPBlocksRegistry.redwood_counter);
            	entries.add(MFurniBOPBlocksRegistry.redwood_drawer_counter);
            	entries.add(MFurniBOPBlocksRegistry.redwood_double_drawer_counter);
            	entries.add(MFurniBOPBlocksRegistry.redwood_cupboard_counter);
            	entries.add(MFurniBOPBlocksRegistry.stripped_redwood_wardrobe);
            	entries.add(MFurniBOPBlocksRegistry.stripped_redwood_modern_wardrobe);
            	entries.add(MFurniBOPBlocksRegistry.stripped_redwood_double_wardrobe);
            	entries.add(MFurniBOPBlocksRegistry.stripped_redwood_bookshelf);
            	entries.add(MFurniBOPBlocksRegistry.stripped_redwood_bookshelf_cupboard);
            	entries.add(MFurniBOPBlocksRegistry.stripped_redwood_drawer);
            	entries.add(MFurniBOPBlocksRegistry.stripped_redwood_double_drawer);
            	entries.add(MFurniBOPBlocksRegistry.stripped_redwood_bookshelf_drawer);
            	entries.add(MFurniBOPBlocksRegistry.stripped_redwood_lower_bookshelf_drawer);
            	entries.add(MFurniBOPBlocksRegistry.stripped_redwood_large_drawer);
            	entries.add(MFurniBOPBlocksRegistry.stripped_redwood_lower_triple_drawer);
            	entries.add(MFurniBOPBlocksRegistry.stripped_redwood_triple_drawer);
            	entries.add(MFurniBOPBlocksRegistry.stripped_redwood_desk);
            	entries.add(MFurniBOPBlocksRegistry.stripped_redwood_covered_desk);
            	entries.add(MFurniBOPBlocksRegistry.stripped_redwood_modern_desk);
            	entries.add(MFurniBOPBlocksRegistry.stripped_redwood_table);
            	entries.add(MFurniBOPBlocksRegistry.stripped_redwood_end_table);
            	entries.add(MFurniBOPBlocksRegistry.stripped_redwood_coffee_table);
            	entries.add(MFurniBOPBlocksRegistry.stripped_redwood_glass_table);
            	entries.add(MFurniBOPBlocksRegistry.stripped_redwood_modern_chair);
            	entries.add(MFurniBOPBlocksRegistry.stripped_redwood_striped_chair);
            	entries.add(MFurniBOPBlocksRegistry.stripped_redwood_stool_chair);
            	entries.add(MFurniBOPBlocksRegistry.stripped_redwood_counter);
            	entries.add(MFurniBOPBlocksRegistry.stripped_redwood_drawer_counter);
            	entries.add(MFurniBOPBlocksRegistry.stripped_redwood_double_drawer_counter);
            	entries.add(MFurniBOPBlocksRegistry.stripped_redwood_cupboard_counter);
            	entries.add(MFurniBOPBlocksRegistry.redwood_kitchen_cabinet);
            	entries.add(MFurniBOPBlocksRegistry.redwood_double_kitchen_cabinet);
            	entries.add(MFurniBOPBlocksRegistry.redwood_glass_kitchen_cabinet);
            	entries.add(MFurniBOPBlocksRegistry.stripped_redwood_kitchen_cabinet);
            	entries.add(MFurniBOPBlocksRegistry.stripped_redwood_double_kitchen_cabinet);
            	entries.add(MFurniBOPBlocksRegistry.stripped_redwood_glass_kitchen_cabinet);
            	entries.add(MFurniBOPBlocksRegistry.umbran_wardrobe);
            	entries.add(MFurniBOPBlocksRegistry.umbran_modern_wardrobe);
            	entries.add(MFurniBOPBlocksRegistry.umbran_double_wardrobe);
            	entries.add(MFurniBOPBlocksRegistry.umbran_bookshelf);
            	entries.add(MFurniBOPBlocksRegistry.umbran_bookshelf_cupboard);
            	entries.add(MFurniBOPBlocksRegistry.umbran_drawer);
            	entries.add(MFurniBOPBlocksRegistry.umbran_double_drawer);
            	entries.add(MFurniBOPBlocksRegistry.umbran_bookshelf_drawer);
            	entries.add(MFurniBOPBlocksRegistry.umbran_lower_bookshelf_drawer);
            	entries.add(MFurniBOPBlocksRegistry.umbran_large_drawer);
            	entries.add(MFurniBOPBlocksRegistry.umbran_lower_triple_drawer);
            	entries.add(MFurniBOPBlocksRegistry.umbran_triple_drawer);
            	entries.add(MFurniBOPBlocksRegistry.umbran_covered_desk);
            	entries.add(MFurniBOPBlocksRegistry.umbran_modern_desk);
            	entries.add(MFurniBOPBlocksRegistry.umbran_table);
            	entries.add(MFurniBOPBlocksRegistry.umbran_end_table);
            	entries.add(MFurniBOPBlocksRegistry.umbran_coffee_table);
            	entries.add(MFurniBOPBlocksRegistry.umbran_glass_table);
            	entries.add(MFurniBOPBlocksRegistry.umbran_chair);
            	entries.add(MFurniBOPBlocksRegistry.umbran_modern_chair);
            	entries.add(MFurniBOPBlocksRegistry.umbran_striped_chair);
            	entries.add(MFurniBOPBlocksRegistry.umbran_stool_chair);
            	entries.add(MFurniBOPBlocksRegistry.umbran_counter);
            	entries.add(MFurniBOPBlocksRegistry.umbran_drawer_counter);
            	entries.add(MFurniBOPBlocksRegistry.umbran_double_drawer_counter);
            	entries.add(MFurniBOPBlocksRegistry.umbran_cupboard_counter);
            	entries.add(MFurniBOPBlocksRegistry.stripped_umbran_wardrobe);
            	entries.add(MFurniBOPBlocksRegistry.stripped_umbran_modern_wardrobe);
            	entries.add(MFurniBOPBlocksRegistry.stripped_umbran_double_wardrobe);
            	entries.add(MFurniBOPBlocksRegistry.stripped_umbran_bookshelf);
            	entries.add(MFurniBOPBlocksRegistry.stripped_umbran_bookshelf_cupboard);
            	entries.add(MFurniBOPBlocksRegistry.stripped_umbran_drawer);
            	entries.add(MFurniBOPBlocksRegistry.stripped_umbran_double_drawer);
            	entries.add(MFurniBOPBlocksRegistry.stripped_umbran_bookshelf_drawer);
            	entries.add(MFurniBOPBlocksRegistry.stripped_umbran_lower_bookshelf_drawer);
            	entries.add(MFurniBOPBlocksRegistry.stripped_umbran_large_drawer);
            	entries.add(MFurniBOPBlocksRegistry.stripped_umbran_lower_triple_drawer);
            	entries.add(MFurniBOPBlocksRegistry.stripped_umbran_triple_drawer);
            	entries.add(MFurniBOPBlocksRegistry.stripped_umbran_desk);
            	entries.add(MFurniBOPBlocksRegistry.stripped_umbran_covered_desk);
            	entries.add(MFurniBOPBlocksRegistry.stripped_umbran_modern_desk);
            	entries.add(MFurniBOPBlocksRegistry.stripped_umbran_table);
            	entries.add(MFurniBOPBlocksRegistry.stripped_umbran_end_table);
            	entries.add(MFurniBOPBlocksRegistry.stripped_umbran_coffee_table);
            	entries.add(MFurniBOPBlocksRegistry.stripped_umbran_glass_table);
            	entries.add(MFurniBOPBlocksRegistry.stripped_umbran_modern_chair);
            	entries.add(MFurniBOPBlocksRegistry.stripped_umbran_striped_chair);
            	entries.add(MFurniBOPBlocksRegistry.stripped_umbran_stool_chair);
            	entries.add(MFurniBOPBlocksRegistry.stripped_umbran_counter);
            	entries.add(MFurniBOPBlocksRegistry.stripped_umbran_drawer_counter);
            	entries.add(MFurniBOPBlocksRegistry.stripped_umbran_double_drawer_counter);
            	entries.add(MFurniBOPBlocksRegistry.stripped_umbran_cupboard_counter);
            	entries.add(MFurniBOPBlocksRegistry.umbran_kitchen_cabinet);
            	entries.add(MFurniBOPBlocksRegistry.umbran_double_kitchen_cabinet);
            	entries.add(MFurniBOPBlocksRegistry.umbran_glass_kitchen_cabinet);
            	entries.add(MFurniBOPBlocksRegistry.stripped_umbran_kitchen_cabinet);
            	entries.add(MFurniBOPBlocksRegistry.stripped_umbran_double_kitchen_cabinet);
            	entries.add(MFurniBOPBlocksRegistry.stripped_umbran_glass_kitchen_cabinet);
            	entries.add(MFurniBOPBlocksRegistry.willow_wardrobe);
            	entries.add(MFurniBOPBlocksRegistry.willow_modern_wardrobe);
            	entries.add(MFurniBOPBlocksRegistry.willow_double_wardrobe);
            	entries.add(MFurniBOPBlocksRegistry.willow_bookshelf);
            	entries.add(MFurniBOPBlocksRegistry.willow_bookshelf_cupboard);
            	entries.add(MFurniBOPBlocksRegistry.willow_drawer);
            	entries.add(MFurniBOPBlocksRegistry.willow_double_drawer);
            	entries.add(MFurniBOPBlocksRegistry.willow_bookshelf_drawer);
            	entries.add(MFurniBOPBlocksRegistry.willow_lower_bookshelf_drawer);
            	entries.add(MFurniBOPBlocksRegistry.willow_large_drawer);
            	entries.add(MFurniBOPBlocksRegistry.willow_lower_triple_drawer);
            	entries.add(MFurniBOPBlocksRegistry.willow_triple_drawer);
            	entries.add(MFurniBOPBlocksRegistry.willow_covered_desk);
            	entries.add(MFurniBOPBlocksRegistry.willow_modern_desk);
            	entries.add(MFurniBOPBlocksRegistry.willow_table);
            	entries.add(MFurniBOPBlocksRegistry.willow_end_table);
            	entries.add(MFurniBOPBlocksRegistry.willow_coffee_table);
            	entries.add(MFurniBOPBlocksRegistry.willow_glass_table);
            	entries.add(MFurniBOPBlocksRegistry.willow_chair);
            	entries.add(MFurniBOPBlocksRegistry.willow_modern_chair);
            	entries.add(MFurniBOPBlocksRegistry.willow_striped_chair);
            	entries.add(MFurniBOPBlocksRegistry.willow_stool_chair);
            	entries.add(MFurniBOPBlocksRegistry.willow_counter);
            	entries.add(MFurniBOPBlocksRegistry.willow_drawer_counter);
            	entries.add(MFurniBOPBlocksRegistry.willow_double_drawer_counter);
            	entries.add(MFurniBOPBlocksRegistry.willow_cupboard_counter);
            	entries.add(MFurniBOPBlocksRegistry.stripped_willow_wardrobe);
            	entries.add(MFurniBOPBlocksRegistry.stripped_willow_modern_wardrobe);
            	entries.add(MFurniBOPBlocksRegistry.stripped_willow_double_wardrobe);
            	entries.add(MFurniBOPBlocksRegistry.stripped_willow_bookshelf);
            	entries.add(MFurniBOPBlocksRegistry.stripped_willow_bookshelf_cupboard);
            	entries.add(MFurniBOPBlocksRegistry.stripped_willow_drawer);
            	entries.add(MFurniBOPBlocksRegistry.stripped_willow_double_drawer);
            	entries.add(MFurniBOPBlocksRegistry.stripped_willow_bookshelf_drawer);
            	entries.add(MFurniBOPBlocksRegistry.stripped_willow_lower_bookshelf_drawer);
            	entries.add(MFurniBOPBlocksRegistry.stripped_willow_large_drawer);
            	entries.add(MFurniBOPBlocksRegistry.stripped_willow_lower_triple_drawer);
            	entries.add(MFurniBOPBlocksRegistry.stripped_willow_triple_drawer);
            	entries.add(MFurniBOPBlocksRegistry.stripped_willow_desk);
            	entries.add(MFurniBOPBlocksRegistry.stripped_willow_covered_desk);
            	entries.add(MFurniBOPBlocksRegistry.stripped_willow_modern_desk);
            	entries.add(MFurniBOPBlocksRegistry.stripped_willow_table);
            	entries.add(MFurniBOPBlocksRegistry.stripped_willow_end_table);
            	entries.add(MFurniBOPBlocksRegistry.stripped_willow_coffee_table);
            	entries.add(MFurniBOPBlocksRegistry.stripped_willow_glass_table);
            	entries.add(MFurniBOPBlocksRegistry.stripped_willow_modern_chair);
            	entries.add(MFurniBOPBlocksRegistry.stripped_willow_striped_chair);
            	entries.add(MFurniBOPBlocksRegistry.stripped_willow_stool_chair);
            	entries.add(MFurniBOPBlocksRegistry.stripped_willow_counter);
            	entries.add(MFurniBOPBlocksRegistry.stripped_willow_drawer_counter);
            	entries.add(MFurniBOPBlocksRegistry.stripped_willow_double_drawer_counter);
            	entries.add(MFurniBOPBlocksRegistry.stripped_willow_cupboard_counter);
            	entries.add(MFurniBOPBlocksRegistry.willow_kitchen_cabinet);
            	entries.add(MFurniBOPBlocksRegistry.willow_double_kitchen_cabinet);
            	entries.add(MFurniBOPBlocksRegistry.willow_glass_kitchen_cabinet);
            	entries.add(MFurniBOPBlocksRegistry.stripped_willow_kitchen_cabinet);
            	entries.add(MFurniBOPBlocksRegistry.stripped_willow_double_kitchen_cabinet);
            	entries.add(MFurniBOPBlocksRegistry.stripped_willow_glass_kitchen_cabinet);
            	entries.add(MFurniBOPBlocksRegistry.empyreal_wardrobe);
            	entries.add(MFurniBOPBlocksRegistry.empyreal_modern_wardrobe);
            	entries.add(MFurniBOPBlocksRegistry.empyreal_double_wardrobe);
            	entries.add(MFurniBOPBlocksRegistry.empyreal_bookshelf);
            	entries.add(MFurniBOPBlocksRegistry.empyreal_bookshelf_cupboard);
            	entries.add(MFurniBOPBlocksRegistry.empyreal_drawer);
            	entries.add(MFurniBOPBlocksRegistry.empyreal_double_drawer);
            	entries.add(MFurniBOPBlocksRegistry.empyreal_bookshelf_drawer);
            	entries.add(MFurniBOPBlocksRegistry.empyreal_lower_bookshelf_drawer);
            	entries.add(MFurniBOPBlocksRegistry.empyreal_large_drawer);
            	entries.add(MFurniBOPBlocksRegistry.empyreal_lower_triple_drawer);
            	entries.add(MFurniBOPBlocksRegistry.empyreal_triple_drawer);
            	entries.add(MFurniBOPBlocksRegistry.empyreal_covered_desk);
            	entries.add(MFurniBOPBlocksRegistry.empyreal_modern_desk);
            	entries.add(MFurniBOPBlocksRegistry.empyreal_table);
            	entries.add(MFurniBOPBlocksRegistry.empyreal_end_table);
            	entries.add(MFurniBOPBlocksRegistry.empyreal_coffee_table);
            	entries.add(MFurniBOPBlocksRegistry.empyreal_glass_table);
            	entries.add(MFurniBOPBlocksRegistry.empyreal_chair);
            	entries.add(MFurniBOPBlocksRegistry.empyreal_modern_chair);
            	entries.add(MFurniBOPBlocksRegistry.empyreal_striped_chair);
            	entries.add(MFurniBOPBlocksRegistry.empyreal_stool_chair);
            	entries.add(MFurniBOPBlocksRegistry.empyreal_counter);
            	entries.add(MFurniBOPBlocksRegistry.empyreal_drawer_counter);
            	entries.add(MFurniBOPBlocksRegistry.empyreal_double_drawer_counter);
            	entries.add(MFurniBOPBlocksRegistry.empyreal_cupboard_counter);
            	entries.add(MFurniBOPBlocksRegistry.stripped_empyreal_wardrobe);
            	entries.add(MFurniBOPBlocksRegistry.stripped_empyreal_modern_wardrobe);
            	entries.add(MFurniBOPBlocksRegistry.stripped_empyreal_double_wardrobe);
            	entries.add(MFurniBOPBlocksRegistry.stripped_empyreal_bookshelf);
            	entries.add(MFurniBOPBlocksRegistry.stripped_empyreal_bookshelf_cupboard);
            	entries.add(MFurniBOPBlocksRegistry.stripped_empyreal_drawer);
            	entries.add(MFurniBOPBlocksRegistry.stripped_empyreal_double_drawer);
            	entries.add(MFurniBOPBlocksRegistry.stripped_empyreal_bookshelf_drawer);
            	entries.add(MFurniBOPBlocksRegistry.stripped_empyreal_lower_bookshelf_drawer);
            	entries.add(MFurniBOPBlocksRegistry.stripped_empyreal_large_drawer);
            	entries.add(MFurniBOPBlocksRegistry.stripped_empyreal_lower_triple_drawer);
            	entries.add(MFurniBOPBlocksRegistry.stripped_empyreal_triple_drawer);
            	entries.add(MFurniBOPBlocksRegistry.stripped_empyreal_desk);
            	entries.add(MFurniBOPBlocksRegistry.stripped_empyreal_covered_desk);
            	entries.add(MFurniBOPBlocksRegistry.stripped_empyreal_modern_desk);
            	entries.add(MFurniBOPBlocksRegistry.stripped_empyreal_table);
            	entries.add(MFurniBOPBlocksRegistry.stripped_empyreal_end_table);
            	entries.add(MFurniBOPBlocksRegistry.stripped_empyreal_coffee_table);
            	entries.add(MFurniBOPBlocksRegistry.stripped_empyreal_glass_table);
            	entries.add(MFurniBOPBlocksRegistry.stripped_empyreal_modern_chair);
            	entries.add(MFurniBOPBlocksRegistry.stripped_empyreal_striped_chair);
            	entries.add(MFurniBOPBlocksRegistry.stripped_empyreal_stool_chair);
            	entries.add(MFurniBOPBlocksRegistry.stripped_empyreal_counter);
            	entries.add(MFurniBOPBlocksRegistry.stripped_empyreal_drawer_counter);
            	entries.add(MFurniBOPBlocksRegistry.stripped_empyreal_double_drawer_counter);
            	entries.add(MFurniBOPBlocksRegistry.stripped_empyreal_cupboard_counter);
            	entries.add(MFurniBOPBlocksRegistry.empyreal_kitchen_cabinet);
            	entries.add(MFurniBOPBlocksRegistry.empyreal_double_kitchen_cabinet);
            	entries.add(MFurniBOPBlocksRegistry.empyreal_glass_kitchen_cabinet);
            	entries.add(MFurniBOPBlocksRegistry.stripped_empyreal_kitchen_cabinet);
            	entries.add(MFurniBOPBlocksRegistry.stripped_empyreal_double_kitchen_cabinet);
            	entries.add(MFurniBOPBlocksRegistry.stripped_empyreal_glass_kitchen_cabinet);
            }).build();
 
	@Override
	public void onInitialize()
	{
    	LOGGER.info("Macaw's Furnitures - Biomes O Plenty... Loading...");
        Registry.register(Registries.ITEM_GROUP, Identifier.of(MODID, "mfurnibop_ct"), MFURNIBOP_CT);
		MFurniBOPBlocksRegistry.registry();
		addCompatibleBlocksToFurnitureStorage();
    	LOGGER.info("Macaw's Furnitures - Biomes O Plenty... Finish...");
	}
	
	private static void addCompatibleBlocks(Block... blocks)
	{
		for(Block b : blocks)
		{
			MacawsFurniture.FURNITURE_BLOCK_ENTITY.addSupportedBlock(b);
		}
    }

	private void addCompatibleBlocksToFurnitureStorage()
    {
        addCompatibleBlocks(MFurniBOPBlocksRegistry.dead_wardrobe,
		MFurniBOPBlocksRegistry.dead_modern_wardrobe,
		MFurniBOPBlocksRegistry.dead_double_wardrobe,
		MFurniBOPBlocksRegistry.dead_bookshelf,
		MFurniBOPBlocksRegistry.dead_bookshelf_cupboard,
		MFurniBOPBlocksRegistry.dead_drawer,
		MFurniBOPBlocksRegistry.dead_double_drawer,
		MFurniBOPBlocksRegistry.dead_bookshelf_drawer,
		MFurniBOPBlocksRegistry.dead_lower_bookshelf_drawer,
		MFurniBOPBlocksRegistry.dead_large_drawer,
		MFurniBOPBlocksRegistry.dead_lower_triple_drawer,
		MFurniBOPBlocksRegistry.dead_triple_drawer,
		MFurniBOPBlocksRegistry.dead_drawer_counter,
		MFurniBOPBlocksRegistry.dead_double_drawer_counter,
		MFurniBOPBlocksRegistry.dead_cupboard_counter,
		MFurniBOPBlocksRegistry.stripped_dead_wardrobe,
		MFurniBOPBlocksRegistry.stripped_dead_modern_wardrobe,
		MFurniBOPBlocksRegistry.stripped_dead_double_wardrobe,
		MFurniBOPBlocksRegistry.stripped_dead_bookshelf,
		MFurniBOPBlocksRegistry.stripped_dead_bookshelf_cupboard,
		MFurniBOPBlocksRegistry.stripped_dead_drawer,
		MFurniBOPBlocksRegistry.stripped_dead_double_drawer,
		MFurniBOPBlocksRegistry.stripped_dead_bookshelf_drawer,
		MFurniBOPBlocksRegistry.stripped_dead_lower_bookshelf_drawer,
		MFurniBOPBlocksRegistry.stripped_dead_large_drawer,
		MFurniBOPBlocksRegistry.stripped_dead_lower_triple_drawer,
		MFurniBOPBlocksRegistry.stripped_dead_triple_drawer,
		MFurniBOPBlocksRegistry.stripped_dead_counter,
		MFurniBOPBlocksRegistry.stripped_dead_drawer_counter,
		MFurniBOPBlocksRegistry.stripped_dead_double_drawer_counter,
		MFurniBOPBlocksRegistry.stripped_dead_cupboard_counter,
		MFurniBOPBlocksRegistry.dead_kitchen_cabinet,
		MFurniBOPBlocksRegistry.dead_double_kitchen_cabinet,
		MFurniBOPBlocksRegistry.dead_glass_kitchen_cabinet,
		MFurniBOPBlocksRegistry.stripped_dead_kitchen_cabinet,
		MFurniBOPBlocksRegistry.stripped_dead_double_kitchen_cabinet,
		MFurniBOPBlocksRegistry.stripped_dead_glass_kitchen_cabinet,MFurniBOPBlocksRegistry.fir_wardrobe,
		MFurniBOPBlocksRegistry.fir_modern_wardrobe,
		MFurniBOPBlocksRegistry.fir_double_wardrobe,
		MFurniBOPBlocksRegistry.fir_bookshelf,
		MFurniBOPBlocksRegistry.fir_bookshelf_cupboard,
		MFurniBOPBlocksRegistry.fir_drawer,
		MFurniBOPBlocksRegistry.fir_double_drawer,
		MFurniBOPBlocksRegistry.fir_bookshelf_drawer,
		MFurniBOPBlocksRegistry.fir_lower_bookshelf_drawer,
		MFurniBOPBlocksRegistry.fir_large_drawer,
		MFurniBOPBlocksRegistry.fir_lower_triple_drawer,
		MFurniBOPBlocksRegistry.fir_triple_drawer,
		MFurniBOPBlocksRegistry.fir_drawer_counter,
		MFurniBOPBlocksRegistry.fir_double_drawer_counter,
		MFurniBOPBlocksRegistry.fir_cupboard_counter,
		MFurniBOPBlocksRegistry.stripped_fir_wardrobe,
		MFurniBOPBlocksRegistry.stripped_fir_modern_wardrobe,
		MFurniBOPBlocksRegistry.stripped_fir_double_wardrobe,
		MFurniBOPBlocksRegistry.stripped_fir_bookshelf,
		MFurniBOPBlocksRegistry.stripped_fir_bookshelf_cupboard,
		MFurniBOPBlocksRegistry.stripped_fir_drawer,
		MFurniBOPBlocksRegistry.stripped_fir_double_drawer,
		MFurniBOPBlocksRegistry.stripped_fir_bookshelf_drawer,
		MFurniBOPBlocksRegistry.stripped_fir_lower_bookshelf_drawer,
		MFurniBOPBlocksRegistry.stripped_fir_large_drawer,
		MFurniBOPBlocksRegistry.stripped_fir_lower_triple_drawer,
		MFurniBOPBlocksRegistry.stripped_fir_triple_drawer,
		MFurniBOPBlocksRegistry.stripped_fir_counter,
		MFurniBOPBlocksRegistry.stripped_fir_drawer_counter,
		MFurniBOPBlocksRegistry.stripped_fir_double_drawer_counter,
		MFurniBOPBlocksRegistry.stripped_fir_cupboard_counter,
		MFurniBOPBlocksRegistry.fir_kitchen_cabinet,
		MFurniBOPBlocksRegistry.fir_double_kitchen_cabinet,
		MFurniBOPBlocksRegistry.fir_glass_kitchen_cabinet,
		MFurniBOPBlocksRegistry.stripped_fir_kitchen_cabinet,
		MFurniBOPBlocksRegistry.stripped_fir_double_kitchen_cabinet,
		MFurniBOPBlocksRegistry.stripped_fir_glass_kitchen_cabinet,MFurniBOPBlocksRegistry.hellbark_wardrobe,
		MFurniBOPBlocksRegistry.hellbark_modern_wardrobe,
		MFurniBOPBlocksRegistry.hellbark_double_wardrobe,
		MFurniBOPBlocksRegistry.hellbark_bookshelf,
		MFurniBOPBlocksRegistry.hellbark_bookshelf_cupboard,
		MFurniBOPBlocksRegistry.hellbark_drawer,
		MFurniBOPBlocksRegistry.hellbark_double_drawer,
		MFurniBOPBlocksRegistry.hellbark_bookshelf_drawer,
		MFurniBOPBlocksRegistry.hellbark_lower_bookshelf_drawer,
		MFurniBOPBlocksRegistry.hellbark_large_drawer,
		MFurniBOPBlocksRegistry.hellbark_lower_triple_drawer,
		MFurniBOPBlocksRegistry.hellbark_triple_drawer,
		MFurniBOPBlocksRegistry.hellbark_drawer_counter,
		MFurniBOPBlocksRegistry.hellbark_double_drawer_counter,
		MFurniBOPBlocksRegistry.hellbark_cupboard_counter,
		MFurniBOPBlocksRegistry.stripped_hellbark_wardrobe,
		MFurniBOPBlocksRegistry.stripped_hellbark_modern_wardrobe,
		MFurniBOPBlocksRegistry.stripped_hellbark_double_wardrobe,
		MFurniBOPBlocksRegistry.stripped_hellbark_bookshelf,
		MFurniBOPBlocksRegistry.stripped_hellbark_bookshelf_cupboard,
		MFurniBOPBlocksRegistry.stripped_hellbark_drawer,
		MFurniBOPBlocksRegistry.stripped_hellbark_double_drawer,
		MFurniBOPBlocksRegistry.stripped_hellbark_bookshelf_drawer,
		MFurniBOPBlocksRegistry.stripped_hellbark_lower_bookshelf_drawer,
		MFurniBOPBlocksRegistry.stripped_hellbark_large_drawer,
		MFurniBOPBlocksRegistry.stripped_hellbark_lower_triple_drawer,
		MFurniBOPBlocksRegistry.stripped_hellbark_triple_drawer,
		MFurniBOPBlocksRegistry.stripped_hellbark_counter,
		MFurniBOPBlocksRegistry.stripped_hellbark_drawer_counter,
		MFurniBOPBlocksRegistry.stripped_hellbark_double_drawer_counter,
		MFurniBOPBlocksRegistry.stripped_hellbark_cupboard_counter,
		MFurniBOPBlocksRegistry.hellbark_kitchen_cabinet,
		MFurniBOPBlocksRegistry.hellbark_double_kitchen_cabinet,
		MFurniBOPBlocksRegistry.hellbark_glass_kitchen_cabinet,
		MFurniBOPBlocksRegistry.stripped_hellbark_kitchen_cabinet,
		MFurniBOPBlocksRegistry.stripped_hellbark_double_kitchen_cabinet,
		MFurniBOPBlocksRegistry.stripped_hellbark_glass_kitchen_cabinet,MFurniBOPBlocksRegistry.jacaranda_wardrobe,
		MFurniBOPBlocksRegistry.jacaranda_modern_wardrobe,
		MFurniBOPBlocksRegistry.jacaranda_double_wardrobe,
		MFurniBOPBlocksRegistry.jacaranda_bookshelf,
		MFurniBOPBlocksRegistry.jacaranda_bookshelf_cupboard,
		MFurniBOPBlocksRegistry.jacaranda_drawer,
		MFurniBOPBlocksRegistry.jacaranda_double_drawer,
		MFurniBOPBlocksRegistry.jacaranda_bookshelf_drawer,
		MFurniBOPBlocksRegistry.jacaranda_lower_bookshelf_drawer,
		MFurniBOPBlocksRegistry.jacaranda_large_drawer,
		MFurniBOPBlocksRegistry.jacaranda_lower_triple_drawer,
		MFurniBOPBlocksRegistry.jacaranda_triple_drawer,
		MFurniBOPBlocksRegistry.jacaranda_drawer_counter,
		MFurniBOPBlocksRegistry.jacaranda_double_drawer_counter,
		MFurniBOPBlocksRegistry.jacaranda_cupboard_counter,
		MFurniBOPBlocksRegistry.stripped_jacaranda_wardrobe,
		MFurniBOPBlocksRegistry.stripped_jacaranda_modern_wardrobe,
		MFurniBOPBlocksRegistry.stripped_jacaranda_double_wardrobe,
		MFurniBOPBlocksRegistry.stripped_jacaranda_bookshelf,
		MFurniBOPBlocksRegistry.stripped_jacaranda_bookshelf_cupboard,
		MFurniBOPBlocksRegistry.stripped_jacaranda_drawer,
		MFurniBOPBlocksRegistry.stripped_jacaranda_double_drawer,
		MFurniBOPBlocksRegistry.stripped_jacaranda_bookshelf_drawer,
		MFurniBOPBlocksRegistry.stripped_jacaranda_lower_bookshelf_drawer,
		MFurniBOPBlocksRegistry.stripped_jacaranda_large_drawer,
		MFurniBOPBlocksRegistry.stripped_jacaranda_lower_triple_drawer,
		MFurniBOPBlocksRegistry.stripped_jacaranda_triple_drawer,
		MFurniBOPBlocksRegistry.stripped_jacaranda_counter,
		MFurniBOPBlocksRegistry.stripped_jacaranda_drawer_counter,
		MFurniBOPBlocksRegistry.stripped_jacaranda_double_drawer_counter,
		MFurniBOPBlocksRegistry.stripped_jacaranda_cupboard_counter,
		MFurniBOPBlocksRegistry.jacaranda_kitchen_cabinet,
		MFurniBOPBlocksRegistry.jacaranda_double_kitchen_cabinet,
		MFurniBOPBlocksRegistry.jacaranda_glass_kitchen_cabinet,
		MFurniBOPBlocksRegistry.stripped_jacaranda_kitchen_cabinet,
		MFurniBOPBlocksRegistry.stripped_jacaranda_double_kitchen_cabinet,
		MFurniBOPBlocksRegistry.stripped_jacaranda_glass_kitchen_cabinet,MFurniBOPBlocksRegistry.magic_wardrobe,
		MFurniBOPBlocksRegistry.magic_modern_wardrobe,
		MFurniBOPBlocksRegistry.magic_double_wardrobe,
		MFurniBOPBlocksRegistry.magic_bookshelf,
		MFurniBOPBlocksRegistry.magic_bookshelf_cupboard,
		MFurniBOPBlocksRegistry.magic_drawer,
		MFurniBOPBlocksRegistry.magic_double_drawer,
		MFurniBOPBlocksRegistry.magic_bookshelf_drawer,
		MFurniBOPBlocksRegistry.magic_lower_bookshelf_drawer,
		MFurniBOPBlocksRegistry.magic_large_drawer,
		MFurniBOPBlocksRegistry.magic_lower_triple_drawer,
		MFurniBOPBlocksRegistry.magic_triple_drawer,
		MFurniBOPBlocksRegistry.magic_drawer_counter,
		MFurniBOPBlocksRegistry.magic_double_drawer_counter,
		MFurniBOPBlocksRegistry.magic_cupboard_counter,
		MFurniBOPBlocksRegistry.stripped_magic_wardrobe,
		MFurniBOPBlocksRegistry.stripped_magic_modern_wardrobe,
		MFurniBOPBlocksRegistry.stripped_magic_double_wardrobe,
		MFurniBOPBlocksRegistry.stripped_magic_bookshelf,
		MFurniBOPBlocksRegistry.stripped_magic_bookshelf_cupboard,
		MFurniBOPBlocksRegistry.stripped_magic_drawer,
		MFurniBOPBlocksRegistry.stripped_magic_double_drawer,
		MFurniBOPBlocksRegistry.stripped_magic_bookshelf_drawer,
		MFurniBOPBlocksRegistry.stripped_magic_lower_bookshelf_drawer,
		MFurniBOPBlocksRegistry.stripped_magic_large_drawer,
		MFurniBOPBlocksRegistry.stripped_magic_lower_triple_drawer,
		MFurniBOPBlocksRegistry.stripped_magic_triple_drawer,
		MFurniBOPBlocksRegistry.stripped_magic_counter,
		MFurniBOPBlocksRegistry.stripped_magic_drawer_counter,
		MFurniBOPBlocksRegistry.stripped_magic_double_drawer_counter,
		MFurniBOPBlocksRegistry.stripped_magic_cupboard_counter,
		MFurniBOPBlocksRegistry.magic_kitchen_cabinet,
		MFurniBOPBlocksRegistry.magic_double_kitchen_cabinet,
		MFurniBOPBlocksRegistry.magic_glass_kitchen_cabinet,
		MFurniBOPBlocksRegistry.stripped_magic_kitchen_cabinet,
		MFurniBOPBlocksRegistry.stripped_magic_double_kitchen_cabinet,
		MFurniBOPBlocksRegistry.stripped_magic_glass_kitchen_cabinet,MFurniBOPBlocksRegistry.mahogany_wardrobe,
		MFurniBOPBlocksRegistry.mahogany_modern_wardrobe,
		MFurniBOPBlocksRegistry.mahogany_double_wardrobe,
		MFurniBOPBlocksRegistry.mahogany_bookshelf,
		MFurniBOPBlocksRegistry.mahogany_bookshelf_cupboard,
		MFurniBOPBlocksRegistry.mahogany_drawer,
		MFurniBOPBlocksRegistry.mahogany_double_drawer,
		MFurniBOPBlocksRegistry.mahogany_bookshelf_drawer,
		MFurniBOPBlocksRegistry.mahogany_lower_bookshelf_drawer,
		MFurniBOPBlocksRegistry.mahogany_large_drawer,
		MFurniBOPBlocksRegistry.mahogany_lower_triple_drawer,
		MFurniBOPBlocksRegistry.mahogany_triple_drawer,
		MFurniBOPBlocksRegistry.mahogany_drawer_counter,
		MFurniBOPBlocksRegistry.mahogany_double_drawer_counter,
		MFurniBOPBlocksRegistry.mahogany_cupboard_counter,
		MFurniBOPBlocksRegistry.stripped_mahogany_wardrobe,
		MFurniBOPBlocksRegistry.stripped_mahogany_modern_wardrobe,
		MFurniBOPBlocksRegistry.stripped_mahogany_double_wardrobe,
		MFurniBOPBlocksRegistry.stripped_mahogany_bookshelf,
		MFurniBOPBlocksRegistry.stripped_mahogany_bookshelf_cupboard,
		MFurniBOPBlocksRegistry.stripped_mahogany_drawer,
		MFurniBOPBlocksRegistry.stripped_mahogany_double_drawer,
		MFurniBOPBlocksRegistry.stripped_mahogany_bookshelf_drawer,
		MFurniBOPBlocksRegistry.stripped_mahogany_lower_bookshelf_drawer,
		MFurniBOPBlocksRegistry.stripped_mahogany_large_drawer,
		MFurniBOPBlocksRegistry.stripped_mahogany_lower_triple_drawer,
		MFurniBOPBlocksRegistry.stripped_mahogany_triple_drawer,
		MFurniBOPBlocksRegistry.stripped_mahogany_counter,
		MFurniBOPBlocksRegistry.stripped_mahogany_drawer_counter,
		MFurniBOPBlocksRegistry.stripped_mahogany_double_drawer_counter,
		MFurniBOPBlocksRegistry.stripped_mahogany_cupboard_counter,
		MFurniBOPBlocksRegistry.mahogany_kitchen_cabinet,
		MFurniBOPBlocksRegistry.mahogany_double_kitchen_cabinet,
		MFurniBOPBlocksRegistry.mahogany_glass_kitchen_cabinet,
		MFurniBOPBlocksRegistry.stripped_mahogany_kitchen_cabinet,
		MFurniBOPBlocksRegistry.stripped_mahogany_double_kitchen_cabinet,
		MFurniBOPBlocksRegistry.stripped_mahogany_glass_kitchen_cabinet,MFurniBOPBlocksRegistry.palm_wardrobe,
		MFurniBOPBlocksRegistry.palm_modern_wardrobe,
		MFurniBOPBlocksRegistry.palm_double_wardrobe,
		MFurniBOPBlocksRegistry.palm_bookshelf,
		MFurniBOPBlocksRegistry.palm_bookshelf_cupboard,
		MFurniBOPBlocksRegistry.palm_drawer,
		MFurniBOPBlocksRegistry.palm_double_drawer,
		MFurniBOPBlocksRegistry.palm_bookshelf_drawer,
		MFurniBOPBlocksRegistry.palm_lower_bookshelf_drawer,
		MFurniBOPBlocksRegistry.palm_large_drawer,
		MFurniBOPBlocksRegistry.palm_lower_triple_drawer,
		MFurniBOPBlocksRegistry.palm_triple_drawer,
		MFurniBOPBlocksRegistry.palm_drawer_counter,
		MFurniBOPBlocksRegistry.palm_double_drawer_counter,
		MFurniBOPBlocksRegistry.palm_cupboard_counter,
		MFurniBOPBlocksRegistry.stripped_palm_wardrobe,
		MFurniBOPBlocksRegistry.stripped_palm_modern_wardrobe,
		MFurniBOPBlocksRegistry.stripped_palm_double_wardrobe,
		MFurniBOPBlocksRegistry.stripped_palm_bookshelf,
		MFurniBOPBlocksRegistry.stripped_palm_bookshelf_cupboard,
		MFurniBOPBlocksRegistry.stripped_palm_drawer,
		MFurniBOPBlocksRegistry.stripped_palm_double_drawer,
		MFurniBOPBlocksRegistry.stripped_palm_bookshelf_drawer,
		MFurniBOPBlocksRegistry.stripped_palm_lower_bookshelf_drawer,
		MFurniBOPBlocksRegistry.stripped_palm_large_drawer,
		MFurniBOPBlocksRegistry.stripped_palm_lower_triple_drawer,
		MFurniBOPBlocksRegistry.stripped_palm_triple_drawer,
		MFurniBOPBlocksRegistry.stripped_palm_counter,
		MFurniBOPBlocksRegistry.stripped_palm_drawer_counter,
		MFurniBOPBlocksRegistry.stripped_palm_double_drawer_counter,
		MFurniBOPBlocksRegistry.stripped_palm_cupboard_counter,
		MFurniBOPBlocksRegistry.palm_kitchen_cabinet,
		MFurniBOPBlocksRegistry.palm_double_kitchen_cabinet,
		MFurniBOPBlocksRegistry.palm_glass_kitchen_cabinet,
		MFurniBOPBlocksRegistry.stripped_palm_kitchen_cabinet,
		MFurniBOPBlocksRegistry.stripped_palm_double_kitchen_cabinet,
		MFurniBOPBlocksRegistry.stripped_palm_glass_kitchen_cabinet,MFurniBOPBlocksRegistry.redwood_wardrobe,
		MFurniBOPBlocksRegistry.redwood_modern_wardrobe,
		MFurniBOPBlocksRegistry.redwood_double_wardrobe,
		MFurniBOPBlocksRegistry.redwood_bookshelf,
		MFurniBOPBlocksRegistry.redwood_bookshelf_cupboard,
		MFurniBOPBlocksRegistry.redwood_drawer,
		MFurniBOPBlocksRegistry.redwood_double_drawer,
		MFurniBOPBlocksRegistry.redwood_bookshelf_drawer,
		MFurniBOPBlocksRegistry.redwood_lower_bookshelf_drawer,
		MFurniBOPBlocksRegistry.redwood_large_drawer,
		MFurniBOPBlocksRegistry.redwood_lower_triple_drawer,
		MFurniBOPBlocksRegistry.redwood_triple_drawer,
		MFurniBOPBlocksRegistry.redwood_drawer_counter,
		MFurniBOPBlocksRegistry.redwood_double_drawer_counter,
		MFurniBOPBlocksRegistry.redwood_cupboard_counter,
		MFurniBOPBlocksRegistry.stripped_redwood_wardrobe,
		MFurniBOPBlocksRegistry.stripped_redwood_modern_wardrobe,
		MFurniBOPBlocksRegistry.stripped_redwood_double_wardrobe,
		MFurniBOPBlocksRegistry.stripped_redwood_bookshelf,
		MFurniBOPBlocksRegistry.stripped_redwood_bookshelf_cupboard,
		MFurniBOPBlocksRegistry.stripped_redwood_drawer,
		MFurniBOPBlocksRegistry.stripped_redwood_double_drawer,
		MFurniBOPBlocksRegistry.stripped_redwood_bookshelf_drawer,
		MFurniBOPBlocksRegistry.stripped_redwood_lower_bookshelf_drawer,
		MFurniBOPBlocksRegistry.stripped_redwood_large_drawer,
		MFurniBOPBlocksRegistry.stripped_redwood_lower_triple_drawer,
		MFurniBOPBlocksRegistry.stripped_redwood_triple_drawer,
		MFurniBOPBlocksRegistry.stripped_redwood_counter,
		MFurniBOPBlocksRegistry.stripped_redwood_drawer_counter,
		MFurniBOPBlocksRegistry.stripped_redwood_double_drawer_counter,
		MFurniBOPBlocksRegistry.stripped_redwood_cupboard_counter,
		MFurniBOPBlocksRegistry.redwood_kitchen_cabinet,
		MFurniBOPBlocksRegistry.redwood_double_kitchen_cabinet,
		MFurniBOPBlocksRegistry.redwood_glass_kitchen_cabinet,
		MFurniBOPBlocksRegistry.stripped_redwood_kitchen_cabinet,
		MFurniBOPBlocksRegistry.stripped_redwood_double_kitchen_cabinet,
		MFurniBOPBlocksRegistry.stripped_redwood_glass_kitchen_cabinet,MFurniBOPBlocksRegistry.umbran_wardrobe,
		MFurniBOPBlocksRegistry.umbran_modern_wardrobe,
		MFurniBOPBlocksRegistry.umbran_double_wardrobe,
		MFurniBOPBlocksRegistry.umbran_bookshelf,
		MFurniBOPBlocksRegistry.umbran_bookshelf_cupboard,
		MFurniBOPBlocksRegistry.umbran_drawer,
		MFurniBOPBlocksRegistry.umbran_double_drawer,
		MFurniBOPBlocksRegistry.umbran_bookshelf_drawer,
		MFurniBOPBlocksRegistry.umbran_lower_bookshelf_drawer,
		MFurniBOPBlocksRegistry.umbran_large_drawer,
		MFurniBOPBlocksRegistry.umbran_lower_triple_drawer,
		MFurniBOPBlocksRegistry.umbran_triple_drawer,
		MFurniBOPBlocksRegistry.umbran_drawer_counter,
		MFurniBOPBlocksRegistry.umbran_double_drawer_counter,
		MFurniBOPBlocksRegistry.umbran_cupboard_counter,
		MFurniBOPBlocksRegistry.stripped_umbran_wardrobe,
		MFurniBOPBlocksRegistry.stripped_umbran_modern_wardrobe,
		MFurniBOPBlocksRegistry.stripped_umbran_double_wardrobe,
		MFurniBOPBlocksRegistry.stripped_umbran_bookshelf,
		MFurniBOPBlocksRegistry.stripped_umbran_bookshelf_cupboard,
		MFurniBOPBlocksRegistry.stripped_umbran_drawer,
		MFurniBOPBlocksRegistry.stripped_umbran_double_drawer,
		MFurniBOPBlocksRegistry.stripped_umbran_bookshelf_drawer,
		MFurniBOPBlocksRegistry.stripped_umbran_lower_bookshelf_drawer,
		MFurniBOPBlocksRegistry.stripped_umbran_large_drawer,
		MFurniBOPBlocksRegistry.stripped_umbran_lower_triple_drawer,
		MFurniBOPBlocksRegistry.stripped_umbran_triple_drawer,
		MFurniBOPBlocksRegistry.stripped_umbran_counter,
		MFurniBOPBlocksRegistry.stripped_umbran_drawer_counter,
		MFurniBOPBlocksRegistry.stripped_umbran_double_drawer_counter,
		MFurniBOPBlocksRegistry.stripped_umbran_cupboard_counter,
		MFurniBOPBlocksRegistry.umbran_kitchen_cabinet,
		MFurniBOPBlocksRegistry.umbran_double_kitchen_cabinet,
		MFurniBOPBlocksRegistry.umbran_glass_kitchen_cabinet,
		MFurniBOPBlocksRegistry.stripped_umbran_kitchen_cabinet,
		MFurniBOPBlocksRegistry.stripped_umbran_double_kitchen_cabinet,
		MFurniBOPBlocksRegistry.stripped_umbran_glass_kitchen_cabinet,MFurniBOPBlocksRegistry.willow_wardrobe,
		MFurniBOPBlocksRegistry.willow_modern_wardrobe,
		MFurniBOPBlocksRegistry.willow_double_wardrobe,
		MFurniBOPBlocksRegistry.willow_bookshelf,
		MFurniBOPBlocksRegistry.willow_bookshelf_cupboard,
		MFurniBOPBlocksRegistry.willow_drawer,
		MFurniBOPBlocksRegistry.willow_double_drawer,
		MFurniBOPBlocksRegistry.willow_bookshelf_drawer,
		MFurniBOPBlocksRegistry.willow_lower_bookshelf_drawer,
		MFurniBOPBlocksRegistry.willow_large_drawer,
		MFurniBOPBlocksRegistry.willow_lower_triple_drawer,
		MFurniBOPBlocksRegistry.willow_triple_drawer,
		MFurniBOPBlocksRegistry.willow_drawer_counter,
		MFurniBOPBlocksRegistry.willow_double_drawer_counter,
		MFurniBOPBlocksRegistry.willow_cupboard_counter,
		MFurniBOPBlocksRegistry.stripped_willow_wardrobe,
		MFurniBOPBlocksRegistry.stripped_willow_modern_wardrobe,
		MFurniBOPBlocksRegistry.stripped_willow_double_wardrobe,
		MFurniBOPBlocksRegistry.stripped_willow_bookshelf,
		MFurniBOPBlocksRegistry.stripped_willow_bookshelf_cupboard,
		MFurniBOPBlocksRegistry.stripped_willow_drawer,
		MFurniBOPBlocksRegistry.stripped_willow_double_drawer,
		MFurniBOPBlocksRegistry.stripped_willow_bookshelf_drawer,
		MFurniBOPBlocksRegistry.stripped_willow_lower_bookshelf_drawer,
		MFurniBOPBlocksRegistry.stripped_willow_large_drawer,
		MFurniBOPBlocksRegistry.stripped_willow_lower_triple_drawer,
		MFurniBOPBlocksRegistry.stripped_willow_triple_drawer,
		MFurniBOPBlocksRegistry.stripped_willow_counter,
		MFurniBOPBlocksRegistry.stripped_willow_drawer_counter,
		MFurniBOPBlocksRegistry.stripped_willow_double_drawer_counter,
		MFurniBOPBlocksRegistry.stripped_willow_cupboard_counter,
		MFurniBOPBlocksRegistry.willow_kitchen_cabinet,
		MFurniBOPBlocksRegistry.willow_double_kitchen_cabinet,
		MFurniBOPBlocksRegistry.willow_glass_kitchen_cabinet,
		MFurniBOPBlocksRegistry.stripped_willow_kitchen_cabinet,
		MFurniBOPBlocksRegistry.stripped_willow_double_kitchen_cabinet,
		MFurniBOPBlocksRegistry.stripped_willow_glass_kitchen_cabinet,MFurniBOPBlocksRegistry.empyreal_wardrobe,
		MFurniBOPBlocksRegistry.empyreal_modern_wardrobe,
		MFurniBOPBlocksRegistry.empyreal_double_wardrobe,
		MFurniBOPBlocksRegistry.empyreal_bookshelf,
		MFurniBOPBlocksRegistry.empyreal_bookshelf_cupboard,
		MFurniBOPBlocksRegistry.empyreal_drawer,
		MFurniBOPBlocksRegistry.empyreal_double_drawer,
		MFurniBOPBlocksRegistry.empyreal_bookshelf_drawer,
		MFurniBOPBlocksRegistry.empyreal_lower_bookshelf_drawer,
		MFurniBOPBlocksRegistry.empyreal_large_drawer,
		MFurniBOPBlocksRegistry.empyreal_lower_triple_drawer,
		MFurniBOPBlocksRegistry.empyreal_triple_drawer,
		MFurniBOPBlocksRegistry.empyreal_drawer_counter,
		MFurniBOPBlocksRegistry.empyreal_double_drawer_counter,
		MFurniBOPBlocksRegistry.empyreal_cupboard_counter,
		MFurniBOPBlocksRegistry.stripped_empyreal_wardrobe,
		MFurniBOPBlocksRegistry.stripped_empyreal_modern_wardrobe,
		MFurniBOPBlocksRegistry.stripped_empyreal_double_wardrobe,
		MFurniBOPBlocksRegistry.stripped_empyreal_bookshelf,
		MFurniBOPBlocksRegistry.stripped_empyreal_bookshelf_cupboard,
		MFurniBOPBlocksRegistry.stripped_empyreal_drawer,
		MFurniBOPBlocksRegistry.stripped_empyreal_double_drawer,
		MFurniBOPBlocksRegistry.stripped_empyreal_bookshelf_drawer,
		MFurniBOPBlocksRegistry.stripped_empyreal_lower_bookshelf_drawer,
		MFurniBOPBlocksRegistry.stripped_empyreal_large_drawer,
		MFurniBOPBlocksRegistry.stripped_empyreal_lower_triple_drawer,
		MFurniBOPBlocksRegistry.stripped_empyreal_triple_drawer,
		MFurniBOPBlocksRegistry.stripped_empyreal_counter,
		MFurniBOPBlocksRegistry.stripped_empyreal_drawer_counter,
		MFurniBOPBlocksRegistry.stripped_empyreal_double_drawer_counter,
		MFurniBOPBlocksRegistry.stripped_empyreal_cupboard_counter,
		MFurniBOPBlocksRegistry.empyreal_kitchen_cabinet,
		MFurniBOPBlocksRegistry.empyreal_double_kitchen_cabinet,
		MFurniBOPBlocksRegistry.empyreal_glass_kitchen_cabinet,
		MFurniBOPBlocksRegistry.stripped_empyreal_kitchen_cabinet,
		MFurniBOPBlocksRegistry.stripped_empyreal_double_kitchen_cabinet,
		MFurniBOPBlocksRegistry.stripped_empyreal_glass_kitchen_cabinet);
   }
}