modLoader="javafml"
loaderVersion="[44,)"
license="All rights reserved"
issueTrackerURL="https://github.com/Samlegamer/Macaw-s-Furnitures-Compat/issues"

[[mods]] #mandatory
modId="mcwfurnituresbyg"
version="1.19.3-1.2"
displayName="Macaw's Furnitures - BYG"
displayURL="https://www.curseforge.com/minecraft/mc-mods/macaws-furnitures-oh-the-biomes-youll-go"
logoFile="logo.png"
credits="sketch_macaw"
authors="Samlegamer"

description='''
Compatibility Oh the Biomes You'll Go with Macaw's Furnitures for Minecraft 1.19.3 !
'''

[[dependencies.mcwfurnituresbyg]]
    modId="forge"
    mandatory=true
    versionRange="[44,)"
    ordering="NONE"
    side="BOTH"

[[dependencies.mcwfurnituresbyg]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.19.3,1.20)"
    ordering="NONE"
    side="BOTH"

[[dependencies.mcwfurnituresbyg]]
modId="terrablender"
mandatory=true
versionRange="NONE"
ordering="BEFORE"
side="BOTH"

[[dependencies.mcwfurnituresbyg]]
modId="byg"
mandatory=true
versionRange="NONE"
ordering="BEFORE"
side="BOTH"

[[dependencies.mcwfurnituresbyg]]
modId="mcwfurnitures"
mandatory=true
versionRange="NONE"
ordering="BEFORE"
side="BOTH"