modLoader="javafml"
loaderVersion="[43,)"
license="All rights reserved"
issueTrackerURL="https://github.com/Samlegamer/Macaw-s-Furnitures-Compat/issues"

[[mods]] #mandatory
modId="mcwfurnituresbop"
version="1.19.2-1.3"
displayName="Macaw's Furnitures - BOP"
displayURL="https://www.curseforge.com/minecraft/mc-mods/macaws-furnitures-biomes-o-plenty"
logoFile="logo.png"
credits="sketch_macaw"
authors="Samlegamer"

description='''
Compatibility Biome O' Plenty with Macaw's Furnitures for Minecraft 1.19.2.
'''

[[dependencies.mcwfurnituresbop]]
    modId="forge"
    mandatory=true
    versionRange="[43,)"
    ordering="NONE"
    side="BOTH"

[[dependencies.mcwfurnituresbop]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.19.2,1.20)"
    ordering="NONE"
    side="BOTH"