modLoader="javafml"
loaderVersion="[44,)"
license="All rights reserved"
issueTrackerURL="https://github.com/Samlegamer/Macaw-s-Furnitures-Compat/issues"

[[mods]] #mandatory
modId="mcwfurnituresbop"
version="1.19.3-1.2"
displayName="Macaw's Furnitures - BOP"
displayURL="https://www.curseforge.com/minecraft/mc-mods/macaws-furnitures-biomes-o-plenty"
logoFile="logo.png"
credits="sketch_macaw"
authors="Samlegamer"

description='''
Compatibility Biome O' Plenty with Macaw's Furnitures for Minecraft 1.19.3.
'''

[[dependencies.mcwfurnituresbop]]
    modId="forge"
    mandatory=true
    versionRange="[44,)"
    ordering="NONE"
    side="BOTH"

[[dependencies.mcwfurnituresbop]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.19.3,1.20)"
    ordering="NONE"
    side="BOTH"

[[dependencies.mcwfurnituresbop]]
modId="terrablender"
mandatory=true
versionRange="NONE"
ordering="BEFORE"
side="BOTH"

[[dependencies.mcwfurnituresbop]]
modId="biomesoplenty"
mandatory=true
versionRange="NONE"
ordering="BEFORE"
side="BOTH"

[[dependencies.mcwfurnituresbop]]
modId="mcwfurnitures"
mandatory=true
versionRange="NONE"
ordering="BEFORE"
side="BOTH"