package fr.samlegamer.mcwfurnituresbop;

import org.apache.logging.log4j.LogManager;
import org.apache.logging.log4j.Logger;
import com.mcwfurnitures.kikoz.init.BlockEntityInit;
import fr.samlegamer.mcwfurnituresbop.block.MFurniBOPBlocksRegistry;
import net.neoforged.bus.api.IEventBus;
import net.neoforged.fml.common.Mod;
import net.neoforged.neoforge.event.BlockEntityTypeAddBlocksEvent;
import net.neoforged.neoforge.event.BuildCreativeModeTabContentsEvent;

@Mod(value = McwFurnituresBOP.MODID)
public class McwFurnituresBOP
{
	public static final String MODID = "mcwfurnituresbop";
	public static final Logger log = LogManager.getLogger();
	
	public McwFurnituresBOP(IEventBus bus)
	{
		log.info("Macaw's Furnitures - Biomes O' Plenty : Loading...");
		MFurniBOPBlocksRegistry.ITEMS_REGISTRY.register(bus);
		MFurniBOPBlocksRegistry.BLOCKS_REGISTRY.register(bus);
		MFurniBOPBlocksRegistry.Item_Group.register(bus);
		bus.addListener(this::AddTab);
		bus.addListener(this::addCompatibleBlocksToFurnitureStorage);
		log.info("Macaw's Furnitures - Biomes O' Plenty : Is Charged");
	}
	
	private void addCompatibleBlocksToFurnitureStorage(BlockEntityTypeAddBlocksEvent event)
	{
		event.modify(BlockEntityInit.FURNITURE_STORAGE.get(), MFurniBOPBlocksRegistry.dead_wardrobe.get(),
				MFurniBOPBlocksRegistry.dead_modern_wardrobe.get(),
				MFurniBOPBlocksRegistry.dead_double_wardrobe.get(),
				MFurniBOPBlocksRegistry.dead_bookshelf.get(),
				MFurniBOPBlocksRegistry.dead_bookshelf_cupboard.get(),
				MFurniBOPBlocksRegistry.dead_drawer.get(),
				MFurniBOPBlocksRegistry.dead_double_drawer.get(),
				MFurniBOPBlocksRegistry.dead_bookshelf_drawer.get(),
				MFurniBOPBlocksRegistry.dead_lower_bookshelf_drawer.get(),
				MFurniBOPBlocksRegistry.dead_large_drawer.get(),
				MFurniBOPBlocksRegistry.dead_lower_triple_drawer.get(),
				MFurniBOPBlocksRegistry.dead_triple_drawer.get(),
				MFurniBOPBlocksRegistry.dead_drawer_counter.get(),
				MFurniBOPBlocksRegistry.dead_double_drawer_counter.get(),
				MFurniBOPBlocksRegistry.dead_cupboard_counter.get(),
				MFurniBOPBlocksRegistry.stripped_dead_wardrobe.get(),
				MFurniBOPBlocksRegistry.stripped_dead_modern_wardrobe.get(),
				MFurniBOPBlocksRegistry.stripped_dead_double_wardrobe.get(),
				MFurniBOPBlocksRegistry.stripped_dead_bookshelf.get(),
				MFurniBOPBlocksRegistry.stripped_dead_bookshelf_cupboard.get(),
				MFurniBOPBlocksRegistry.stripped_dead_drawer.get(),
				MFurniBOPBlocksRegistry.stripped_dead_double_drawer.get(),
				MFurniBOPBlocksRegistry.stripped_dead_bookshelf_drawer.get(),
				MFurniBOPBlocksRegistry.stripped_dead_lower_bookshelf_drawer.get(),
				MFurniBOPBlocksRegistry.stripped_dead_large_drawer.get(),
				MFurniBOPBlocksRegistry.stripped_dead_lower_triple_drawer.get(),
				MFurniBOPBlocksRegistry.stripped_dead_triple_drawer.get(),
				MFurniBOPBlocksRegistry.stripped_dead_counter.get(),
				MFurniBOPBlocksRegistry.stripped_dead_drawer_counter.get(),
				MFurniBOPBlocksRegistry.stripped_dead_double_drawer_counter.get(),
				MFurniBOPBlocksRegistry.stripped_dead_cupboard_counter.get(),
				MFurniBOPBlocksRegistry.dead_kitchen_cabinet.get(),
				MFurniBOPBlocksRegistry.dead_double_kitchen_cabinet.get(),
				MFurniBOPBlocksRegistry.dead_glass_kitchen_cabinet.get(),
				MFurniBOPBlocksRegistry.stripped_dead_kitchen_cabinet.get(),
				MFurniBOPBlocksRegistry.stripped_dead_double_kitchen_cabinet.get(),
				MFurniBOPBlocksRegistry.stripped_dead_glass_kitchen_cabinet.get(),MFurniBOPBlocksRegistry.fir_wardrobe.get(),
				MFurniBOPBlocksRegistry.fir_modern_wardrobe.get(),
				MFurniBOPBlocksRegistry.fir_double_wardrobe.get(),
				MFurniBOPBlocksRegistry.fir_bookshelf.get(),
				MFurniBOPBlocksRegistry.fir_bookshelf_cupboard.get(),
				MFurniBOPBlocksRegistry.fir_drawer.get(),
				MFurniBOPBlocksRegistry.fir_double_drawer.get(),
				MFurniBOPBlocksRegistry.fir_bookshelf_drawer.get(),
				MFurniBOPBlocksRegistry.fir_lower_bookshelf_drawer.get(),
				MFurniBOPBlocksRegistry.fir_large_drawer.get(),
				MFurniBOPBlocksRegistry.fir_lower_triple_drawer.get(),
				MFurniBOPBlocksRegistry.fir_triple_drawer.get(),
				MFurniBOPBlocksRegistry.fir_drawer_counter.get(),
				MFurniBOPBlocksRegistry.fir_double_drawer_counter.get(),
				MFurniBOPBlocksRegistry.fir_cupboard_counter.get(),
				MFurniBOPBlocksRegistry.stripped_fir_wardrobe.get(),
				MFurniBOPBlocksRegistry.stripped_fir_modern_wardrobe.get(),
				MFurniBOPBlocksRegistry.stripped_fir_double_wardrobe.get(),
				MFurniBOPBlocksRegistry.stripped_fir_bookshelf.get(),
				MFurniBOPBlocksRegistry.stripped_fir_bookshelf_cupboard.get(),
				MFurniBOPBlocksRegistry.stripped_fir_drawer.get(),
				MFurniBOPBlocksRegistry.stripped_fir_double_drawer.get(),
				MFurniBOPBlocksRegistry.stripped_fir_bookshelf_drawer.get(),
				MFurniBOPBlocksRegistry.stripped_fir_lower_bookshelf_drawer.get(),
				MFurniBOPBlocksRegistry.stripped_fir_large_drawer.get(),
				MFurniBOPBlocksRegistry.stripped_fir_lower_triple_drawer.get(),
				MFurniBOPBlocksRegistry.stripped_fir_triple_drawer.get(),
				MFurniBOPBlocksRegistry.stripped_fir_counter.get(),
				MFurniBOPBlocksRegistry.stripped_fir_drawer_counter.get(),
				MFurniBOPBlocksRegistry.stripped_fir_double_drawer_counter.get(),
				MFurniBOPBlocksRegistry.stripped_fir_cupboard_counter.get(),
				MFurniBOPBlocksRegistry.fir_kitchen_cabinet.get(),
				MFurniBOPBlocksRegistry.fir_double_kitchen_cabinet.get(),
				MFurniBOPBlocksRegistry.fir_glass_kitchen_cabinet.get(),
				MFurniBOPBlocksRegistry.stripped_fir_kitchen_cabinet.get(),
				MFurniBOPBlocksRegistry.stripped_fir_double_kitchen_cabinet.get(),
				MFurniBOPBlocksRegistry.stripped_fir_glass_kitchen_cabinet.get(),MFurniBOPBlocksRegistry.hellbark_wardrobe.get(),
				MFurniBOPBlocksRegistry.hellbark_modern_wardrobe.get(),
				MFurniBOPBlocksRegistry.hellbark_double_wardrobe.get(),
				MFurniBOPBlocksRegistry.hellbark_bookshelf.get(),
				MFurniBOPBlocksRegistry.hellbark_bookshelf_cupboard.get(),
				MFurniBOPBlocksRegistry.hellbark_drawer.get(),
				MFurniBOPBlocksRegistry.hellbark_double_drawer.get(),
				MFurniBOPBlocksRegistry.hellbark_bookshelf_drawer.get(),
				MFurniBOPBlocksRegistry.hellbark_lower_bookshelf_drawer.get(),
				MFurniBOPBlocksRegistry.hellbark_large_drawer.get(),
				MFurniBOPBlocksRegistry.hellbark_lower_triple_drawer.get(),
				MFurniBOPBlocksRegistry.hellbark_triple_drawer.get(),
				MFurniBOPBlocksRegistry.hellbark_drawer_counter.get(),
				MFurniBOPBlocksRegistry.hellbark_double_drawer_counter.get(),
				MFurniBOPBlocksRegistry.hellbark_cupboard_counter.get(),
				MFurniBOPBlocksRegistry.stripped_hellbark_wardrobe.get(),
				MFurniBOPBlocksRegistry.stripped_hellbark_modern_wardrobe.get(),
				MFurniBOPBlocksRegistry.stripped_hellbark_double_wardrobe.get(),
				MFurniBOPBlocksRegistry.stripped_hellbark_bookshelf.get(),
				MFurniBOPBlocksRegistry.stripped_hellbark_bookshelf_cupboard.get(),
				MFurniBOPBlocksRegistry.stripped_hellbark_drawer.get(),
				MFurniBOPBlocksRegistry.stripped_hellbark_double_drawer.get(),
				MFurniBOPBlocksRegistry.stripped_hellbark_bookshelf_drawer.get(),
				MFurniBOPBlocksRegistry.stripped_hellbark_lower_bookshelf_drawer.get(),
				MFurniBOPBlocksRegistry.stripped_hellbark_large_drawer.get(),
				MFurniBOPBlocksRegistry.stripped_hellbark_lower_triple_drawer.get(),
				MFurniBOPBlocksRegistry.stripped_hellbark_triple_drawer.get(),
				MFurniBOPBlocksRegistry.stripped_hellbark_counter.get(),
				MFurniBOPBlocksRegistry.stripped_hellbark_drawer_counter.get(),
				MFurniBOPBlocksRegistry.stripped_hellbark_double_drawer_counter.get(),
				MFurniBOPBlocksRegistry.stripped_hellbark_cupboard_counter.get(),
				MFurniBOPBlocksRegistry.hellbark_kitchen_cabinet.get(),
				MFurniBOPBlocksRegistry.hellbark_double_kitchen_cabinet.get(),
				MFurniBOPBlocksRegistry.hellbark_glass_kitchen_cabinet.get(),
				MFurniBOPBlocksRegistry.stripped_hellbark_kitchen_cabinet.get(),
				MFurniBOPBlocksRegistry.stripped_hellbark_double_kitchen_cabinet.get(),
				MFurniBOPBlocksRegistry.stripped_hellbark_glass_kitchen_cabinet.get(),MFurniBOPBlocksRegistry.jacaranda_wardrobe.get(),
				MFurniBOPBlocksRegistry.jacaranda_modern_wardrobe.get(),
				MFurniBOPBlocksRegistry.jacaranda_double_wardrobe.get(),
				MFurniBOPBlocksRegistry.jacaranda_bookshelf.get(),
				MFurniBOPBlocksRegistry.jacaranda_bookshelf_cupboard.get(),
				MFurniBOPBlocksRegistry.jacaranda_drawer.get(),
				MFurniBOPBlocksRegistry.jacaranda_double_drawer.get(),
				MFurniBOPBlocksRegistry.jacaranda_bookshelf_drawer.get(),
				MFurniBOPBlocksRegistry.jacaranda_lower_bookshelf_drawer.get(),
				MFurniBOPBlocksRegistry.jacaranda_large_drawer.get(),
				MFurniBOPBlocksRegistry.jacaranda_lower_triple_drawer.get(),
				MFurniBOPBlocksRegistry.jacaranda_triple_drawer.get(),
				MFurniBOPBlocksRegistry.jacaranda_drawer_counter.get(),
				MFurniBOPBlocksRegistry.jacaranda_double_drawer_counter.get(),
				MFurniBOPBlocksRegistry.jacaranda_cupboard_counter.get(),
				MFurniBOPBlocksRegistry.stripped_jacaranda_wardrobe.get(),
				MFurniBOPBlocksRegistry.stripped_jacaranda_modern_wardrobe.get(),
				MFurniBOPBlocksRegistry.stripped_jacaranda_double_wardrobe.get(),
				MFurniBOPBlocksRegistry.stripped_jacaranda_bookshelf.get(),
				MFurniBOPBlocksRegistry.stripped_jacaranda_bookshelf_cupboard.get(),
				MFurniBOPBlocksRegistry.stripped_jacaranda_drawer.get(),
				MFurniBOPBlocksRegistry.stripped_jacaranda_double_drawer.get(),
				MFurniBOPBlocksRegistry.stripped_jacaranda_bookshelf_drawer.get(),
				MFurniBOPBlocksRegistry.stripped_jacaranda_lower_bookshelf_drawer.get(),
				MFurniBOPBlocksRegistry.stripped_jacaranda_large_drawer.get(),
				MFurniBOPBlocksRegistry.stripped_jacaranda_lower_triple_drawer.get(),
				MFurniBOPBlocksRegistry.stripped_jacaranda_triple_drawer.get(),
				MFurniBOPBlocksRegistry.stripped_jacaranda_counter.get(),
				MFurniBOPBlocksRegistry.stripped_jacaranda_drawer_counter.get(),
				MFurniBOPBlocksRegistry.stripped_jacaranda_double_drawer_counter.get(),
				MFurniBOPBlocksRegistry.stripped_jacaranda_cupboard_counter.get(),
				MFurniBOPBlocksRegistry.jacaranda_kitchen_cabinet.get(),
				MFurniBOPBlocksRegistry.jacaranda_double_kitchen_cabinet.get(),
				MFurniBOPBlocksRegistry.jacaranda_glass_kitchen_cabinet.get(),
				MFurniBOPBlocksRegistry.stripped_jacaranda_kitchen_cabinet.get(),
				MFurniBOPBlocksRegistry.stripped_jacaranda_double_kitchen_cabinet.get(),
				MFurniBOPBlocksRegistry.stripped_jacaranda_glass_kitchen_cabinet.get(),MFurniBOPBlocksRegistry.magic_wardrobe.get(),
				MFurniBOPBlocksRegistry.magic_modern_wardrobe.get(),
				MFurniBOPBlocksRegistry.magic_double_wardrobe.get(),
				MFurniBOPBlocksRegistry.magic_bookshelf.get(),
				MFurniBOPBlocksRegistry.magic_bookshelf_cupboard.get(),
				MFurniBOPBlocksRegistry.magic_drawer.get(),
				MFurniBOPBlocksRegistry.magic_double_drawer.get(),
				MFurniBOPBlocksRegistry.magic_bookshelf_drawer.get(),
				MFurniBOPBlocksRegistry.magic_lower_bookshelf_drawer.get(),
				MFurniBOPBlocksRegistry.magic_large_drawer.get(),
				MFurniBOPBlocksRegistry.magic_lower_triple_drawer.get(),
				MFurniBOPBlocksRegistry.magic_triple_drawer.get(),
				MFurniBOPBlocksRegistry.magic_drawer_counter.get(),
				MFurniBOPBlocksRegistry.magic_double_drawer_counter.get(),
				MFurniBOPBlocksRegistry.magic_cupboard_counter.get(),
				MFurniBOPBlocksRegistry.stripped_magic_wardrobe.get(),
				MFurniBOPBlocksRegistry.stripped_magic_modern_wardrobe.get(),
				MFurniBOPBlocksRegistry.stripped_magic_double_wardrobe.get(),
				MFurniBOPBlocksRegistry.stripped_magic_bookshelf.get(),
				MFurniBOPBlocksRegistry.stripped_magic_bookshelf_cupboard.get(),
				MFurniBOPBlocksRegistry.stripped_magic_drawer.get(),
				MFurniBOPBlocksRegistry.stripped_magic_double_drawer.get(),
				MFurniBOPBlocksRegistry.stripped_magic_bookshelf_drawer.get(),
				MFurniBOPBlocksRegistry.stripped_magic_lower_bookshelf_drawer.get(),
				MFurniBOPBlocksRegistry.stripped_magic_large_drawer.get(),
				MFurniBOPBlocksRegistry.stripped_magic_lower_triple_drawer.get(),
				MFurniBOPBlocksRegistry.stripped_magic_triple_drawer.get(),
				MFurniBOPBlocksRegistry.stripped_magic_counter.get(),
				MFurniBOPBlocksRegistry.stripped_magic_drawer_counter.get(),
				MFurniBOPBlocksRegistry.stripped_magic_double_drawer_counter.get(),
				MFurniBOPBlocksRegistry.stripped_magic_cupboard_counter.get(),
				MFurniBOPBlocksRegistry.magic_kitchen_cabinet.get(),
				MFurniBOPBlocksRegistry.magic_double_kitchen_cabinet.get(),
				MFurniBOPBlocksRegistry.magic_glass_kitchen_cabinet.get(),
				MFurniBOPBlocksRegistry.stripped_magic_kitchen_cabinet.get(),
				MFurniBOPBlocksRegistry.stripped_magic_double_kitchen_cabinet.get(),
				MFurniBOPBlocksRegistry.stripped_magic_glass_kitchen_cabinet.get(),MFurniBOPBlocksRegistry.mahogany_wardrobe.get(),
				MFurniBOPBlocksRegistry.mahogany_modern_wardrobe.get(),
				MFurniBOPBlocksRegistry.mahogany_double_wardrobe.get(),
				MFurniBOPBlocksRegistry.mahogany_bookshelf.get(),
				MFurniBOPBlocksRegistry.mahogany_bookshelf_cupboard.get(),
				MFurniBOPBlocksRegistry.mahogany_drawer.get(),
				MFurniBOPBlocksRegistry.mahogany_double_drawer.get(),
				MFurniBOPBlocksRegistry.mahogany_bookshelf_drawer.get(),
				MFurniBOPBlocksRegistry.mahogany_lower_bookshelf_drawer.get(),
				MFurniBOPBlocksRegistry.mahogany_large_drawer.get(),
				MFurniBOPBlocksRegistry.mahogany_lower_triple_drawer.get(),
				MFurniBOPBlocksRegistry.mahogany_triple_drawer.get(),
				MFurniBOPBlocksRegistry.mahogany_drawer_counter.get(),
				MFurniBOPBlocksRegistry.mahogany_double_drawer_counter.get(),
				MFurniBOPBlocksRegistry.mahogany_cupboard_counter.get(),
				MFurniBOPBlocksRegistry.stripped_mahogany_wardrobe.get(),
				MFurniBOPBlocksRegistry.stripped_mahogany_modern_wardrobe.get(),
				MFurniBOPBlocksRegistry.stripped_mahogany_double_wardrobe.get(),
				MFurniBOPBlocksRegistry.stripped_mahogany_bookshelf.get(),
				MFurniBOPBlocksRegistry.stripped_mahogany_bookshelf_cupboard.get(),
				MFurniBOPBlocksRegistry.stripped_mahogany_drawer.get(),
				MFurniBOPBlocksRegistry.stripped_mahogany_double_drawer.get(),
				MFurniBOPBlocksRegistry.stripped_mahogany_bookshelf_drawer.get(),
				MFurniBOPBlocksRegistry.stripped_mahogany_lower_bookshelf_drawer.get(),
				MFurniBOPBlocksRegistry.stripped_mahogany_large_drawer.get(),
				MFurniBOPBlocksRegistry.stripped_mahogany_lower_triple_drawer.get(),
				MFurniBOPBlocksRegistry.stripped_mahogany_triple_drawer.get(),
				MFurniBOPBlocksRegistry.stripped_mahogany_counter.get(),
				MFurniBOPBlocksRegistry.stripped_mahogany_drawer_counter.get(),
				MFurniBOPBlocksRegistry.stripped_mahogany_double_drawer_counter.get(),
				MFurniBOPBlocksRegistry.stripped_mahogany_cupboard_counter.get(),
				MFurniBOPBlocksRegistry.mahogany_kitchen_cabinet.get(),
				MFurniBOPBlocksRegistry.mahogany_double_kitchen_cabinet.get(),
				MFurniBOPBlocksRegistry.mahogany_glass_kitchen_cabinet.get(),
				MFurniBOPBlocksRegistry.stripped_mahogany_kitchen_cabinet.get(),
				MFurniBOPBlocksRegistry.stripped_mahogany_double_kitchen_cabinet.get(),
				MFurniBOPBlocksRegistry.stripped_mahogany_glass_kitchen_cabinet.get(),MFurniBOPBlocksRegistry.palm_wardrobe.get(),
				MFurniBOPBlocksRegistry.palm_modern_wardrobe.get(),
				MFurniBOPBlocksRegistry.palm_double_wardrobe.get(),
				MFurniBOPBlocksRegistry.palm_bookshelf.get(),
				MFurniBOPBlocksRegistry.palm_bookshelf_cupboard.get(),
				MFurniBOPBlocksRegistry.palm_drawer.get(),
				MFurniBOPBlocksRegistry.palm_double_drawer.get(),
				MFurniBOPBlocksRegistry.palm_bookshelf_drawer.get(),
				MFurniBOPBlocksRegistry.palm_lower_bookshelf_drawer.get(),
				MFurniBOPBlocksRegistry.palm_large_drawer.get(),
				MFurniBOPBlocksRegistry.palm_lower_triple_drawer.get(),
				MFurniBOPBlocksRegistry.palm_triple_drawer.get(),
				MFurniBOPBlocksRegistry.palm_drawer_counter.get(),
				MFurniBOPBlocksRegistry.palm_double_drawer_counter.get(),
				MFurniBOPBlocksRegistry.palm_cupboard_counter.get(),
				MFurniBOPBlocksRegistry.stripped_palm_wardrobe.get(),
				MFurniBOPBlocksRegistry.stripped_palm_modern_wardrobe.get(),
				MFurniBOPBlocksRegistry.stripped_palm_double_wardrobe.get(),
				MFurniBOPBlocksRegistry.stripped_palm_bookshelf.get(),
				MFurniBOPBlocksRegistry.stripped_palm_bookshelf_cupboard.get(),
				MFurniBOPBlocksRegistry.stripped_palm_drawer.get(),
				MFurniBOPBlocksRegistry.stripped_palm_double_drawer.get(),
				MFurniBOPBlocksRegistry.stripped_palm_bookshelf_drawer.get(),
				MFurniBOPBlocksRegistry.stripped_palm_lower_bookshelf_drawer.get(),
				MFurniBOPBlocksRegistry.stripped_palm_large_drawer.get(),
				MFurniBOPBlocksRegistry.stripped_palm_lower_triple_drawer.get(),
				MFurniBOPBlocksRegistry.stripped_palm_triple_drawer.get(),
				MFurniBOPBlocksRegistry.stripped_palm_counter.get(),
				MFurniBOPBlocksRegistry.stripped_palm_drawer_counter.get(),
				MFurniBOPBlocksRegistry.stripped_palm_double_drawer_counter.get(),
				MFurniBOPBlocksRegistry.stripped_palm_cupboard_counter.get(),
				MFurniBOPBlocksRegistry.palm_kitchen_cabinet.get(),
				MFurniBOPBlocksRegistry.palm_double_kitchen_cabinet.get(),
				MFurniBOPBlocksRegistry.palm_glass_kitchen_cabinet.get(),
				MFurniBOPBlocksRegistry.stripped_palm_kitchen_cabinet.get(),
				MFurniBOPBlocksRegistry.stripped_palm_double_kitchen_cabinet.get(),
				MFurniBOPBlocksRegistry.stripped_palm_glass_kitchen_cabinet.get(),MFurniBOPBlocksRegistry.redwood_wardrobe.get(),
				MFurniBOPBlocksRegistry.redwood_modern_wardrobe.get(),
				MFurniBOPBlocksRegistry.redwood_double_wardrobe.get(),
				MFurniBOPBlocksRegistry.redwood_bookshelf.get(),
				MFurniBOPBlocksRegistry.redwood_bookshelf_cupboard.get(),
				MFurniBOPBlocksRegistry.redwood_drawer.get(),
				MFurniBOPBlocksRegistry.redwood_double_drawer.get(),
				MFurniBOPBlocksRegistry.redwood_bookshelf_drawer.get(),
				MFurniBOPBlocksRegistry.redwood_lower_bookshelf_drawer.get(),
				MFurniBOPBlocksRegistry.redwood_large_drawer.get(),
				MFurniBOPBlocksRegistry.redwood_lower_triple_drawer.get(),
				MFurniBOPBlocksRegistry.redwood_triple_drawer.get(),
				MFurniBOPBlocksRegistry.redwood_drawer_counter.get(),
				MFurniBOPBlocksRegistry.redwood_double_drawer_counter.get(),
				MFurniBOPBlocksRegistry.redwood_cupboard_counter.get(),
				MFurniBOPBlocksRegistry.stripped_redwood_wardrobe.get(),
				MFurniBOPBlocksRegistry.stripped_redwood_modern_wardrobe.get(),
				MFurniBOPBlocksRegistry.stripped_redwood_double_wardrobe.get(),
				MFurniBOPBlocksRegistry.stripped_redwood_bookshelf.get(),
				MFurniBOPBlocksRegistry.stripped_redwood_bookshelf_cupboard.get(),
				MFurniBOPBlocksRegistry.stripped_redwood_drawer.get(),
				MFurniBOPBlocksRegistry.stripped_redwood_double_drawer.get(),
				MFurniBOPBlocksRegistry.stripped_redwood_bookshelf_drawer.get(),
				MFurniBOPBlocksRegistry.stripped_redwood_lower_bookshelf_drawer.get(),
				MFurniBOPBlocksRegistry.stripped_redwood_large_drawer.get(),
				MFurniBOPBlocksRegistry.stripped_redwood_lower_triple_drawer.get(),
				MFurniBOPBlocksRegistry.stripped_redwood_triple_drawer.get(),
				MFurniBOPBlocksRegistry.stripped_redwood_counter.get(),
				MFurniBOPBlocksRegistry.stripped_redwood_drawer_counter.get(),
				MFurniBOPBlocksRegistry.stripped_redwood_double_drawer_counter.get(),
				MFurniBOPBlocksRegistry.stripped_redwood_cupboard_counter.get(),
				MFurniBOPBlocksRegistry.redwood_kitchen_cabinet.get(),
				MFurniBOPBlocksRegistry.redwood_double_kitchen_cabinet.get(),
				MFurniBOPBlocksRegistry.redwood_glass_kitchen_cabinet.get(),
				MFurniBOPBlocksRegistry.stripped_redwood_kitchen_cabinet.get(),
				MFurniBOPBlocksRegistry.stripped_redwood_double_kitchen_cabinet.get(),
				MFurniBOPBlocksRegistry.stripped_redwood_glass_kitchen_cabinet.get(),MFurniBOPBlocksRegistry.umbran_wardrobe.get(),
				MFurniBOPBlocksRegistry.umbran_modern_wardrobe.get(),
				MFurniBOPBlocksRegistry.umbran_double_wardrobe.get(),
				MFurniBOPBlocksRegistry.umbran_bookshelf.get(),
				MFurniBOPBlocksRegistry.umbran_bookshelf_cupboard.get(),
				MFurniBOPBlocksRegistry.umbran_drawer.get(),
				MFurniBOPBlocksRegistry.umbran_double_drawer.get(),
				MFurniBOPBlocksRegistry.umbran_bookshelf_drawer.get(),
				MFurniBOPBlocksRegistry.umbran_lower_bookshelf_drawer.get(),
				MFurniBOPBlocksRegistry.umbran_large_drawer.get(),
				MFurniBOPBlocksRegistry.umbran_lower_triple_drawer.get(),
				MFurniBOPBlocksRegistry.umbran_triple_drawer.get(),
				MFurniBOPBlocksRegistry.umbran_drawer_counter.get(),
				MFurniBOPBlocksRegistry.umbran_double_drawer_counter.get(),
				MFurniBOPBlocksRegistry.umbran_cupboard_counter.get(),
				MFurniBOPBlocksRegistry.stripped_umbran_wardrobe.get(),
				MFurniBOPBlocksRegistry.stripped_umbran_modern_wardrobe.get(),
				MFurniBOPBlocksRegistry.stripped_umbran_double_wardrobe.get(),
				MFurniBOPBlocksRegistry.stripped_umbran_bookshelf.get(),
				MFurniBOPBlocksRegistry.stripped_umbran_bookshelf_cupboard.get(),
				MFurniBOPBlocksRegistry.stripped_umbran_drawer.get(),
				MFurniBOPBlocksRegistry.stripped_umbran_double_drawer.get(),
				MFurniBOPBlocksRegistry.stripped_umbran_bookshelf_drawer.get(),
				MFurniBOPBlocksRegistry.stripped_umbran_lower_bookshelf_drawer.get(),
				MFurniBOPBlocksRegistry.stripped_umbran_large_drawer.get(),
				MFurniBOPBlocksRegistry.stripped_umbran_lower_triple_drawer.get(),
				MFurniBOPBlocksRegistry.stripped_umbran_triple_drawer.get(),
				MFurniBOPBlocksRegistry.stripped_umbran_counter.get(),
				MFurniBOPBlocksRegistry.stripped_umbran_drawer_counter.get(),
				MFurniBOPBlocksRegistry.stripped_umbran_double_drawer_counter.get(),
				MFurniBOPBlocksRegistry.stripped_umbran_cupboard_counter.get(),
				MFurniBOPBlocksRegistry.umbran_kitchen_cabinet.get(),
				MFurniBOPBlocksRegistry.umbran_double_kitchen_cabinet.get(),
				MFurniBOPBlocksRegistry.umbran_glass_kitchen_cabinet.get(),
				MFurniBOPBlocksRegistry.stripped_umbran_kitchen_cabinet.get(),
				MFurniBOPBlocksRegistry.stripped_umbran_double_kitchen_cabinet.get(),
				MFurniBOPBlocksRegistry.stripped_umbran_glass_kitchen_cabinet.get(),MFurniBOPBlocksRegistry.willow_wardrobe.get(),
				MFurniBOPBlocksRegistry.willow_modern_wardrobe.get(),
				MFurniBOPBlocksRegistry.willow_double_wardrobe.get(),
				MFurniBOPBlocksRegistry.willow_bookshelf.get(),
				MFurniBOPBlocksRegistry.willow_bookshelf_cupboard.get(),
				MFurniBOPBlocksRegistry.willow_drawer.get(),
				MFurniBOPBlocksRegistry.willow_double_drawer.get(),
				MFurniBOPBlocksRegistry.willow_bookshelf_drawer.get(),
				MFurniBOPBlocksRegistry.willow_lower_bookshelf_drawer.get(),
				MFurniBOPBlocksRegistry.willow_large_drawer.get(),
				MFurniBOPBlocksRegistry.willow_lower_triple_drawer.get(),
				MFurniBOPBlocksRegistry.willow_triple_drawer.get(),
				MFurniBOPBlocksRegistry.willow_drawer_counter.get(),
				MFurniBOPBlocksRegistry.willow_double_drawer_counter.get(),
				MFurniBOPBlocksRegistry.willow_cupboard_counter.get(),
				MFurniBOPBlocksRegistry.stripped_willow_wardrobe.get(),
				MFurniBOPBlocksRegistry.stripped_willow_modern_wardrobe.get(),
				MFurniBOPBlocksRegistry.stripped_willow_double_wardrobe.get(),
				MFurniBOPBlocksRegistry.stripped_willow_bookshelf.get(),
				MFurniBOPBlocksRegistry.stripped_willow_bookshelf_cupboard.get(),
				MFurniBOPBlocksRegistry.stripped_willow_drawer.get(),
				MFurniBOPBlocksRegistry.stripped_willow_double_drawer.get(),
				MFurniBOPBlocksRegistry.stripped_willow_bookshelf_drawer.get(),
				MFurniBOPBlocksRegistry.stripped_willow_lower_bookshelf_drawer.get(),
				MFurniBOPBlocksRegistry.stripped_willow_large_drawer.get(),
				MFurniBOPBlocksRegistry.stripped_willow_lower_triple_drawer.get(),
				MFurniBOPBlocksRegistry.stripped_willow_triple_drawer.get(),
				MFurniBOPBlocksRegistry.stripped_willow_counter.get(),
				MFurniBOPBlocksRegistry.stripped_willow_drawer_counter.get(),
				MFurniBOPBlocksRegistry.stripped_willow_double_drawer_counter.get(),
				MFurniBOPBlocksRegistry.stripped_willow_cupboard_counter.get(),
				MFurniBOPBlocksRegistry.willow_kitchen_cabinet.get(),
				MFurniBOPBlocksRegistry.willow_double_kitchen_cabinet.get(),
				MFurniBOPBlocksRegistry.willow_glass_kitchen_cabinet.get(),
				MFurniBOPBlocksRegistry.stripped_willow_kitchen_cabinet.get(),
				MFurniBOPBlocksRegistry.stripped_willow_double_kitchen_cabinet.get(),
				MFurniBOPBlocksRegistry.stripped_willow_glass_kitchen_cabinet.get(),MFurniBOPBlocksRegistry.empyreal_wardrobe.get(),
				MFurniBOPBlocksRegistry.empyreal_modern_wardrobe.get(),
				MFurniBOPBlocksRegistry.empyreal_double_wardrobe.get(),
				MFurniBOPBlocksRegistry.empyreal_bookshelf.get(),
				MFurniBOPBlocksRegistry.empyreal_bookshelf_cupboard.get(),
				MFurniBOPBlocksRegistry.empyreal_drawer.get(),
				MFurniBOPBlocksRegistry.empyreal_double_drawer.get(),
				MFurniBOPBlocksRegistry.empyreal_bookshelf_drawer.get(),
				MFurniBOPBlocksRegistry.empyreal_lower_bookshelf_drawer.get(),
				MFurniBOPBlocksRegistry.empyreal_large_drawer.get(),
				MFurniBOPBlocksRegistry.empyreal_lower_triple_drawer.get(),
				MFurniBOPBlocksRegistry.empyreal_triple_drawer.get(),
				MFurniBOPBlocksRegistry.empyreal_drawer_counter.get(),
				MFurniBOPBlocksRegistry.empyreal_double_drawer_counter.get(),
				MFurniBOPBlocksRegistry.empyreal_cupboard_counter.get(),
				MFurniBOPBlocksRegistry.stripped_empyreal_wardrobe.get(),
				MFurniBOPBlocksRegistry.stripped_empyreal_modern_wardrobe.get(),
				MFurniBOPBlocksRegistry.stripped_empyreal_double_wardrobe.get(),
				MFurniBOPBlocksRegistry.stripped_empyreal_bookshelf.get(),
				MFurniBOPBlocksRegistry.stripped_empyreal_bookshelf_cupboard.get(),
				MFurniBOPBlocksRegistry.stripped_empyreal_drawer.get(),
				MFurniBOPBlocksRegistry.stripped_empyreal_double_drawer.get(),
				MFurniBOPBlocksRegistry.stripped_empyreal_bookshelf_drawer.get(),
				MFurniBOPBlocksRegistry.stripped_empyreal_lower_bookshelf_drawer.get(),
				MFurniBOPBlocksRegistry.stripped_empyreal_large_drawer.get(),
				MFurniBOPBlocksRegistry.stripped_empyreal_lower_triple_drawer.get(),
				MFurniBOPBlocksRegistry.stripped_empyreal_triple_drawer.get(),
				MFurniBOPBlocksRegistry.stripped_empyreal_counter.get(),
				MFurniBOPBlocksRegistry.stripped_empyreal_drawer_counter.get(),
				MFurniBOPBlocksRegistry.stripped_empyreal_double_drawer_counter.get(),
				MFurniBOPBlocksRegistry.stripped_empyreal_cupboard_counter.get(),
				MFurniBOPBlocksRegistry.empyreal_kitchen_cabinet.get(),
				MFurniBOPBlocksRegistry.empyreal_double_kitchen_cabinet.get(),
				MFurniBOPBlocksRegistry.empyreal_glass_kitchen_cabinet.get(),
				MFurniBOPBlocksRegistry.stripped_empyreal_kitchen_cabinet.get(),
				MFurniBOPBlocksRegistry.stripped_empyreal_double_kitchen_cabinet.get(),
				MFurniBOPBlocksRegistry.stripped_empyreal_glass_kitchen_cabinet.get());
	}
			    
    private void AddTab(BuildCreativeModeTabContentsEvent event)
    {
    	 if (event.getTab() == MFurniBOPBlocksRegistry.MFURNI_CT.get())
    	 {
    		 event.accept(MFurniBOPBlocksRegistry.dead_wardrobe.get());
    		 event.accept(MFurniBOPBlocksRegistry.dead_modern_wardrobe.get());
    		 event.accept(MFurniBOPBlocksRegistry.dead_double_wardrobe.get());
    		 event.accept(MFurniBOPBlocksRegistry.dead_bookshelf.get());
    		 event.accept(MFurniBOPBlocksRegistry.dead_bookshelf_cupboard.get());
    		 event.accept(MFurniBOPBlocksRegistry.dead_drawer.get());
    		 event.accept(MFurniBOPBlocksRegistry.dead_double_drawer.get());
    		 event.accept(MFurniBOPBlocksRegistry.dead_bookshelf_drawer.get());
    		 event.accept(MFurniBOPBlocksRegistry.dead_lower_bookshelf_drawer.get());
    		 event.accept(MFurniBOPBlocksRegistry.dead_large_drawer.get());
    		 event.accept(MFurniBOPBlocksRegistry.dead_lower_triple_drawer.get());
    		 event.accept(MFurniBOPBlocksRegistry.dead_triple_drawer.get());
    		 event.accept(MFurniBOPBlocksRegistry.dead_covered_desk.get());
    		 event.accept(MFurniBOPBlocksRegistry.dead_modern_desk.get());
    		 event.accept(MFurniBOPBlocksRegistry.dead_table.get());
    		 event.accept(MFurniBOPBlocksRegistry.dead_end_table.get());
    		 event.accept(MFurniBOPBlocksRegistry.dead_coffee_table.get());
    		 event.accept(MFurniBOPBlocksRegistry.dead_glass_table.get());
    		 event.accept(MFurniBOPBlocksRegistry.dead_chair.get());
    		 event.accept(MFurniBOPBlocksRegistry.dead_modern_chair.get());
    		 event.accept(MFurniBOPBlocksRegistry.dead_striped_chair.get());
    		 event.accept(MFurniBOPBlocksRegistry.dead_stool_chair.get());
    		 event.accept(MFurniBOPBlocksRegistry.dead_counter.get());
    		 event.accept(MFurniBOPBlocksRegistry.dead_drawer_counter.get());
    		 event.accept(MFurniBOPBlocksRegistry.dead_double_drawer_counter.get());
    		 event.accept(MFurniBOPBlocksRegistry.dead_cupboard_counter.get());
    		 event.accept(MFurniBOPBlocksRegistry.stripped_dead_wardrobe.get());
    		 event.accept(MFurniBOPBlocksRegistry.stripped_dead_modern_wardrobe.get());
    		 event.accept(MFurniBOPBlocksRegistry.stripped_dead_double_wardrobe.get());
    		 event.accept(MFurniBOPBlocksRegistry.stripped_dead_bookshelf.get());
    		 event.accept(MFurniBOPBlocksRegistry.stripped_dead_bookshelf_cupboard.get());
    		 event.accept(MFurniBOPBlocksRegistry.stripped_dead_drawer.get());
    		 event.accept(MFurniBOPBlocksRegistry.stripped_dead_double_drawer.get());
    		 event.accept(MFurniBOPBlocksRegistry.stripped_dead_bookshelf_drawer.get());
    		 event.accept(MFurniBOPBlocksRegistry.stripped_dead_lower_bookshelf_drawer.get());
    		 event.accept(MFurniBOPBlocksRegistry.stripped_dead_large_drawer.get());
    		 event.accept(MFurniBOPBlocksRegistry.stripped_dead_lower_triple_drawer.get());
    		 event.accept(MFurniBOPBlocksRegistry.stripped_dead_triple_drawer.get());
    		 event.accept(MFurniBOPBlocksRegistry.stripped_dead_desk.get());
    		 event.accept(MFurniBOPBlocksRegistry.stripped_dead_covered_desk.get());
    		 event.accept(MFurniBOPBlocksRegistry.stripped_dead_modern_desk.get());
    		 event.accept(MFurniBOPBlocksRegistry.stripped_dead_table.get());
    		 event.accept(MFurniBOPBlocksRegistry.stripped_dead_end_table.get());
    		 event.accept(MFurniBOPBlocksRegistry.stripped_dead_coffee_table.get());
    		 event.accept(MFurniBOPBlocksRegistry.stripped_dead_glass_table.get());
    		 event.accept(MFurniBOPBlocksRegistry.stripped_dead_modern_chair.get());
    		 event.accept(MFurniBOPBlocksRegistry.stripped_dead_striped_chair.get());
    		 event.accept(MFurniBOPBlocksRegistry.stripped_dead_stool_chair.get());
    		 event.accept(MFurniBOPBlocksRegistry.stripped_dead_counter.get());
    		 event.accept(MFurniBOPBlocksRegistry.stripped_dead_drawer_counter.get());
    		 event.accept(MFurniBOPBlocksRegistry.stripped_dead_double_drawer_counter.get());
    		 event.accept(MFurniBOPBlocksRegistry.stripped_dead_cupboard_counter.get());
    		 event.accept(MFurniBOPBlocksRegistry.dead_kitchen_cabinet.get());
    		 event.accept(MFurniBOPBlocksRegistry.dead_double_kitchen_cabinet.get());
    		 event.accept(MFurniBOPBlocksRegistry.dead_glass_kitchen_cabinet.get());
    		 event.accept(MFurniBOPBlocksRegistry.stripped_dead_kitchen_cabinet.get());
    		 event.accept(MFurniBOPBlocksRegistry.stripped_dead_double_kitchen_cabinet.get());
    		 event.accept(MFurniBOPBlocksRegistry.stripped_dead_glass_kitchen_cabinet.get());
    		 event.accept(MFurniBOPBlocksRegistry.fir_wardrobe.get());
    		 event.accept(MFurniBOPBlocksRegistry.fir_modern_wardrobe.get());
    		 event.accept(MFurniBOPBlocksRegistry.fir_double_wardrobe.get());
    		 event.accept(MFurniBOPBlocksRegistry.fir_bookshelf.get());
    		 event.accept(MFurniBOPBlocksRegistry.fir_bookshelf_cupboard.get());
    		 event.accept(MFurniBOPBlocksRegistry.fir_drawer.get());
    		 event.accept(MFurniBOPBlocksRegistry.fir_double_drawer.get());
    		 event.accept(MFurniBOPBlocksRegistry.fir_bookshelf_drawer.get());
    		 event.accept(MFurniBOPBlocksRegistry.fir_lower_bookshelf_drawer.get());
    		 event.accept(MFurniBOPBlocksRegistry.fir_large_drawer.get());
    		 event.accept(MFurniBOPBlocksRegistry.fir_lower_triple_drawer.get());
    		 event.accept(MFurniBOPBlocksRegistry.fir_triple_drawer.get());
    		 event.accept(MFurniBOPBlocksRegistry.fir_covered_desk.get());
    		 event.accept(MFurniBOPBlocksRegistry.fir_modern_desk.get());
    		 event.accept(MFurniBOPBlocksRegistry.fir_table.get());
    		 event.accept(MFurniBOPBlocksRegistry.fir_end_table.get());
    		 event.accept(MFurniBOPBlocksRegistry.fir_coffee_table.get());
    		 event.accept(MFurniBOPBlocksRegistry.fir_glass_table.get());
    		 event.accept(MFurniBOPBlocksRegistry.fir_chair.get());
    		 event.accept(MFurniBOPBlocksRegistry.fir_modern_chair.get());
    		 event.accept(MFurniBOPBlocksRegistry.fir_striped_chair.get());
    		 event.accept(MFurniBOPBlocksRegistry.fir_stool_chair.get());
    		 event.accept(MFurniBOPBlocksRegistry.fir_counter.get());
    		 event.accept(MFurniBOPBlocksRegistry.fir_drawer_counter.get());
    		 event.accept(MFurniBOPBlocksRegistry.fir_double_drawer_counter.get());
    		 event.accept(MFurniBOPBlocksRegistry.fir_cupboard_counter.get());
    		 event.accept(MFurniBOPBlocksRegistry.stripped_fir_wardrobe.get());
    		 event.accept(MFurniBOPBlocksRegistry.stripped_fir_modern_wardrobe.get());
    		 event.accept(MFurniBOPBlocksRegistry.stripped_fir_double_wardrobe.get());
    		 event.accept(MFurniBOPBlocksRegistry.stripped_fir_bookshelf.get());
    		 event.accept(MFurniBOPBlocksRegistry.stripped_fir_bookshelf_cupboard.get());
    		 event.accept(MFurniBOPBlocksRegistry.stripped_fir_drawer.get());
    		 event.accept(MFurniBOPBlocksRegistry.stripped_fir_double_drawer.get());
    		 event.accept(MFurniBOPBlocksRegistry.stripped_fir_bookshelf_drawer.get());
    		 event.accept(MFurniBOPBlocksRegistry.stripped_fir_lower_bookshelf_drawer.get());
    		 event.accept(MFurniBOPBlocksRegistry.stripped_fir_large_drawer.get());
    		 event.accept(MFurniBOPBlocksRegistry.stripped_fir_lower_triple_drawer.get());
    		 event.accept(MFurniBOPBlocksRegistry.stripped_fir_triple_drawer.get());
    		 event.accept(MFurniBOPBlocksRegistry.stripped_fir_desk.get());
    		 event.accept(MFurniBOPBlocksRegistry.stripped_fir_covered_desk.get());
    		 event.accept(MFurniBOPBlocksRegistry.stripped_fir_modern_desk.get());
    		 event.accept(MFurniBOPBlocksRegistry.stripped_fir_table.get());
    		 event.accept(MFurniBOPBlocksRegistry.stripped_fir_end_table.get());
    		 event.accept(MFurniBOPBlocksRegistry.stripped_fir_coffee_table.get());
    		 event.accept(MFurniBOPBlocksRegistry.stripped_fir_glass_table.get());
    		 event.accept(MFurniBOPBlocksRegistry.stripped_fir_modern_chair.get());
    		 event.accept(MFurniBOPBlocksRegistry.stripped_fir_striped_chair.get());
    		 event.accept(MFurniBOPBlocksRegistry.stripped_fir_stool_chair.get());
    		 event.accept(MFurniBOPBlocksRegistry.stripped_fir_counter.get());
    		 event.accept(MFurniBOPBlocksRegistry.stripped_fir_drawer_counter.get());
    		 event.accept(MFurniBOPBlocksRegistry.stripped_fir_double_drawer_counter.get());
    		 event.accept(MFurniBOPBlocksRegistry.stripped_fir_cupboard_counter.get());
    		 event.accept(MFurniBOPBlocksRegistry.fir_kitchen_cabinet.get());
    		 event.accept(MFurniBOPBlocksRegistry.fir_double_kitchen_cabinet.get());
    		 event.accept(MFurniBOPBlocksRegistry.fir_glass_kitchen_cabinet.get());
    		 event.accept(MFurniBOPBlocksRegistry.stripped_fir_kitchen_cabinet.get());
    		 event.accept(MFurniBOPBlocksRegistry.stripped_fir_double_kitchen_cabinet.get());
    		 event.accept(MFurniBOPBlocksRegistry.stripped_fir_glass_kitchen_cabinet.get());
    		 event.accept(MFurniBOPBlocksRegistry.hellbark_wardrobe.get());
    		 event.accept(MFurniBOPBlocksRegistry.hellbark_modern_wardrobe.get());
    		 event.accept(MFurniBOPBlocksRegistry.hellbark_double_wardrobe.get());
    		 event.accept(MFurniBOPBlocksRegistry.hellbark_bookshelf.get());
    		 event.accept(MFurniBOPBlocksRegistry.hellbark_bookshelf_cupboard.get());
    		 event.accept(MFurniBOPBlocksRegistry.hellbark_drawer.get());
    		 event.accept(MFurniBOPBlocksRegistry.hellbark_double_drawer.get());
    		 event.accept(MFurniBOPBlocksRegistry.hellbark_bookshelf_drawer.get());
    		 event.accept(MFurniBOPBlocksRegistry.hellbark_lower_bookshelf_drawer.get());
    		 event.accept(MFurniBOPBlocksRegistry.hellbark_large_drawer.get());
    		 event.accept(MFurniBOPBlocksRegistry.hellbark_lower_triple_drawer.get());
    		 event.accept(MFurniBOPBlocksRegistry.hellbark_triple_drawer.get());
    		 event.accept(MFurniBOPBlocksRegistry.hellbark_covered_desk.get());
    		 event.accept(MFurniBOPBlocksRegistry.hellbark_modern_desk.get());
    		 event.accept(MFurniBOPBlocksRegistry.hellbark_table.get());
    		 event.accept(MFurniBOPBlocksRegistry.hellbark_end_table.get());
    		 event.accept(MFurniBOPBlocksRegistry.hellbark_coffee_table.get());
    		 event.accept(MFurniBOPBlocksRegistry.hellbark_glass_table.get());
    		 event.accept(MFurniBOPBlocksRegistry.hellbark_chair.get());
    		 event.accept(MFurniBOPBlocksRegistry.hellbark_modern_chair.get());
    		 event.accept(MFurniBOPBlocksRegistry.hellbark_striped_chair.get());
    		 event.accept(MFurniBOPBlocksRegistry.hellbark_stool_chair.get());
    		 event.accept(MFurniBOPBlocksRegistry.hellbark_counter.get());
    		 event.accept(MFurniBOPBlocksRegistry.hellbark_drawer_counter.get());
    		 event.accept(MFurniBOPBlocksRegistry.hellbark_double_drawer_counter.get());
    		 event.accept(MFurniBOPBlocksRegistry.hellbark_cupboard_counter.get());
    		 event.accept(MFurniBOPBlocksRegistry.stripped_hellbark_wardrobe.get());
    		 event.accept(MFurniBOPBlocksRegistry.stripped_hellbark_modern_wardrobe.get());
    		 event.accept(MFurniBOPBlocksRegistry.stripped_hellbark_double_wardrobe.get());
    		 event.accept(MFurniBOPBlocksRegistry.stripped_hellbark_bookshelf.get());
    		 event.accept(MFurniBOPBlocksRegistry.stripped_hellbark_bookshelf_cupboard.get());
    		 event.accept(MFurniBOPBlocksRegistry.stripped_hellbark_drawer.get());
    		 event.accept(MFurniBOPBlocksRegistry.stripped_hellbark_double_drawer.get());
    		 event.accept(MFurniBOPBlocksRegistry.stripped_hellbark_bookshelf_drawer.get());
    		 event.accept(MFurniBOPBlocksRegistry.stripped_hellbark_lower_bookshelf_drawer.get());
    		 event.accept(MFurniBOPBlocksRegistry.stripped_hellbark_large_drawer.get());
    		 event.accept(MFurniBOPBlocksRegistry.stripped_hellbark_lower_triple_drawer.get());
    		 event.accept(MFurniBOPBlocksRegistry.stripped_hellbark_triple_drawer.get());
    		 event.accept(MFurniBOPBlocksRegistry.stripped_hellbark_desk.get());
    		 event.accept(MFurniBOPBlocksRegistry.stripped_hellbark_covered_desk.get());
    		 event.accept(MFurniBOPBlocksRegistry.stripped_hellbark_modern_desk.get());
    		 event.accept(MFurniBOPBlocksRegistry.stripped_hellbark_table.get());
    		 event.accept(MFurniBOPBlocksRegistry.stripped_hellbark_end_table.get());
    		 event.accept(MFurniBOPBlocksRegistry.stripped_hellbark_coffee_table.get());
    		 event.accept(MFurniBOPBlocksRegistry.stripped_hellbark_glass_table.get());
    		 event.accept(MFurniBOPBlocksRegistry.stripped_hellbark_modern_chair.get());
    		 event.accept(MFurniBOPBlocksRegistry.stripped_hellbark_striped_chair.get());
    		 event.accept(MFurniBOPBlocksRegistry.stripped_hellbark_stool_chair.get());
    		 event.accept(MFurniBOPBlocksRegistry.stripped_hellbark_counter.get());
    		 event.accept(MFurniBOPBlocksRegistry.stripped_hellbark_drawer_counter.get());
    		 event.accept(MFurniBOPBlocksRegistry.stripped_hellbark_double_drawer_counter.get());
    		 event.accept(MFurniBOPBlocksRegistry.stripped_hellbark_cupboard_counter.get());
    		 event.accept(MFurniBOPBlocksRegistry.hellbark_kitchen_cabinet.get());
    		 event.accept(MFurniBOPBlocksRegistry.hellbark_double_kitchen_cabinet.get());
    		 event.accept(MFurniBOPBlocksRegistry.hellbark_glass_kitchen_cabinet.get());
    		 event.accept(MFurniBOPBlocksRegistry.stripped_hellbark_kitchen_cabinet.get());
    		 event.accept(MFurniBOPBlocksRegistry.stripped_hellbark_double_kitchen_cabinet.get());
    		 event.accept(MFurniBOPBlocksRegistry.stripped_hellbark_glass_kitchen_cabinet.get());
    		 event.accept(MFurniBOPBlocksRegistry.jacaranda_wardrobe.get());
    		 event.accept(MFurniBOPBlocksRegistry.jacaranda_modern_wardrobe.get());
    		 event.accept(MFurniBOPBlocksRegistry.jacaranda_double_wardrobe.get());
    		 event.accept(MFurniBOPBlocksRegistry.jacaranda_bookshelf.get());
    		 event.accept(MFurniBOPBlocksRegistry.jacaranda_bookshelf_cupboard.get());
    		 event.accept(MFurniBOPBlocksRegistry.jacaranda_drawer.get());
    		 event.accept(MFurniBOPBlocksRegistry.jacaranda_double_drawer.get());
    		 event.accept(MFurniBOPBlocksRegistry.jacaranda_bookshelf_drawer.get());
    		 event.accept(MFurniBOPBlocksRegistry.jacaranda_lower_bookshelf_drawer.get());
    		 event.accept(MFurniBOPBlocksRegistry.jacaranda_large_drawer.get());
    		 event.accept(MFurniBOPBlocksRegistry.jacaranda_lower_triple_drawer.get());
    		 event.accept(MFurniBOPBlocksRegistry.jacaranda_triple_drawer.get());
    		 event.accept(MFurniBOPBlocksRegistry.jacaranda_covered_desk.get());
    		 event.accept(MFurniBOPBlocksRegistry.jacaranda_modern_desk.get());
    		 event.accept(MFurniBOPBlocksRegistry.jacaranda_table.get());
    		 event.accept(MFurniBOPBlocksRegistry.jacaranda_end_table.get());
    		 event.accept(MFurniBOPBlocksRegistry.jacaranda_coffee_table.get());
    		 event.accept(MFurniBOPBlocksRegistry.jacaranda_glass_table.get());
    		 event.accept(MFurniBOPBlocksRegistry.jacaranda_chair.get());
    		 event.accept(MFurniBOPBlocksRegistry.jacaranda_modern_chair.get());
    		 event.accept(MFurniBOPBlocksRegistry.jacaranda_striped_chair.get());
    		 event.accept(MFurniBOPBlocksRegistry.jacaranda_stool_chair.get());
    		 event.accept(MFurniBOPBlocksRegistry.jacaranda_counter.get());
    		 event.accept(MFurniBOPBlocksRegistry.jacaranda_drawer_counter.get());
    		 event.accept(MFurniBOPBlocksRegistry.jacaranda_double_drawer_counter.get());
    		 event.accept(MFurniBOPBlocksRegistry.jacaranda_cupboard_counter.get());
    		 event.accept(MFurniBOPBlocksRegistry.stripped_jacaranda_wardrobe.get());
    		 event.accept(MFurniBOPBlocksRegistry.stripped_jacaranda_modern_wardrobe.get());
    		 event.accept(MFurniBOPBlocksRegistry.stripped_jacaranda_double_wardrobe.get());
    		 event.accept(MFurniBOPBlocksRegistry.stripped_jacaranda_bookshelf.get());
    		 event.accept(MFurniBOPBlocksRegistry.stripped_jacaranda_bookshelf_cupboard.get());
    		 event.accept(MFurniBOPBlocksRegistry.stripped_jacaranda_drawer.get());
    		 event.accept(MFurniBOPBlocksRegistry.stripped_jacaranda_double_drawer.get());
    		 event.accept(MFurniBOPBlocksRegistry.stripped_jacaranda_bookshelf_drawer.get());
    		 event.accept(MFurniBOPBlocksRegistry.stripped_jacaranda_lower_bookshelf_drawer.get());
    		 event.accept(MFurniBOPBlocksRegistry.stripped_jacaranda_large_drawer.get());
    		 event.accept(MFurniBOPBlocksRegistry.stripped_jacaranda_lower_triple_drawer.get());
    		 event.accept(MFurniBOPBlocksRegistry.stripped_jacaranda_triple_drawer.get());
    		 event.accept(MFurniBOPBlocksRegistry.stripped_jacaranda_desk.get());
    		 event.accept(MFurniBOPBlocksRegistry.stripped_jacaranda_covered_desk.get());
    		 event.accept(MFurniBOPBlocksRegistry.stripped_jacaranda_modern_desk.get());
    		 event.accept(MFurniBOPBlocksRegistry.stripped_jacaranda_table.get());
    		 event.accept(MFurniBOPBlocksRegistry.stripped_jacaranda_end_table.get());
    		 event.accept(MFurniBOPBlocksRegistry.stripped_jacaranda_coffee_table.get());
    		 event.accept(MFurniBOPBlocksRegistry.stripped_jacaranda_glass_table.get());
    		 event.accept(MFurniBOPBlocksRegistry.stripped_jacaranda_modern_chair.get());
    		 event.accept(MFurniBOPBlocksRegistry.stripped_jacaranda_striped_chair.get());
    		 event.accept(MFurniBOPBlocksRegistry.stripped_jacaranda_stool_chair.get());
    		 event.accept(MFurniBOPBlocksRegistry.stripped_jacaranda_counter.get());
    		 event.accept(MFurniBOPBlocksRegistry.stripped_jacaranda_drawer_counter.get());
    		 event.accept(MFurniBOPBlocksRegistry.stripped_jacaranda_double_drawer_counter.get());
    		 event.accept(MFurniBOPBlocksRegistry.stripped_jacaranda_cupboard_counter.get());
    		 event.accept(MFurniBOPBlocksRegistry.jacaranda_kitchen_cabinet.get());
    		 event.accept(MFurniBOPBlocksRegistry.jacaranda_double_kitchen_cabinet.get());
    		 event.accept(MFurniBOPBlocksRegistry.jacaranda_glass_kitchen_cabinet.get());
    		 event.accept(MFurniBOPBlocksRegistry.stripped_jacaranda_kitchen_cabinet.get());
    		 event.accept(MFurniBOPBlocksRegistry.stripped_jacaranda_double_kitchen_cabinet.get());
    		 event.accept(MFurniBOPBlocksRegistry.stripped_jacaranda_glass_kitchen_cabinet.get());
    		 event.accept(MFurniBOPBlocksRegistry.magic_wardrobe.get());
    		 event.accept(MFurniBOPBlocksRegistry.magic_modern_wardrobe.get());
    		 event.accept(MFurniBOPBlocksRegistry.magic_double_wardrobe.get());
    		 event.accept(MFurniBOPBlocksRegistry.magic_bookshelf.get());
    		 event.accept(MFurniBOPBlocksRegistry.magic_bookshelf_cupboard.get());
    		 event.accept(MFurniBOPBlocksRegistry.magic_drawer.get());
    		 event.accept(MFurniBOPBlocksRegistry.magic_double_drawer.get());
    		 event.accept(MFurniBOPBlocksRegistry.magic_bookshelf_drawer.get());
    		 event.accept(MFurniBOPBlocksRegistry.magic_lower_bookshelf_drawer.get());
    		 event.accept(MFurniBOPBlocksRegistry.magic_large_drawer.get());
    		 event.accept(MFurniBOPBlocksRegistry.magic_lower_triple_drawer.get());
    		 event.accept(MFurniBOPBlocksRegistry.magic_triple_drawer.get());
    		 event.accept(MFurniBOPBlocksRegistry.magic_covered_desk.get());
    		 event.accept(MFurniBOPBlocksRegistry.magic_modern_desk.get());
    		 event.accept(MFurniBOPBlocksRegistry.magic_table.get());
    		 event.accept(MFurniBOPBlocksRegistry.magic_end_table.get());
    		 event.accept(MFurniBOPBlocksRegistry.magic_coffee_table.get());
    		 event.accept(MFurniBOPBlocksRegistry.magic_glass_table.get());
    		 event.accept(MFurniBOPBlocksRegistry.magic_chair.get());
    		 event.accept(MFurniBOPBlocksRegistry.magic_modern_chair.get());
    		 event.accept(MFurniBOPBlocksRegistry.magic_striped_chair.get());
    		 event.accept(MFurniBOPBlocksRegistry.magic_stool_chair.get());
    		 event.accept(MFurniBOPBlocksRegistry.magic_counter.get());
    		 event.accept(MFurniBOPBlocksRegistry.magic_drawer_counter.get());
    		 event.accept(MFurniBOPBlocksRegistry.magic_double_drawer_counter.get());
    		 event.accept(MFurniBOPBlocksRegistry.magic_cupboard_counter.get());
    		 event.accept(MFurniBOPBlocksRegistry.stripped_magic_wardrobe.get());
    		 event.accept(MFurniBOPBlocksRegistry.stripped_magic_modern_wardrobe.get());
    		 event.accept(MFurniBOPBlocksRegistry.stripped_magic_double_wardrobe.get());
    		 event.accept(MFurniBOPBlocksRegistry.stripped_magic_bookshelf.get());
    		 event.accept(MFurniBOPBlocksRegistry.stripped_magic_bookshelf_cupboard.get());
    		 event.accept(MFurniBOPBlocksRegistry.stripped_magic_drawer.get());
    		 event.accept(MFurniBOPBlocksRegistry.stripped_magic_double_drawer.get());
    		 event.accept(MFurniBOPBlocksRegistry.stripped_magic_bookshelf_drawer.get());
    		 event.accept(MFurniBOPBlocksRegistry.stripped_magic_lower_bookshelf_drawer.get());
    		 event.accept(MFurniBOPBlocksRegistry.stripped_magic_large_drawer.get());
    		 event.accept(MFurniBOPBlocksRegistry.stripped_magic_lower_triple_drawer.get());
    		 event.accept(MFurniBOPBlocksRegistry.stripped_magic_triple_drawer.get());
    		 event.accept(MFurniBOPBlocksRegistry.stripped_magic_desk.get());
    		 event.accept(MFurniBOPBlocksRegistry.stripped_magic_covered_desk.get());
    		 event.accept(MFurniBOPBlocksRegistry.stripped_magic_modern_desk.get());
    		 event.accept(MFurniBOPBlocksRegistry.stripped_magic_table.get());
    		 event.accept(MFurniBOPBlocksRegistry.stripped_magic_end_table.get());
    		 event.accept(MFurniBOPBlocksRegistry.stripped_magic_coffee_table.get());
    		 event.accept(MFurniBOPBlocksRegistry.stripped_magic_glass_table.get());
    		 event.accept(MFurniBOPBlocksRegistry.stripped_magic_modern_chair.get());
    		 event.accept(MFurniBOPBlocksRegistry.stripped_magic_striped_chair.get());
    		 event.accept(MFurniBOPBlocksRegistry.stripped_magic_stool_chair.get());
    		 event.accept(MFurniBOPBlocksRegistry.stripped_magic_counter.get());
    		 event.accept(MFurniBOPBlocksRegistry.stripped_magic_drawer_counter.get());
    		 event.accept(MFurniBOPBlocksRegistry.stripped_magic_double_drawer_counter.get());
    		 event.accept(MFurniBOPBlocksRegistry.stripped_magic_cupboard_counter.get());
    		 event.accept(MFurniBOPBlocksRegistry.magic_kitchen_cabinet.get());
    		 event.accept(MFurniBOPBlocksRegistry.magic_double_kitchen_cabinet.get());
    		 event.accept(MFurniBOPBlocksRegistry.magic_glass_kitchen_cabinet.get());
    		 event.accept(MFurniBOPBlocksRegistry.stripped_magic_kitchen_cabinet.get());
    		 event.accept(MFurniBOPBlocksRegistry.stripped_magic_double_kitchen_cabinet.get());
    		 event.accept(MFurniBOPBlocksRegistry.stripped_magic_glass_kitchen_cabinet.get());
    		 event.accept(MFurniBOPBlocksRegistry.mahogany_wardrobe.get());
    		 event.accept(MFurniBOPBlocksRegistry.mahogany_modern_wardrobe.get());
    		 event.accept(MFurniBOPBlocksRegistry.mahogany_double_wardrobe.get());
    		 event.accept(MFurniBOPBlocksRegistry.mahogany_bookshelf.get());
    		 event.accept(MFurniBOPBlocksRegistry.mahogany_bookshelf_cupboard.get());
    		 event.accept(MFurniBOPBlocksRegistry.mahogany_drawer.get());
    		 event.accept(MFurniBOPBlocksRegistry.mahogany_double_drawer.get());
    		 event.accept(MFurniBOPBlocksRegistry.mahogany_bookshelf_drawer.get());
    		 event.accept(MFurniBOPBlocksRegistry.mahogany_lower_bookshelf_drawer.get());
    		 event.accept(MFurniBOPBlocksRegistry.mahogany_large_drawer.get());
    		 event.accept(MFurniBOPBlocksRegistry.mahogany_lower_triple_drawer.get());
    		 event.accept(MFurniBOPBlocksRegistry.mahogany_triple_drawer.get());
    		 event.accept(MFurniBOPBlocksRegistry.mahogany_covered_desk.get());
    		 event.accept(MFurniBOPBlocksRegistry.mahogany_modern_desk.get());
    		 event.accept(MFurniBOPBlocksRegistry.mahogany_table.get());
    		 event.accept(MFurniBOPBlocksRegistry.mahogany_end_table.get());
    		 event.accept(MFurniBOPBlocksRegistry.mahogany_coffee_table.get());
    		 event.accept(MFurniBOPBlocksRegistry.mahogany_glass_table.get());
    		 event.accept(MFurniBOPBlocksRegistry.mahogany_chair.get());
    		 event.accept(MFurniBOPBlocksRegistry.mahogany_modern_chair.get());
    		 event.accept(MFurniBOPBlocksRegistry.mahogany_striped_chair.get());
    		 event.accept(MFurniBOPBlocksRegistry.mahogany_stool_chair.get());
    		 event.accept(MFurniBOPBlocksRegistry.mahogany_counter.get());
    		 event.accept(MFurniBOPBlocksRegistry.mahogany_drawer_counter.get());
    		 event.accept(MFurniBOPBlocksRegistry.mahogany_double_drawer_counter.get());
    		 event.accept(MFurniBOPBlocksRegistry.mahogany_cupboard_counter.get());
    		 event.accept(MFurniBOPBlocksRegistry.stripped_mahogany_wardrobe.get());
    		 event.accept(MFurniBOPBlocksRegistry.stripped_mahogany_modern_wardrobe.get());
    		 event.accept(MFurniBOPBlocksRegistry.stripped_mahogany_double_wardrobe.get());
    		 event.accept(MFurniBOPBlocksRegistry.stripped_mahogany_bookshelf.get());
    		 event.accept(MFurniBOPBlocksRegistry.stripped_mahogany_bookshelf_cupboard.get());
    		 event.accept(MFurniBOPBlocksRegistry.stripped_mahogany_drawer.get());
    		 event.accept(MFurniBOPBlocksRegistry.stripped_mahogany_double_drawer.get());
    		 event.accept(MFurniBOPBlocksRegistry.stripped_mahogany_bookshelf_drawer.get());
    		 event.accept(MFurniBOPBlocksRegistry.stripped_mahogany_lower_bookshelf_drawer.get());
    		 event.accept(MFurniBOPBlocksRegistry.stripped_mahogany_large_drawer.get());
    		 event.accept(MFurniBOPBlocksRegistry.stripped_mahogany_lower_triple_drawer.get());
    		 event.accept(MFurniBOPBlocksRegistry.stripped_mahogany_triple_drawer.get());
    		 event.accept(MFurniBOPBlocksRegistry.stripped_mahogany_desk.get());
    		 event.accept(MFurniBOPBlocksRegistry.stripped_mahogany_covered_desk.get());
    		 event.accept(MFurniBOPBlocksRegistry.stripped_mahogany_modern_desk.get());
    		 event.accept(MFurniBOPBlocksRegistry.stripped_mahogany_table.get());
    		 event.accept(MFurniBOPBlocksRegistry.stripped_mahogany_end_table.get());
    		 event.accept(MFurniBOPBlocksRegistry.stripped_mahogany_coffee_table.get());
    		 event.accept(MFurniBOPBlocksRegistry.stripped_mahogany_glass_table.get());
    		 event.accept(MFurniBOPBlocksRegistry.stripped_mahogany_modern_chair.get());
    		 event.accept(MFurniBOPBlocksRegistry.stripped_mahogany_striped_chair.get());
    		 event.accept(MFurniBOPBlocksRegistry.stripped_mahogany_stool_chair.get());
    		 event.accept(MFurniBOPBlocksRegistry.stripped_mahogany_counter.get());
    		 event.accept(MFurniBOPBlocksRegistry.stripped_mahogany_drawer_counter.get());
    		 event.accept(MFurniBOPBlocksRegistry.stripped_mahogany_double_drawer_counter.get());
    		 event.accept(MFurniBOPBlocksRegistry.stripped_mahogany_cupboard_counter.get());
    		 event.accept(MFurniBOPBlocksRegistry.mahogany_kitchen_cabinet.get());
    		 event.accept(MFurniBOPBlocksRegistry.mahogany_double_kitchen_cabinet.get());
    		 event.accept(MFurniBOPBlocksRegistry.mahogany_glass_kitchen_cabinet.get());
    		 event.accept(MFurniBOPBlocksRegistry.stripped_mahogany_kitchen_cabinet.get());
    		 event.accept(MFurniBOPBlocksRegistry.stripped_mahogany_double_kitchen_cabinet.get());
    		 event.accept(MFurniBOPBlocksRegistry.stripped_mahogany_glass_kitchen_cabinet.get());
    		 event.accept(MFurniBOPBlocksRegistry.palm_wardrobe.get());
    		 event.accept(MFurniBOPBlocksRegistry.palm_modern_wardrobe.get());
    		 event.accept(MFurniBOPBlocksRegistry.palm_double_wardrobe.get());
    		 event.accept(MFurniBOPBlocksRegistry.palm_bookshelf.get());
    		 event.accept(MFurniBOPBlocksRegistry.palm_bookshelf_cupboard.get());
    		 event.accept(MFurniBOPBlocksRegistry.palm_drawer.get());
    		 event.accept(MFurniBOPBlocksRegistry.palm_double_drawer.get());
    		 event.accept(MFurniBOPBlocksRegistry.palm_bookshelf_drawer.get());
    		 event.accept(MFurniBOPBlocksRegistry.palm_lower_bookshelf_drawer.get());
    		 event.accept(MFurniBOPBlocksRegistry.palm_large_drawer.get());
    		 event.accept(MFurniBOPBlocksRegistry.palm_lower_triple_drawer.get());
    		 event.accept(MFurniBOPBlocksRegistry.palm_triple_drawer.get());
    		 event.accept(MFurniBOPBlocksRegistry.palm_covered_desk.get());
    		 event.accept(MFurniBOPBlocksRegistry.palm_modern_desk.get());
    		 event.accept(MFurniBOPBlocksRegistry.palm_table.get());
    		 event.accept(MFurniBOPBlocksRegistry.palm_end_table.get());
    		 event.accept(MFurniBOPBlocksRegistry.palm_coffee_table.get());
    		 event.accept(MFurniBOPBlocksRegistry.palm_glass_table.get());
    		 event.accept(MFurniBOPBlocksRegistry.palm_chair.get());
    		 event.accept(MFurniBOPBlocksRegistry.palm_modern_chair.get());
    		 event.accept(MFurniBOPBlocksRegistry.palm_striped_chair.get());
    		 event.accept(MFurniBOPBlocksRegistry.palm_stool_chair.get());
    		 event.accept(MFurniBOPBlocksRegistry.palm_counter.get());
    		 event.accept(MFurniBOPBlocksRegistry.palm_drawer_counter.get());
    		 event.accept(MFurniBOPBlocksRegistry.palm_double_drawer_counter.get());
    		 event.accept(MFurniBOPBlocksRegistry.palm_cupboard_counter.get());
    		 event.accept(MFurniBOPBlocksRegistry.stripped_palm_wardrobe.get());
    		 event.accept(MFurniBOPBlocksRegistry.stripped_palm_modern_wardrobe.get());
    		 event.accept(MFurniBOPBlocksRegistry.stripped_palm_double_wardrobe.get());
    		 event.accept(MFurniBOPBlocksRegistry.stripped_palm_bookshelf.get());
    		 event.accept(MFurniBOPBlocksRegistry.stripped_palm_bookshelf_cupboard.get());
    		 event.accept(MFurniBOPBlocksRegistry.stripped_palm_drawer.get());
    		 event.accept(MFurniBOPBlocksRegistry.stripped_palm_double_drawer.get());
    		 event.accept(MFurniBOPBlocksRegistry.stripped_palm_bookshelf_drawer.get());
    		 event.accept(MFurniBOPBlocksRegistry.stripped_palm_lower_bookshelf_drawer.get());
    		 event.accept(MFurniBOPBlocksRegistry.stripped_palm_large_drawer.get());
    		 event.accept(MFurniBOPBlocksRegistry.stripped_palm_lower_triple_drawer.get());
    		 event.accept(MFurniBOPBlocksRegistry.stripped_palm_triple_drawer.get());
    		 event.accept(MFurniBOPBlocksRegistry.stripped_palm_desk.get());
    		 event.accept(MFurniBOPBlocksRegistry.stripped_palm_covered_desk.get());
    		 event.accept(MFurniBOPBlocksRegistry.stripped_palm_modern_desk.get());
    		 event.accept(MFurniBOPBlocksRegistry.stripped_palm_table.get());
    		 event.accept(MFurniBOPBlocksRegistry.stripped_palm_end_table.get());
    		 event.accept(MFurniBOPBlocksRegistry.stripped_palm_coffee_table.get());
    		 event.accept(MFurniBOPBlocksRegistry.stripped_palm_glass_table.get());
    		 event.accept(MFurniBOPBlocksRegistry.stripped_palm_modern_chair.get());
    		 event.accept(MFurniBOPBlocksRegistry.stripped_palm_striped_chair.get());
    		 event.accept(MFurniBOPBlocksRegistry.stripped_palm_stool_chair.get());
    		 event.accept(MFurniBOPBlocksRegistry.stripped_palm_counter.get());
    		 event.accept(MFurniBOPBlocksRegistry.stripped_palm_drawer_counter.get());
    		 event.accept(MFurniBOPBlocksRegistry.stripped_palm_double_drawer_counter.get());
    		 event.accept(MFurniBOPBlocksRegistry.stripped_palm_cupboard_counter.get());
    		 event.accept(MFurniBOPBlocksRegistry.palm_kitchen_cabinet.get());
    		 event.accept(MFurniBOPBlocksRegistry.palm_double_kitchen_cabinet.get());
    		 event.accept(MFurniBOPBlocksRegistry.palm_glass_kitchen_cabinet.get());
    		 event.accept(MFurniBOPBlocksRegistry.stripped_palm_kitchen_cabinet.get());
    		 event.accept(MFurniBOPBlocksRegistry.stripped_palm_double_kitchen_cabinet.get());
    		 event.accept(MFurniBOPBlocksRegistry.stripped_palm_glass_kitchen_cabinet.get());
    		 event.accept(MFurniBOPBlocksRegistry.redwood_wardrobe.get());
    		 event.accept(MFurniBOPBlocksRegistry.redwood_modern_wardrobe.get());
    		 event.accept(MFurniBOPBlocksRegistry.redwood_double_wardrobe.get());
    		 event.accept(MFurniBOPBlocksRegistry.redwood_bookshelf.get());
    		 event.accept(MFurniBOPBlocksRegistry.redwood_bookshelf_cupboard.get());
    		 event.accept(MFurniBOPBlocksRegistry.redwood_drawer.get());
    		 event.accept(MFurniBOPBlocksRegistry.redwood_double_drawer.get());
    		 event.accept(MFurniBOPBlocksRegistry.redwood_bookshelf_drawer.get());
    		 event.accept(MFurniBOPBlocksRegistry.redwood_lower_bookshelf_drawer.get());
    		 event.accept(MFurniBOPBlocksRegistry.redwood_large_drawer.get());
    		 event.accept(MFurniBOPBlocksRegistry.redwood_lower_triple_drawer.get());
    		 event.accept(MFurniBOPBlocksRegistry.redwood_triple_drawer.get());
    		 event.accept(MFurniBOPBlocksRegistry.redwood_covered_desk.get());
    		 event.accept(MFurniBOPBlocksRegistry.redwood_modern_desk.get());
    		 event.accept(MFurniBOPBlocksRegistry.redwood_table.get());
    		 event.accept(MFurniBOPBlocksRegistry.redwood_end_table.get());
    		 event.accept(MFurniBOPBlocksRegistry.redwood_coffee_table.get());
    		 event.accept(MFurniBOPBlocksRegistry.redwood_glass_table.get());
    		 event.accept(MFurniBOPBlocksRegistry.redwood_chair.get());
    		 event.accept(MFurniBOPBlocksRegistry.redwood_modern_chair.get());
    		 event.accept(MFurniBOPBlocksRegistry.redwood_striped_chair.get());
    		 event.accept(MFurniBOPBlocksRegistry.redwood_stool_chair.get());
    		 event.accept(MFurniBOPBlocksRegistry.redwood_counter.get());
    		 event.accept(MFurniBOPBlocksRegistry.redwood_drawer_counter.get());
    		 event.accept(MFurniBOPBlocksRegistry.redwood_double_drawer_counter.get());
    		 event.accept(MFurniBOPBlocksRegistry.redwood_cupboard_counter.get());
    		 event.accept(MFurniBOPBlocksRegistry.stripped_redwood_wardrobe.get());
    		 event.accept(MFurniBOPBlocksRegistry.stripped_redwood_modern_wardrobe.get());
    		 event.accept(MFurniBOPBlocksRegistry.stripped_redwood_double_wardrobe.get());
    		 event.accept(MFurniBOPBlocksRegistry.stripped_redwood_bookshelf.get());
    		 event.accept(MFurniBOPBlocksRegistry.stripped_redwood_bookshelf_cupboard.get());
    		 event.accept(MFurniBOPBlocksRegistry.stripped_redwood_drawer.get());
    		 event.accept(MFurniBOPBlocksRegistry.stripped_redwood_double_drawer.get());
    		 event.accept(MFurniBOPBlocksRegistry.stripped_redwood_bookshelf_drawer.get());
    		 event.accept(MFurniBOPBlocksRegistry.stripped_redwood_lower_bookshelf_drawer.get());
    		 event.accept(MFurniBOPBlocksRegistry.stripped_redwood_large_drawer.get());
    		 event.accept(MFurniBOPBlocksRegistry.stripped_redwood_lower_triple_drawer.get());
    		 event.accept(MFurniBOPBlocksRegistry.stripped_redwood_triple_drawer.get());
    		 event.accept(MFurniBOPBlocksRegistry.stripped_redwood_desk.get());
    		 event.accept(MFurniBOPBlocksRegistry.stripped_redwood_covered_desk.get());
    		 event.accept(MFurniBOPBlocksRegistry.stripped_redwood_modern_desk.get());
    		 event.accept(MFurniBOPBlocksRegistry.stripped_redwood_table.get());
    		 event.accept(MFurniBOPBlocksRegistry.stripped_redwood_end_table.get());
    		 event.accept(MFurniBOPBlocksRegistry.stripped_redwood_coffee_table.get());
    		 event.accept(MFurniBOPBlocksRegistry.stripped_redwood_glass_table.get());
    		 event.accept(MFurniBOPBlocksRegistry.stripped_redwood_modern_chair.get());
    		 event.accept(MFurniBOPBlocksRegistry.stripped_redwood_striped_chair.get());
    		 event.accept(MFurniBOPBlocksRegistry.stripped_redwood_stool_chair.get());
    		 event.accept(MFurniBOPBlocksRegistry.stripped_redwood_counter.get());
    		 event.accept(MFurniBOPBlocksRegistry.stripped_redwood_drawer_counter.get());
    		 event.accept(MFurniBOPBlocksRegistry.stripped_redwood_double_drawer_counter.get());
    		 event.accept(MFurniBOPBlocksRegistry.stripped_redwood_cupboard_counter.get());
    		 event.accept(MFurniBOPBlocksRegistry.redwood_kitchen_cabinet.get());
    		 event.accept(MFurniBOPBlocksRegistry.redwood_double_kitchen_cabinet.get());
    		 event.accept(MFurniBOPBlocksRegistry.redwood_glass_kitchen_cabinet.get());
    		 event.accept(MFurniBOPBlocksRegistry.stripped_redwood_kitchen_cabinet.get());
    		 event.accept(MFurniBOPBlocksRegistry.stripped_redwood_double_kitchen_cabinet.get());
    		 event.accept(MFurniBOPBlocksRegistry.stripped_redwood_glass_kitchen_cabinet.get());
    		 event.accept(MFurniBOPBlocksRegistry.umbran_wardrobe.get());
    		 event.accept(MFurniBOPBlocksRegistry.umbran_modern_wardrobe.get());
    		 event.accept(MFurniBOPBlocksRegistry.umbran_double_wardrobe.get());
    		 event.accept(MFurniBOPBlocksRegistry.umbran_bookshelf.get());
    		 event.accept(MFurniBOPBlocksRegistry.umbran_bookshelf_cupboard.get());
    		 event.accept(MFurniBOPBlocksRegistry.umbran_drawer.get());
    		 event.accept(MFurniBOPBlocksRegistry.umbran_double_drawer.get());
    		 event.accept(MFurniBOPBlocksRegistry.umbran_bookshelf_drawer.get());
    		 event.accept(MFurniBOPBlocksRegistry.umbran_lower_bookshelf_drawer.get());
    		 event.accept(MFurniBOPBlocksRegistry.umbran_large_drawer.get());
    		 event.accept(MFurniBOPBlocksRegistry.umbran_lower_triple_drawer.get());
    		 event.accept(MFurniBOPBlocksRegistry.umbran_triple_drawer.get());
    		 event.accept(MFurniBOPBlocksRegistry.umbran_covered_desk.get());
    		 event.accept(MFurniBOPBlocksRegistry.umbran_modern_desk.get());
    		 event.accept(MFurniBOPBlocksRegistry.umbran_table.get());
    		 event.accept(MFurniBOPBlocksRegistry.umbran_end_table.get());
    		 event.accept(MFurniBOPBlocksRegistry.umbran_coffee_table.get());
    		 event.accept(MFurniBOPBlocksRegistry.umbran_glass_table.get());
    		 event.accept(MFurniBOPBlocksRegistry.umbran_chair.get());
    		 event.accept(MFurniBOPBlocksRegistry.umbran_modern_chair.get());
    		 event.accept(MFurniBOPBlocksRegistry.umbran_striped_chair.get());
    		 event.accept(MFurniBOPBlocksRegistry.umbran_stool_chair.get());
    		 event.accept(MFurniBOPBlocksRegistry.umbran_counter.get());
    		 event.accept(MFurniBOPBlocksRegistry.umbran_drawer_counter.get());
    		 event.accept(MFurniBOPBlocksRegistry.umbran_double_drawer_counter.get());
    		 event.accept(MFurniBOPBlocksRegistry.umbran_cupboard_counter.get());
    		 event.accept(MFurniBOPBlocksRegistry.stripped_umbran_wardrobe.get());
    		 event.accept(MFurniBOPBlocksRegistry.stripped_umbran_modern_wardrobe.get());
    		 event.accept(MFurniBOPBlocksRegistry.stripped_umbran_double_wardrobe.get());
    		 event.accept(MFurniBOPBlocksRegistry.stripped_umbran_bookshelf.get());
    		 event.accept(MFurniBOPBlocksRegistry.stripped_umbran_bookshelf_cupboard.get());
    		 event.accept(MFurniBOPBlocksRegistry.stripped_umbran_drawer.get());
    		 event.accept(MFurniBOPBlocksRegistry.stripped_umbran_double_drawer.get());
    		 event.accept(MFurniBOPBlocksRegistry.stripped_umbran_bookshelf_drawer.get());
    		 event.accept(MFurniBOPBlocksRegistry.stripped_umbran_lower_bookshelf_drawer.get());
    		 event.accept(MFurniBOPBlocksRegistry.stripped_umbran_large_drawer.get());
    		 event.accept(MFurniBOPBlocksRegistry.stripped_umbran_lower_triple_drawer.get());
    		 event.accept(MFurniBOPBlocksRegistry.stripped_umbran_triple_drawer.get());
    		 event.accept(MFurniBOPBlocksRegistry.stripped_umbran_desk.get());
    		 event.accept(MFurniBOPBlocksRegistry.stripped_umbran_covered_desk.get());
    		 event.accept(MFurniBOPBlocksRegistry.stripped_umbran_modern_desk.get());
    		 event.accept(MFurniBOPBlocksRegistry.stripped_umbran_table.get());
    		 event.accept(MFurniBOPBlocksRegistry.stripped_umbran_end_table.get());
    		 event.accept(MFurniBOPBlocksRegistry.stripped_umbran_coffee_table.get());
    		 event.accept(MFurniBOPBlocksRegistry.stripped_umbran_glass_table.get());
    		 event.accept(MFurniBOPBlocksRegistry.stripped_umbran_modern_chair.get());
    		 event.accept(MFurniBOPBlocksRegistry.stripped_umbran_striped_chair.get());
    		 event.accept(MFurniBOPBlocksRegistry.stripped_umbran_stool_chair.get());
    		 event.accept(MFurniBOPBlocksRegistry.stripped_umbran_counter.get());
    		 event.accept(MFurniBOPBlocksRegistry.stripped_umbran_drawer_counter.get());
    		 event.accept(MFurniBOPBlocksRegistry.stripped_umbran_double_drawer_counter.get());
    		 event.accept(MFurniBOPBlocksRegistry.stripped_umbran_cupboard_counter.get());
    		 event.accept(MFurniBOPBlocksRegistry.umbran_kitchen_cabinet.get());
    		 event.accept(MFurniBOPBlocksRegistry.umbran_double_kitchen_cabinet.get());
    		 event.accept(MFurniBOPBlocksRegistry.umbran_glass_kitchen_cabinet.get());
    		 event.accept(MFurniBOPBlocksRegistry.stripped_umbran_kitchen_cabinet.get());
    		 event.accept(MFurniBOPBlocksRegistry.stripped_umbran_double_kitchen_cabinet.get());
    		 event.accept(MFurniBOPBlocksRegistry.stripped_umbran_glass_kitchen_cabinet.get());
    		 event.accept(MFurniBOPBlocksRegistry.willow_wardrobe.get());
    		 event.accept(MFurniBOPBlocksRegistry.willow_modern_wardrobe.get());
    		 event.accept(MFurniBOPBlocksRegistry.willow_double_wardrobe.get());
    		 event.accept(MFurniBOPBlocksRegistry.willow_bookshelf.get());
    		 event.accept(MFurniBOPBlocksRegistry.willow_bookshelf_cupboard.get());
    		 event.accept(MFurniBOPBlocksRegistry.willow_drawer.get());
    		 event.accept(MFurniBOPBlocksRegistry.willow_double_drawer.get());
    		 event.accept(MFurniBOPBlocksRegistry.willow_bookshelf_drawer.get());
    		 event.accept(MFurniBOPBlocksRegistry.willow_lower_bookshelf_drawer.get());
    		 event.accept(MFurniBOPBlocksRegistry.willow_large_drawer.get());
    		 event.accept(MFurniBOPBlocksRegistry.willow_lower_triple_drawer.get());
    		 event.accept(MFurniBOPBlocksRegistry.willow_triple_drawer.get());
    		 event.accept(MFurniBOPBlocksRegistry.willow_covered_desk.get());
    		 event.accept(MFurniBOPBlocksRegistry.willow_modern_desk.get());
    		 event.accept(MFurniBOPBlocksRegistry.willow_table.get());
    		 event.accept(MFurniBOPBlocksRegistry.willow_end_table.get());
    		 event.accept(MFurniBOPBlocksRegistry.willow_coffee_table.get());
    		 event.accept(MFurniBOPBlocksRegistry.willow_glass_table.get());
    		 event.accept(MFurniBOPBlocksRegistry.willow_chair.get());
    		 event.accept(MFurniBOPBlocksRegistry.willow_modern_chair.get());
    		 event.accept(MFurniBOPBlocksRegistry.willow_striped_chair.get());
    		 event.accept(MFurniBOPBlocksRegistry.willow_stool_chair.get());
    		 event.accept(MFurniBOPBlocksRegistry.willow_counter.get());
    		 event.accept(MFurniBOPBlocksRegistry.willow_drawer_counter.get());
    		 event.accept(MFurniBOPBlocksRegistry.willow_double_drawer_counter.get());
    		 event.accept(MFurniBOPBlocksRegistry.willow_cupboard_counter.get());
    		 event.accept(MFurniBOPBlocksRegistry.stripped_willow_wardrobe.get());
    		 event.accept(MFurniBOPBlocksRegistry.stripped_willow_modern_wardrobe.get());
    		 event.accept(MFurniBOPBlocksRegistry.stripped_willow_double_wardrobe.get());
    		 event.accept(MFurniBOPBlocksRegistry.stripped_willow_bookshelf.get());
    		 event.accept(MFurniBOPBlocksRegistry.stripped_willow_bookshelf_cupboard.get());
    		 event.accept(MFurniBOPBlocksRegistry.stripped_willow_drawer.get());
    		 event.accept(MFurniBOPBlocksRegistry.stripped_willow_double_drawer.get());
    		 event.accept(MFurniBOPBlocksRegistry.stripped_willow_bookshelf_drawer.get());
    		 event.accept(MFurniBOPBlocksRegistry.stripped_willow_lower_bookshelf_drawer.get());
    		 event.accept(MFurniBOPBlocksRegistry.stripped_willow_large_drawer.get());
    		 event.accept(MFurniBOPBlocksRegistry.stripped_willow_lower_triple_drawer.get());
    		 event.accept(MFurniBOPBlocksRegistry.stripped_willow_triple_drawer.get());
    		 event.accept(MFurniBOPBlocksRegistry.stripped_willow_desk.get());
    		 event.accept(MFurniBOPBlocksRegistry.stripped_willow_covered_desk.get());
    		 event.accept(MFurniBOPBlocksRegistry.stripped_willow_modern_desk.get());
    		 event.accept(MFurniBOPBlocksRegistry.stripped_willow_table.get());
    		 event.accept(MFurniBOPBlocksRegistry.stripped_willow_end_table.get());
    		 event.accept(MFurniBOPBlocksRegistry.stripped_willow_coffee_table.get());
    		 event.accept(MFurniBOPBlocksRegistry.stripped_willow_glass_table.get());
    		 event.accept(MFurniBOPBlocksRegistry.stripped_willow_modern_chair.get());
    		 event.accept(MFurniBOPBlocksRegistry.stripped_willow_striped_chair.get());
    		 event.accept(MFurniBOPBlocksRegistry.stripped_willow_stool_chair.get());
    		 event.accept(MFurniBOPBlocksRegistry.stripped_willow_counter.get());
    		 event.accept(MFurniBOPBlocksRegistry.stripped_willow_drawer_counter.get());
    		 event.accept(MFurniBOPBlocksRegistry.stripped_willow_double_drawer_counter.get());
    		 event.accept(MFurniBOPBlocksRegistry.stripped_willow_cupboard_counter.get());
    		 event.accept(MFurniBOPBlocksRegistry.willow_kitchen_cabinet.get());
    		 event.accept(MFurniBOPBlocksRegistry.willow_double_kitchen_cabinet.get());
    		 event.accept(MFurniBOPBlocksRegistry.willow_glass_kitchen_cabinet.get());
    		 event.accept(MFurniBOPBlocksRegistry.stripped_willow_kitchen_cabinet.get());
    		 event.accept(MFurniBOPBlocksRegistry.stripped_willow_double_kitchen_cabinet.get());
    		 event.accept(MFurniBOPBlocksRegistry.stripped_willow_glass_kitchen_cabinet.get());
    		 event.accept(MFurniBOPBlocksRegistry.empyreal_wardrobe.get());
    		 event.accept(MFurniBOPBlocksRegistry.empyreal_modern_wardrobe.get());
    		 event.accept(MFurniBOPBlocksRegistry.empyreal_double_wardrobe.get());
    		 event.accept(MFurniBOPBlocksRegistry.empyreal_bookshelf.get());
    		 event.accept(MFurniBOPBlocksRegistry.empyreal_bookshelf_cupboard.get());
    		 event.accept(MFurniBOPBlocksRegistry.empyreal_drawer.get());
    		 event.accept(MFurniBOPBlocksRegistry.empyreal_double_drawer.get());
    		 event.accept(MFurniBOPBlocksRegistry.empyreal_bookshelf_drawer.get());
    		 event.accept(MFurniBOPBlocksRegistry.empyreal_lower_bookshelf_drawer.get());
    		 event.accept(MFurniBOPBlocksRegistry.empyreal_large_drawer.get());
    		 event.accept(MFurniBOPBlocksRegistry.empyreal_lower_triple_drawer.get());
    		 event.accept(MFurniBOPBlocksRegistry.empyreal_triple_drawer.get());
    		 event.accept(MFurniBOPBlocksRegistry.empyreal_covered_desk.get());
    		 event.accept(MFurniBOPBlocksRegistry.empyreal_modern_desk.get());
    		 event.accept(MFurniBOPBlocksRegistry.empyreal_table.get());
    		 event.accept(MFurniBOPBlocksRegistry.empyreal_end_table.get());
    		 event.accept(MFurniBOPBlocksRegistry.empyreal_coffee_table.get());
    		 event.accept(MFurniBOPBlocksRegistry.empyreal_glass_table.get());
    		 event.accept(MFurniBOPBlocksRegistry.empyreal_chair.get());
    		 event.accept(MFurniBOPBlocksRegistry.empyreal_modern_chair.get());
    		 event.accept(MFurniBOPBlocksRegistry.empyreal_striped_chair.get());
    		 event.accept(MFurniBOPBlocksRegistry.empyreal_stool_chair.get());
    		 event.accept(MFurniBOPBlocksRegistry.empyreal_counter.get());
    		 event.accept(MFurniBOPBlocksRegistry.empyreal_drawer_counter.get());
    		 event.accept(MFurniBOPBlocksRegistry.empyreal_double_drawer_counter.get());
    		 event.accept(MFurniBOPBlocksRegistry.empyreal_cupboard_counter.get());
    		 event.accept(MFurniBOPBlocksRegistry.stripped_empyreal_wardrobe.get());
    		 event.accept(MFurniBOPBlocksRegistry.stripped_empyreal_modern_wardrobe.get());
    		 event.accept(MFurniBOPBlocksRegistry.stripped_empyreal_double_wardrobe.get());
    		 event.accept(MFurniBOPBlocksRegistry.stripped_empyreal_bookshelf.get());
    		 event.accept(MFurniBOPBlocksRegistry.stripped_empyreal_bookshelf_cupboard.get());
    		 event.accept(MFurniBOPBlocksRegistry.stripped_empyreal_drawer.get());
    		 event.accept(MFurniBOPBlocksRegistry.stripped_empyreal_double_drawer.get());
    		 event.accept(MFurniBOPBlocksRegistry.stripped_empyreal_bookshelf_drawer.get());
    		 event.accept(MFurniBOPBlocksRegistry.stripped_empyreal_lower_bookshelf_drawer.get());
    		 event.accept(MFurniBOPBlocksRegistry.stripped_empyreal_large_drawer.get());
    		 event.accept(MFurniBOPBlocksRegistry.stripped_empyreal_lower_triple_drawer.get());
    		 event.accept(MFurniBOPBlocksRegistry.stripped_empyreal_triple_drawer.get());
    		 event.accept(MFurniBOPBlocksRegistry.stripped_empyreal_desk.get());
    		 event.accept(MFurniBOPBlocksRegistry.stripped_empyreal_covered_desk.get());
    		 event.accept(MFurniBOPBlocksRegistry.stripped_empyreal_modern_desk.get());
    		 event.accept(MFurniBOPBlocksRegistry.stripped_empyreal_table.get());
    		 event.accept(MFurniBOPBlocksRegistry.stripped_empyreal_end_table.get());
    		 event.accept(MFurniBOPBlocksRegistry.stripped_empyreal_coffee_table.get());
    		 event.accept(MFurniBOPBlocksRegistry.stripped_empyreal_glass_table.get());
    		 event.accept(MFurniBOPBlocksRegistry.stripped_empyreal_modern_chair.get());
    		 event.accept(MFurniBOPBlocksRegistry.stripped_empyreal_striped_chair.get());
    		 event.accept(MFurniBOPBlocksRegistry.stripped_empyreal_stool_chair.get());
    		 event.accept(MFurniBOPBlocksRegistry.stripped_empyreal_counter.get());
    		 event.accept(MFurniBOPBlocksRegistry.stripped_empyreal_drawer_counter.get());
    		 event.accept(MFurniBOPBlocksRegistry.stripped_empyreal_double_drawer_counter.get());
    		 event.accept(MFurniBOPBlocksRegistry.stripped_empyreal_cupboard_counter.get());
    		 event.accept(MFurniBOPBlocksRegistry.empyreal_kitchen_cabinet.get());
    		 event.accept(MFurniBOPBlocksRegistry.empyreal_double_kitchen_cabinet.get());
    		 event.accept(MFurniBOPBlocksRegistry.empyreal_glass_kitchen_cabinet.get());
    		 event.accept(MFurniBOPBlocksRegistry.stripped_empyreal_kitchen_cabinet.get());
    		 event.accept(MFurniBOPBlocksRegistry.stripped_empyreal_double_kitchen_cabinet.get());
    		 event.accept(MFurniBOPBlocksRegistry.stripped_empyreal_glass_kitchen_cabinet.get());
    	 }
    }
}