package fr.samlegamer.mcwfurnituresbop.block;

import fr.samlegamer.mcwfurnituresbop.McwFurnituresBOP;
import net.kikoz.mcwfurnitures.objects.Chair;
import net.kikoz.mcwfurnitures.objects.Desk;
import net.kikoz.mcwfurnitures.objects.Table;
import net.kikoz.mcwfurnitures.objects.TableHitbox;
import net.kikoz.mcwfurnitures.objects.TallFurniture;
import net.kikoz.mcwfurnitures.objects.TallFurnitureHinge;
import net.kikoz.mcwfurnitures.objects.WideFurniture;
import net.kikoz.mcwfurnitures.objects.chairs.ModernChair;
import net.kikoz.mcwfurnitures.objects.chairs.StripedChair;
import net.kikoz.mcwfurnitures.objects.counters.Counter;
import net.kikoz.mcwfurnitures.objects.counters.StorageCounter;
import net.minecraft.block.AbstractBlock;
import net.minecraft.block.Block;
import net.minecraft.item.BlockItem;
import net.minecraft.item.Item;
import net.minecraft.registry.Registries;
import net.minecraft.registry.Registry;
import net.minecraft.util.Identifier;

public class MFurniBOPBlocksRegistry
{
	public static final Block dead_wardrobe = new TallFurnitureHinge(AbstractBlock.Settings.create().strength(2.0F, 2.3F));
	public static final Block dead_modern_wardrobe = new TallFurnitureHinge(AbstractBlock.Settings.create().strength(2.0F, 2.3F));
	public static final Block dead_double_wardrobe = new TallFurniture(AbstractBlock.Settings.create().strength(2.0F, 2.3F));
	public static final Block dead_bookshelf = new TallFurniture(AbstractBlock.Settings.create().strength(2.0F, 2.3F));
	public static final Block dead_bookshelf_cupboard = new TallFurnitureHinge(AbstractBlock.Settings.create().strength(2.0F, 2.3F));
	public static final Block dead_drawer = new WideFurniture(AbstractBlock.Settings.create().strength(2.0F, 2.3F));
	public static final Block dead_double_drawer = new WideFurniture(AbstractBlock.Settings.create().strength(2.0F, 2.3F));
	public static final Block dead_bookshelf_drawer = new WideFurniture(AbstractBlock.Settings.create().strength(2.0F, 2.3F));
	public static final Block dead_lower_bookshelf_drawer = new WideFurniture(AbstractBlock.Settings.create().strength(2.0F, 2.3F));
	public static final Block dead_large_drawer = new WideFurniture(AbstractBlock.Settings.create().strength(2.0F, 2.3F));
	public static final Block dead_lower_triple_drawer = new WideFurniture(AbstractBlock.Settings.create().strength(2.0F, 2.3F));
	public static final Block dead_triple_drawer = new WideFurniture(AbstractBlock.Settings.create().strength(2.0F, 2.3F));
	public static final Block dead_desk = new Desk(AbstractBlock.Settings.create().strength(2.0F, 2.3F));
	public static final Block dead_covered_desk = new Desk(AbstractBlock.Settings.create().strength(2.0F, 2.3F));
	public static final Block dead_modern_desk = new Desk(AbstractBlock.Settings.create().strength(2.0F, 2.3F));
	public static final Block dead_table = new TableHitbox(AbstractBlock.Settings.create().strength(2.0F, 2.3F));
	public static final Block dead_end_table = new TableHitbox(AbstractBlock.Settings.create().strength(2.0F, 2.3F));
	public static final Block dead_coffee_table = new Table(AbstractBlock.Settings.create().strength(2.0F, 2.3F));
	public static final Block dead_glass_table = new TableHitbox(AbstractBlock.Settings.create().strength(2.0F, 2.3F));
	public static final Block dead_chair = new StripedChair(AbstractBlock.Settings.create().strength(2.0F, 2.3F));
	public static final Block dead_modern_chair = new ModernChair(AbstractBlock.Settings.create().strength(2.0F, 2.3F));
	public static final Block dead_striped_chair = new StripedChair(AbstractBlock.Settings.create().strength(2.0F, 2.3F));
	public static final Block dead_stool_chair = new Chair(AbstractBlock.Settings.create().strength(2.0F, 2.3F));
	public static final Block dead_counter = new Counter(AbstractBlock.Settings.create().strength(2.0F, 2.3F));
	public static final Block dead_drawer_counter = new StorageCounter(AbstractBlock.Settings.create().strength(2.0F, 2.3F));
	public static final Block dead_double_drawer_counter = new StorageCounter(AbstractBlock.Settings.create().strength(2.0F, 2.3F));
	public static final Block dead_cupboard_counter = new StorageCounter(AbstractBlock.Settings.create().strength(2.0F, 2.3F));
	public static final Block fir_wardrobe = new TallFurnitureHinge(AbstractBlock.Settings.create().strength(2.0F, 2.3F));
	public static final Block fir_modern_wardrobe = new TallFurnitureHinge(AbstractBlock.Settings.create().strength(2.0F, 2.3F));
	public static final Block fir_double_wardrobe = new TallFurniture(AbstractBlock.Settings.create().strength(2.0F, 2.3F));
	public static final Block fir_bookshelf = new TallFurniture(AbstractBlock.Settings.create().strength(2.0F, 2.3F));
	public static final Block fir_bookshelf_cupboard = new TallFurnitureHinge(AbstractBlock.Settings.create().strength(2.0F, 2.3F));
	public static final Block fir_drawer = new WideFurniture(AbstractBlock.Settings.create().strength(2.0F, 2.3F));
	public static final Block fir_double_drawer = new WideFurniture(AbstractBlock.Settings.create().strength(2.0F, 2.3F));
	public static final Block fir_bookshelf_drawer = new WideFurniture(AbstractBlock.Settings.create().strength(2.0F, 2.3F));
	public static final Block fir_lower_bookshelf_drawer = new WideFurniture(AbstractBlock.Settings.create().strength(2.0F, 2.3F));
	public static final Block fir_large_drawer = new WideFurniture(AbstractBlock.Settings.create().strength(2.0F, 2.3F));
	public static final Block fir_lower_triple_drawer = new WideFurniture(AbstractBlock.Settings.create().strength(2.0F, 2.3F));
	public static final Block fir_triple_drawer = new WideFurniture(AbstractBlock.Settings.create().strength(2.0F, 2.3F));
	public static final Block fir_desk = new Desk(AbstractBlock.Settings.create().strength(2.0F, 2.3F));
	public static final Block fir_covered_desk = new Desk(AbstractBlock.Settings.create().strength(2.0F, 2.3F));
	public static final Block fir_modern_desk = new Desk(AbstractBlock.Settings.create().strength(2.0F, 2.3F));
	public static final Block fir_table = new TableHitbox(AbstractBlock.Settings.create().strength(2.0F, 2.3F));
	public static final Block fir_end_table = new TableHitbox(AbstractBlock.Settings.create().strength(2.0F, 2.3F));
	public static final Block fir_coffee_table = new Table(AbstractBlock.Settings.create().strength(2.0F, 2.3F));
	public static final Block fir_glass_table = new TableHitbox(AbstractBlock.Settings.create().strength(2.0F, 2.3F));
	public static final Block fir_chair = new StripedChair(AbstractBlock.Settings.create().strength(2.0F, 2.3F));
	public static final Block fir_modern_chair = new ModernChair(AbstractBlock.Settings.create().strength(2.0F, 2.3F));
	public static final Block fir_striped_chair = new StripedChair(AbstractBlock.Settings.create().strength(2.0F, 2.3F));
	public static final Block fir_stool_chair = new Chair(AbstractBlock.Settings.create().strength(2.0F, 2.3F));
	public static final Block fir_counter = new Counter(AbstractBlock.Settings.create().strength(2.0F, 2.3F));
	public static final Block fir_drawer_counter = new StorageCounter(AbstractBlock.Settings.create().strength(2.0F, 2.3F));
	public static final Block fir_double_drawer_counter = new StorageCounter(AbstractBlock.Settings.create().strength(2.0F, 2.3F));
	public static final Block fir_cupboard_counter = new StorageCounter(AbstractBlock.Settings.create().strength(2.0F, 2.3F));
	public static final Block hellbark_wardrobe = new TallFurnitureHinge(AbstractBlock.Settings.create().strength(2.0F, 2.3F));
	public static final Block hellbark_modern_wardrobe = new TallFurnitureHinge(AbstractBlock.Settings.create().strength(2.0F, 2.3F));
	public static final Block hellbark_double_wardrobe = new TallFurniture(AbstractBlock.Settings.create().strength(2.0F, 2.3F));
	public static final Block hellbark_bookshelf = new TallFurniture(AbstractBlock.Settings.create().strength(2.0F, 2.3F));
	public static final Block hellbark_bookshelf_cupboard = new TallFurnitureHinge(AbstractBlock.Settings.create().strength(2.0F, 2.3F));
	public static final Block hellbark_drawer = new WideFurniture(AbstractBlock.Settings.create().strength(2.0F, 2.3F));
	public static final Block hellbark_double_drawer = new WideFurniture(AbstractBlock.Settings.create().strength(2.0F, 2.3F));
	public static final Block hellbark_bookshelf_drawer = new WideFurniture(AbstractBlock.Settings.create().strength(2.0F, 2.3F));
	public static final Block hellbark_lower_bookshelf_drawer = new WideFurniture(AbstractBlock.Settings.create().strength(2.0F, 2.3F));
	public static final Block hellbark_large_drawer = new WideFurniture(AbstractBlock.Settings.create().strength(2.0F, 2.3F));
	public static final Block hellbark_lower_triple_drawer = new WideFurniture(AbstractBlock.Settings.create().strength(2.0F, 2.3F));
	public static final Block hellbark_triple_drawer = new WideFurniture(AbstractBlock.Settings.create().strength(2.0F, 2.3F));
	public static final Block hellbark_desk = new Desk(AbstractBlock.Settings.create().strength(2.0F, 2.3F));
	public static final Block hellbark_covered_desk = new Desk(AbstractBlock.Settings.create().strength(2.0F, 2.3F));
	public static final Block hellbark_modern_desk = new Desk(AbstractBlock.Settings.create().strength(2.0F, 2.3F));
	public static final Block hellbark_table = new TableHitbox(AbstractBlock.Settings.create().strength(2.0F, 2.3F));
	public static final Block hellbark_end_table = new TableHitbox(AbstractBlock.Settings.create().strength(2.0F, 2.3F));
	public static final Block hellbark_coffee_table = new Table(AbstractBlock.Settings.create().strength(2.0F, 2.3F));
	public static final Block hellbark_glass_table = new TableHitbox(AbstractBlock.Settings.create().strength(2.0F, 2.3F));
	public static final Block hellbark_chair = new StripedChair(AbstractBlock.Settings.create().strength(2.0F, 2.3F));
	public static final Block hellbark_modern_chair = new ModernChair(AbstractBlock.Settings.create().strength(2.0F, 2.3F));
	public static final Block hellbark_striped_chair = new StripedChair(AbstractBlock.Settings.create().strength(2.0F, 2.3F));
	public static final Block hellbark_stool_chair = new Chair(AbstractBlock.Settings.create().strength(2.0F, 2.3F));
	public static final Block hellbark_counter = new Counter(AbstractBlock.Settings.create().strength(2.0F, 2.3F));
	public static final Block hellbark_drawer_counter = new StorageCounter(AbstractBlock.Settings.create().strength(2.0F, 2.3F));
	public static final Block hellbark_double_drawer_counter = new StorageCounter(AbstractBlock.Settings.create().strength(2.0F, 2.3F));
	public static final Block hellbark_cupboard_counter = new StorageCounter(AbstractBlock.Settings.create().strength(2.0F, 2.3F));
	public static final Block jacaranda_wardrobe = new TallFurnitureHinge(AbstractBlock.Settings.create().strength(2.0F, 2.3F));
	public static final Block jacaranda_modern_wardrobe = new TallFurnitureHinge(AbstractBlock.Settings.create().strength(2.0F, 2.3F));
	public static final Block jacaranda_double_wardrobe = new TallFurniture(AbstractBlock.Settings.create().strength(2.0F, 2.3F));
	public static final Block jacaranda_bookshelf = new TallFurniture(AbstractBlock.Settings.create().strength(2.0F, 2.3F));
	public static final Block jacaranda_bookshelf_cupboard = new TallFurnitureHinge(AbstractBlock.Settings.create().strength(2.0F, 2.3F));
	public static final Block jacaranda_drawer = new WideFurniture(AbstractBlock.Settings.create().strength(2.0F, 2.3F));
	public static final Block jacaranda_double_drawer = new WideFurniture(AbstractBlock.Settings.create().strength(2.0F, 2.3F));
	public static final Block jacaranda_bookshelf_drawer = new WideFurniture(AbstractBlock.Settings.create().strength(2.0F, 2.3F));
	public static final Block jacaranda_lower_bookshelf_drawer = new WideFurniture(AbstractBlock.Settings.create().strength(2.0F, 2.3F));
	public static final Block jacaranda_large_drawer = new WideFurniture(AbstractBlock.Settings.create().strength(2.0F, 2.3F));
	public static final Block jacaranda_lower_triple_drawer = new WideFurniture(AbstractBlock.Settings.create().strength(2.0F, 2.3F));
	public static final Block jacaranda_triple_drawer = new WideFurniture(AbstractBlock.Settings.create().strength(2.0F, 2.3F));
	public static final Block jacaranda_desk = new Desk(AbstractBlock.Settings.create().strength(2.0F, 2.3F));
	public static final Block jacaranda_covered_desk = new Desk(AbstractBlock.Settings.create().strength(2.0F, 2.3F));
	public static final Block jacaranda_modern_desk = new Desk(AbstractBlock.Settings.create().strength(2.0F, 2.3F));
	public static final Block jacaranda_table = new TableHitbox(AbstractBlock.Settings.create().strength(2.0F, 2.3F));
	public static final Block jacaranda_end_table = new TableHitbox(AbstractBlock.Settings.create().strength(2.0F, 2.3F));
	public static final Block jacaranda_coffee_table = new Table(AbstractBlock.Settings.create().strength(2.0F, 2.3F));
	public static final Block jacaranda_glass_table = new TableHitbox(AbstractBlock.Settings.create().strength(2.0F, 2.3F));
	public static final Block jacaranda_chair = new StripedChair(AbstractBlock.Settings.create().strength(2.0F, 2.3F));
	public static final Block jacaranda_modern_chair = new ModernChair(AbstractBlock.Settings.create().strength(2.0F, 2.3F));
	public static final Block jacaranda_striped_chair = new StripedChair(AbstractBlock.Settings.create().strength(2.0F, 2.3F));
	public static final Block jacaranda_stool_chair = new Chair(AbstractBlock.Settings.create().strength(2.0F, 2.3F));
	public static final Block jacaranda_counter = new Counter(AbstractBlock.Settings.create().strength(2.0F, 2.3F));
	public static final Block jacaranda_drawer_counter = new StorageCounter(AbstractBlock.Settings.create().strength(2.0F, 2.3F));
	public static final Block jacaranda_double_drawer_counter = new StorageCounter(AbstractBlock.Settings.create().strength(2.0F, 2.3F));
	public static final Block jacaranda_cupboard_counter = new StorageCounter(AbstractBlock.Settings.create().strength(2.0F, 2.3F));
	public static final Block magic_wardrobe = new TallFurnitureHinge(AbstractBlock.Settings.create().strength(2.0F, 2.3F));
	public static final Block magic_modern_wardrobe = new TallFurnitureHinge(AbstractBlock.Settings.create().strength(2.0F, 2.3F));
	public static final Block magic_double_wardrobe = new TallFurniture(AbstractBlock.Settings.create().strength(2.0F, 2.3F));
	public static final Block magic_bookshelf = new TallFurniture(AbstractBlock.Settings.create().strength(2.0F, 2.3F));
	public static final Block magic_bookshelf_cupboard = new TallFurnitureHinge(AbstractBlock.Settings.create().strength(2.0F, 2.3F));
	public static final Block magic_drawer = new WideFurniture(AbstractBlock.Settings.create().strength(2.0F, 2.3F));
	public static final Block magic_double_drawer = new WideFurniture(AbstractBlock.Settings.create().strength(2.0F, 2.3F));
	public static final Block magic_bookshelf_drawer = new WideFurniture(AbstractBlock.Settings.create().strength(2.0F, 2.3F));
	public static final Block magic_lower_bookshelf_drawer = new WideFurniture(AbstractBlock.Settings.create().strength(2.0F, 2.3F));
	public static final Block magic_large_drawer = new WideFurniture(AbstractBlock.Settings.create().strength(2.0F, 2.3F));
	public static final Block magic_lower_triple_drawer = new WideFurniture(AbstractBlock.Settings.create().strength(2.0F, 2.3F));
	public static final Block magic_triple_drawer = new WideFurniture(AbstractBlock.Settings.create().strength(2.0F, 2.3F));
	public static final Block magic_desk = new Desk(AbstractBlock.Settings.create().strength(2.0F, 2.3F));
	public static final Block magic_covered_desk = new Desk(AbstractBlock.Settings.create().strength(2.0F, 2.3F));
	public static final Block magic_modern_desk = new Desk(AbstractBlock.Settings.create().strength(2.0F, 2.3F));
	public static final Block magic_table = new TableHitbox(AbstractBlock.Settings.create().strength(2.0F, 2.3F));
	public static final Block magic_end_table = new TableHitbox(AbstractBlock.Settings.create().strength(2.0F, 2.3F));
	public static final Block magic_coffee_table = new Table(AbstractBlock.Settings.create().strength(2.0F, 2.3F));
	public static final Block magic_glass_table = new TableHitbox(AbstractBlock.Settings.create().strength(2.0F, 2.3F));
	public static final Block magic_chair = new StripedChair(AbstractBlock.Settings.create().strength(2.0F, 2.3F));
	public static final Block magic_modern_chair = new ModernChair(AbstractBlock.Settings.create().strength(2.0F, 2.3F));
	public static final Block magic_striped_chair = new StripedChair(AbstractBlock.Settings.create().strength(2.0F, 2.3F));
	public static final Block magic_stool_chair = new Chair(AbstractBlock.Settings.create().strength(2.0F, 2.3F));
	public static final Block magic_counter = new Counter(AbstractBlock.Settings.create().strength(2.0F, 2.3F));
	public static final Block magic_drawer_counter = new StorageCounter(AbstractBlock.Settings.create().strength(2.0F, 2.3F));
	public static final Block magic_double_drawer_counter = new StorageCounter(AbstractBlock.Settings.create().strength(2.0F, 2.3F));
	public static final Block magic_cupboard_counter = new StorageCounter(AbstractBlock.Settings.create().strength(2.0F, 2.3F));
	public static final Block mahogany_wardrobe = new TallFurnitureHinge(AbstractBlock.Settings.create().strength(2.0F, 2.3F));
	public static final Block mahogany_modern_wardrobe = new TallFurnitureHinge(AbstractBlock.Settings.create().strength(2.0F, 2.3F));
	public static final Block mahogany_double_wardrobe = new TallFurniture(AbstractBlock.Settings.create().strength(2.0F, 2.3F));
	public static final Block mahogany_bookshelf = new TallFurniture(AbstractBlock.Settings.create().strength(2.0F, 2.3F));
	public static final Block mahogany_bookshelf_cupboard = new TallFurnitureHinge(AbstractBlock.Settings.create().strength(2.0F, 2.3F));
	public static final Block mahogany_drawer = new WideFurniture(AbstractBlock.Settings.create().strength(2.0F, 2.3F));
	public static final Block mahogany_double_drawer = new WideFurniture(AbstractBlock.Settings.create().strength(2.0F, 2.3F));
	public static final Block mahogany_bookshelf_drawer = new WideFurniture(AbstractBlock.Settings.create().strength(2.0F, 2.3F));
	public static final Block mahogany_lower_bookshelf_drawer = new WideFurniture(AbstractBlock.Settings.create().strength(2.0F, 2.3F));
	public static final Block mahogany_large_drawer = new WideFurniture(AbstractBlock.Settings.create().strength(2.0F, 2.3F));
	public static final Block mahogany_lower_triple_drawer = new WideFurniture(AbstractBlock.Settings.create().strength(2.0F, 2.3F));
	public static final Block mahogany_triple_drawer = new WideFurniture(AbstractBlock.Settings.create().strength(2.0F, 2.3F));
	public static final Block mahogany_desk = new Desk(AbstractBlock.Settings.create().strength(2.0F, 2.3F));
	public static final Block mahogany_covered_desk = new Desk(AbstractBlock.Settings.create().strength(2.0F, 2.3F));
	public static final Block mahogany_modern_desk = new Desk(AbstractBlock.Settings.create().strength(2.0F, 2.3F));
	public static final Block mahogany_table = new TableHitbox(AbstractBlock.Settings.create().strength(2.0F, 2.3F));
	public static final Block mahogany_end_table = new TableHitbox(AbstractBlock.Settings.create().strength(2.0F, 2.3F));
	public static final Block mahogany_coffee_table = new Table(AbstractBlock.Settings.create().strength(2.0F, 2.3F));
	public static final Block mahogany_glass_table = new TableHitbox(AbstractBlock.Settings.create().strength(2.0F, 2.3F));
	public static final Block mahogany_chair = new StripedChair(AbstractBlock.Settings.create().strength(2.0F, 2.3F));
	public static final Block mahogany_modern_chair = new ModernChair(AbstractBlock.Settings.create().strength(2.0F, 2.3F));
	public static final Block mahogany_striped_chair = new StripedChair(AbstractBlock.Settings.create().strength(2.0F, 2.3F));
	public static final Block mahogany_stool_chair = new Chair(AbstractBlock.Settings.create().strength(2.0F, 2.3F));
	public static final Block mahogany_counter = new Counter(AbstractBlock.Settings.create().strength(2.0F, 2.3F));
	public static final Block mahogany_drawer_counter = new StorageCounter(AbstractBlock.Settings.create().strength(2.0F, 2.3F));
	public static final Block mahogany_double_drawer_counter = new StorageCounter(AbstractBlock.Settings.create().strength(2.0F, 2.3F));
	public static final Block mahogany_cupboard_counter = new StorageCounter(AbstractBlock.Settings.create().strength(2.0F, 2.3F));
	public static final Block palm_wardrobe = new TallFurnitureHinge(AbstractBlock.Settings.create().strength(2.0F, 2.3F));
	public static final Block palm_modern_wardrobe = new TallFurnitureHinge(AbstractBlock.Settings.create().strength(2.0F, 2.3F));
	public static final Block palm_double_wardrobe = new TallFurniture(AbstractBlock.Settings.create().strength(2.0F, 2.3F));
	public static final Block palm_bookshelf = new TallFurniture(AbstractBlock.Settings.create().strength(2.0F, 2.3F));
	public static final Block palm_bookshelf_cupboard = new TallFurnitureHinge(AbstractBlock.Settings.create().strength(2.0F, 2.3F));
	public static final Block palm_drawer = new WideFurniture(AbstractBlock.Settings.create().strength(2.0F, 2.3F));
	public static final Block palm_double_drawer = new WideFurniture(AbstractBlock.Settings.create().strength(2.0F, 2.3F));
	public static final Block palm_bookshelf_drawer = new WideFurniture(AbstractBlock.Settings.create().strength(2.0F, 2.3F));
	public static final Block palm_lower_bookshelf_drawer = new WideFurniture(AbstractBlock.Settings.create().strength(2.0F, 2.3F));
	public static final Block palm_large_drawer = new WideFurniture(AbstractBlock.Settings.create().strength(2.0F, 2.3F));
	public static final Block palm_lower_triple_drawer = new WideFurniture(AbstractBlock.Settings.create().strength(2.0F, 2.3F));
	public static final Block palm_triple_drawer = new WideFurniture(AbstractBlock.Settings.create().strength(2.0F, 2.3F));
	public static final Block palm_desk = new Desk(AbstractBlock.Settings.create().strength(2.0F, 2.3F));
	public static final Block palm_covered_desk = new Desk(AbstractBlock.Settings.create().strength(2.0F, 2.3F));
	public static final Block palm_modern_desk = new Desk(AbstractBlock.Settings.create().strength(2.0F, 2.3F));
	public static final Block palm_table = new TableHitbox(AbstractBlock.Settings.create().strength(2.0F, 2.3F));
	public static final Block palm_end_table = new TableHitbox(AbstractBlock.Settings.create().strength(2.0F, 2.3F));
	public static final Block palm_coffee_table = new Table(AbstractBlock.Settings.create().strength(2.0F, 2.3F));
	public static final Block palm_glass_table = new TableHitbox(AbstractBlock.Settings.create().strength(2.0F, 2.3F));
	public static final Block palm_chair = new StripedChair(AbstractBlock.Settings.create().strength(2.0F, 2.3F));
	public static final Block palm_modern_chair = new ModernChair(AbstractBlock.Settings.create().strength(2.0F, 2.3F));
	public static final Block palm_striped_chair = new StripedChair(AbstractBlock.Settings.create().strength(2.0F, 2.3F));
	public static final Block palm_stool_chair = new Chair(AbstractBlock.Settings.create().strength(2.0F, 2.3F));
	public static final Block palm_counter = new Counter(AbstractBlock.Settings.create().strength(2.0F, 2.3F));
	public static final Block palm_drawer_counter = new StorageCounter(AbstractBlock.Settings.create().strength(2.0F, 2.3F));
	public static final Block palm_double_drawer_counter = new StorageCounter(AbstractBlock.Settings.create().strength(2.0F, 2.3F));
	public static final Block palm_cupboard_counter = new StorageCounter(AbstractBlock.Settings.create().strength(2.0F, 2.3F));
	public static final Block redwood_wardrobe = new TallFurnitureHinge(AbstractBlock.Settings.create().strength(2.0F, 2.3F));
	public static final Block redwood_modern_wardrobe = new TallFurnitureHinge(AbstractBlock.Settings.create().strength(2.0F, 2.3F));
	public static final Block redwood_double_wardrobe = new TallFurniture(AbstractBlock.Settings.create().strength(2.0F, 2.3F));
	public static final Block redwood_bookshelf = new TallFurniture(AbstractBlock.Settings.create().strength(2.0F, 2.3F));
	public static final Block redwood_bookshelf_cupboard = new TallFurnitureHinge(AbstractBlock.Settings.create().strength(2.0F, 2.3F));
	public static final Block redwood_drawer = new WideFurniture(AbstractBlock.Settings.create().strength(2.0F, 2.3F));
	public static final Block redwood_double_drawer = new WideFurniture(AbstractBlock.Settings.create().strength(2.0F, 2.3F));
	public static final Block redwood_bookshelf_drawer = new WideFurniture(AbstractBlock.Settings.create().strength(2.0F, 2.3F));
	public static final Block redwood_lower_bookshelf_drawer = new WideFurniture(AbstractBlock.Settings.create().strength(2.0F, 2.3F));
	public static final Block redwood_large_drawer = new WideFurniture(AbstractBlock.Settings.create().strength(2.0F, 2.3F));
	public static final Block redwood_lower_triple_drawer = new WideFurniture(AbstractBlock.Settings.create().strength(2.0F, 2.3F));
	public static final Block redwood_triple_drawer = new WideFurniture(AbstractBlock.Settings.create().strength(2.0F, 2.3F));
	public static final Block redwood_desk = new Desk(AbstractBlock.Settings.create().strength(2.0F, 2.3F));
	public static final Block redwood_covered_desk = new Desk(AbstractBlock.Settings.create().strength(2.0F, 2.3F));
	public static final Block redwood_modern_desk = new Desk(AbstractBlock.Settings.create().strength(2.0F, 2.3F));
	public static final Block redwood_table = new TableHitbox(AbstractBlock.Settings.create().strength(2.0F, 2.3F));
	public static final Block redwood_end_table = new TableHitbox(AbstractBlock.Settings.create().strength(2.0F, 2.3F));
	public static final Block redwood_coffee_table = new Table(AbstractBlock.Settings.create().strength(2.0F, 2.3F));
	public static final Block redwood_glass_table = new TableHitbox(AbstractBlock.Settings.create().strength(2.0F, 2.3F));
	public static final Block redwood_chair = new StripedChair(AbstractBlock.Settings.create().strength(2.0F, 2.3F));
	public static final Block redwood_modern_chair = new ModernChair(AbstractBlock.Settings.create().strength(2.0F, 2.3F));
	public static final Block redwood_striped_chair = new StripedChair(AbstractBlock.Settings.create().strength(2.0F, 2.3F));
	public static final Block redwood_stool_chair = new Chair(AbstractBlock.Settings.create().strength(2.0F, 2.3F));
	public static final Block redwood_counter = new Counter(AbstractBlock.Settings.create().strength(2.0F, 2.3F));
	public static final Block redwood_drawer_counter = new StorageCounter(AbstractBlock.Settings.create().strength(2.0F, 2.3F));
	public static final Block redwood_double_drawer_counter = new StorageCounter(AbstractBlock.Settings.create().strength(2.0F, 2.3F));
	public static final Block redwood_cupboard_counter = new StorageCounter(AbstractBlock.Settings.create().strength(2.0F, 2.3F));
	public static final Block umbran_wardrobe = new TallFurnitureHinge(AbstractBlock.Settings.create().strength(2.0F, 2.3F));
	public static final Block umbran_modern_wardrobe = new TallFurnitureHinge(AbstractBlock.Settings.create().strength(2.0F, 2.3F));
	public static final Block umbran_double_wardrobe = new TallFurniture(AbstractBlock.Settings.create().strength(2.0F, 2.3F));
	public static final Block umbran_bookshelf = new TallFurniture(AbstractBlock.Settings.create().strength(2.0F, 2.3F));
	public static final Block umbran_bookshelf_cupboard = new TallFurnitureHinge(AbstractBlock.Settings.create().strength(2.0F, 2.3F));
	public static final Block umbran_drawer = new WideFurniture(AbstractBlock.Settings.create().strength(2.0F, 2.3F));
	public static final Block umbran_double_drawer = new WideFurniture(AbstractBlock.Settings.create().strength(2.0F, 2.3F));
	public static final Block umbran_bookshelf_drawer = new WideFurniture(AbstractBlock.Settings.create().strength(2.0F, 2.3F));
	public static final Block umbran_lower_bookshelf_drawer = new WideFurniture(AbstractBlock.Settings.create().strength(2.0F, 2.3F));
	public static final Block umbran_large_drawer = new WideFurniture(AbstractBlock.Settings.create().strength(2.0F, 2.3F));
	public static final Block umbran_lower_triple_drawer = new WideFurniture(AbstractBlock.Settings.create().strength(2.0F, 2.3F));
	public static final Block umbran_triple_drawer = new WideFurniture(AbstractBlock.Settings.create().strength(2.0F, 2.3F));
	public static final Block umbran_desk = new Desk(AbstractBlock.Settings.create().strength(2.0F, 2.3F));
	public static final Block umbran_covered_desk = new Desk(AbstractBlock.Settings.create().strength(2.0F, 2.3F));
	public static final Block umbran_modern_desk = new Desk(AbstractBlock.Settings.create().strength(2.0F, 2.3F));
	public static final Block umbran_table = new TableHitbox(AbstractBlock.Settings.create().strength(2.0F, 2.3F));
	public static final Block umbran_end_table = new TableHitbox(AbstractBlock.Settings.create().strength(2.0F, 2.3F));
	public static final Block umbran_coffee_table = new Table(AbstractBlock.Settings.create().strength(2.0F, 2.3F));
	public static final Block umbran_glass_table = new TableHitbox(AbstractBlock.Settings.create().strength(2.0F, 2.3F));
	public static final Block umbran_chair = new StripedChair(AbstractBlock.Settings.create().strength(2.0F, 2.3F));
	public static final Block umbran_modern_chair = new ModernChair(AbstractBlock.Settings.create().strength(2.0F, 2.3F));
	public static final Block umbran_striped_chair = new StripedChair(AbstractBlock.Settings.create().strength(2.0F, 2.3F));
	public static final Block umbran_stool_chair = new Chair(AbstractBlock.Settings.create().strength(2.0F, 2.3F));
	public static final Block umbran_counter = new Counter(AbstractBlock.Settings.create().strength(2.0F, 2.3F));
	public static final Block umbran_drawer_counter = new StorageCounter(AbstractBlock.Settings.create().strength(2.0F, 2.3F));
	public static final Block umbran_double_drawer_counter = new StorageCounter(AbstractBlock.Settings.create().strength(2.0F, 2.3F));
	public static final Block umbran_cupboard_counter = new StorageCounter(AbstractBlock.Settings.create().strength(2.0F, 2.3F));
	public static final Block willow_wardrobe = new TallFurnitureHinge(AbstractBlock.Settings.create().strength(2.0F, 2.3F));
	public static final Block willow_modern_wardrobe = new TallFurnitureHinge(AbstractBlock.Settings.create().strength(2.0F, 2.3F));
	public static final Block willow_double_wardrobe = new TallFurniture(AbstractBlock.Settings.create().strength(2.0F, 2.3F));
	public static final Block willow_bookshelf = new TallFurniture(AbstractBlock.Settings.create().strength(2.0F, 2.3F));
	public static final Block willow_bookshelf_cupboard = new TallFurnitureHinge(AbstractBlock.Settings.create().strength(2.0F, 2.3F));
	public static final Block willow_drawer = new WideFurniture(AbstractBlock.Settings.create().strength(2.0F, 2.3F));
	public static final Block willow_double_drawer = new WideFurniture(AbstractBlock.Settings.create().strength(2.0F, 2.3F));
	public static final Block willow_bookshelf_drawer = new WideFurniture(AbstractBlock.Settings.create().strength(2.0F, 2.3F));
	public static final Block willow_lower_bookshelf_drawer = new WideFurniture(AbstractBlock.Settings.create().strength(2.0F, 2.3F));
	public static final Block willow_large_drawer = new WideFurniture(AbstractBlock.Settings.create().strength(2.0F, 2.3F));
	public static final Block willow_lower_triple_drawer = new WideFurniture(AbstractBlock.Settings.create().strength(2.0F, 2.3F));
	public static final Block willow_triple_drawer = new WideFurniture(AbstractBlock.Settings.create().strength(2.0F, 2.3F));
	public static final Block willow_desk = new Desk(AbstractBlock.Settings.create().strength(2.0F, 2.3F));
	public static final Block willow_covered_desk = new Desk(AbstractBlock.Settings.create().strength(2.0F, 2.3F));
	public static final Block willow_modern_desk = new Desk(AbstractBlock.Settings.create().strength(2.0F, 2.3F));
	public static final Block willow_table = new TableHitbox(AbstractBlock.Settings.create().strength(2.0F, 2.3F));
	public static final Block willow_end_table = new TableHitbox(AbstractBlock.Settings.create().strength(2.0F, 2.3F));
	public static final Block willow_coffee_table = new Table(AbstractBlock.Settings.create().strength(2.0F, 2.3F));
	public static final Block willow_glass_table = new TableHitbox(AbstractBlock.Settings.create().strength(2.0F, 2.3F));
	public static final Block willow_chair = new StripedChair(AbstractBlock.Settings.create().strength(2.0F, 2.3F));
	public static final Block willow_modern_chair = new ModernChair(AbstractBlock.Settings.create().strength(2.0F, 2.3F));
	public static final Block willow_striped_chair = new StripedChair(AbstractBlock.Settings.create().strength(2.0F, 2.3F));
	public static final Block willow_stool_chair = new Chair(AbstractBlock.Settings.create().strength(2.0F, 2.3F));
	public static final Block willow_counter = new Counter(AbstractBlock.Settings.create().strength(2.0F, 2.3F));
	public static final Block willow_drawer_counter = new StorageCounter(AbstractBlock.Settings.create().strength(2.0F, 2.3F));
	public static final Block willow_double_drawer_counter = new StorageCounter(AbstractBlock.Settings.create().strength(2.0F, 2.3F));
	public static final Block willow_cupboard_counter = new StorageCounter(AbstractBlock.Settings.create().strength(2.0F, 2.3F));

	public static void registry()
	{
		add("dead_wardrobe", dead_wardrobe);
		add("dead_modern_wardrobe", dead_modern_wardrobe);
		add("dead_double_wardrobe", dead_double_wardrobe);
		add("dead_bookshelf", dead_bookshelf);
		add("dead_bookshelf_cupboard", dead_bookshelf_cupboard);
		add("dead_drawer", dead_drawer);
		add("dead_double_drawer", dead_double_drawer);
		add("dead_bookshelf_drawer", dead_bookshelf_drawer);
		add("dead_lower_bookshelf_drawer", dead_lower_bookshelf_drawer);
		add("dead_large_drawer", dead_large_drawer);
		add("dead_lower_triple_drawer", dead_lower_triple_drawer);
		add("dead_triple_drawer", dead_triple_drawer);
		add("dead_desk", dead_desk);
		add("dead_covered_desk", dead_covered_desk);
		add("dead_modern_desk", dead_modern_desk);
		add("dead_table", dead_table);
		add("dead_end_table", dead_end_table);
		add("dead_coffee_table", dead_coffee_table);
		add("dead_glass_table", dead_glass_table);
		add("dead_chair", dead_chair);
		add("dead_modern_chair", dead_modern_chair);
		add("dead_striped_chair", dead_striped_chair);
		add("dead_stool_chair", dead_stool_chair);
		add("dead_counter", dead_counter);
		add("dead_drawer_counter", dead_drawer_counter);
		add("dead_double_drawer_counter", dead_double_drawer_counter);
		add("dead_cupboard_counter", dead_cupboard_counter);
		add("fir_wardrobe", fir_wardrobe);
		add("fir_modern_wardrobe", fir_modern_wardrobe);
		add("fir_double_wardrobe", fir_double_wardrobe);
		add("fir_bookshelf", fir_bookshelf);
		add("fir_bookshelf_cupboard", fir_bookshelf_cupboard);
		add("fir_drawer", fir_drawer);
		add("fir_double_drawer", fir_double_drawer);
		add("fir_bookshelf_drawer", fir_bookshelf_drawer);
		add("fir_lower_bookshelf_drawer", fir_lower_bookshelf_drawer);
		add("fir_large_drawer", fir_large_drawer);
		add("fir_lower_triple_drawer", fir_lower_triple_drawer);
		add("fir_triple_drawer", fir_triple_drawer);
		add("fir_desk", fir_desk);
		add("fir_covered_desk", fir_covered_desk);
		add("fir_modern_desk", fir_modern_desk);
		add("fir_table", fir_table);
		add("fir_end_table", fir_end_table);
		add("fir_coffee_table", fir_coffee_table);
		add("fir_glass_table", fir_glass_table);
		add("fir_chair", fir_chair);
		add("fir_modern_chair", fir_modern_chair);
		add("fir_striped_chair", fir_striped_chair);
		add("fir_stool_chair", fir_stool_chair);
		add("fir_counter", fir_counter);
		add("fir_drawer_counter", fir_drawer_counter);
		add("fir_double_drawer_counter", fir_double_drawer_counter);
		add("fir_cupboard_counter", fir_cupboard_counter);
		add("hellbark_wardrobe", hellbark_wardrobe);
		add("hellbark_modern_wardrobe", hellbark_modern_wardrobe);
		add("hellbark_double_wardrobe", hellbark_double_wardrobe);
		add("hellbark_bookshelf", hellbark_bookshelf);
		add("hellbark_bookshelf_cupboard", hellbark_bookshelf_cupboard);
		add("hellbark_drawer", hellbark_drawer);
		add("hellbark_double_drawer", hellbark_double_drawer);
		add("hellbark_bookshelf_drawer", hellbark_bookshelf_drawer);
		add("hellbark_lower_bookshelf_drawer", hellbark_lower_bookshelf_drawer);
		add("hellbark_large_drawer", hellbark_large_drawer);
		add("hellbark_lower_triple_drawer", hellbark_lower_triple_drawer);
		add("hellbark_triple_drawer", hellbark_triple_drawer);
		add("hellbark_desk", hellbark_desk);
		add("hellbark_covered_desk", hellbark_covered_desk);
		add("hellbark_modern_desk", hellbark_modern_desk);
		add("hellbark_table", hellbark_table);
		add("hellbark_end_table", hellbark_end_table);
		add("hellbark_coffee_table", hellbark_coffee_table);
		add("hellbark_glass_table", hellbark_glass_table);
		add("hellbark_chair", hellbark_chair);
		add("hellbark_modern_chair", hellbark_modern_chair);
		add("hellbark_striped_chair", hellbark_striped_chair);
		add("hellbark_stool_chair", hellbark_stool_chair);
		add("hellbark_counter", hellbark_counter);
		add("hellbark_drawer_counter", hellbark_drawer_counter);
		add("hellbark_double_drawer_counter", hellbark_double_drawer_counter);
		add("hellbark_cupboard_counter", hellbark_cupboard_counter);
		add("jacaranda_wardrobe", jacaranda_wardrobe);
		add("jacaranda_modern_wardrobe", jacaranda_modern_wardrobe);
		add("jacaranda_double_wardrobe", jacaranda_double_wardrobe);
		add("jacaranda_bookshelf", jacaranda_bookshelf);
		add("jacaranda_bookshelf_cupboard", jacaranda_bookshelf_cupboard);
		add("jacaranda_drawer", jacaranda_drawer);
		add("jacaranda_double_drawer", jacaranda_double_drawer);
		add("jacaranda_bookshelf_drawer", jacaranda_bookshelf_drawer);
		add("jacaranda_lower_bookshelf_drawer", jacaranda_lower_bookshelf_drawer);
		add("jacaranda_large_drawer", jacaranda_large_drawer);
		add("jacaranda_lower_triple_drawer", jacaranda_lower_triple_drawer);
		add("jacaranda_triple_drawer", jacaranda_triple_drawer);
		add("jacaranda_desk", jacaranda_desk);
		add("jacaranda_covered_desk", jacaranda_covered_desk);
		add("jacaranda_modern_desk", jacaranda_modern_desk);
		add("jacaranda_table", jacaranda_table);
		add("jacaranda_end_table", jacaranda_end_table);
		add("jacaranda_coffee_table", jacaranda_coffee_table);
		add("jacaranda_glass_table", jacaranda_glass_table);
		add("jacaranda_chair", jacaranda_chair);
		add("jacaranda_modern_chair", jacaranda_modern_chair);
		add("jacaranda_striped_chair", jacaranda_striped_chair);
		add("jacaranda_stool_chair", jacaranda_stool_chair);
		add("jacaranda_counter", jacaranda_counter);
		add("jacaranda_drawer_counter", jacaranda_drawer_counter);
		add("jacaranda_double_drawer_counter", jacaranda_double_drawer_counter);
		add("jacaranda_cupboard_counter", jacaranda_cupboard_counter);
		add("magic_wardrobe", magic_wardrobe);
		add("magic_modern_wardrobe", magic_modern_wardrobe);
		add("magic_double_wardrobe", magic_double_wardrobe);
		add("magic_bookshelf", magic_bookshelf);
		add("magic_bookshelf_cupboard", magic_bookshelf_cupboard);
		add("magic_drawer", magic_drawer);
		add("magic_double_drawer", magic_double_drawer);
		add("magic_bookshelf_drawer", magic_bookshelf_drawer);
		add("magic_lower_bookshelf_drawer", magic_lower_bookshelf_drawer);
		add("magic_large_drawer", magic_large_drawer);
		add("magic_lower_triple_drawer", magic_lower_triple_drawer);
		add("magic_triple_drawer", magic_triple_drawer);
		add("magic_desk", magic_desk);
		add("magic_covered_desk", magic_covered_desk);
		add("magic_modern_desk", magic_modern_desk);
		add("magic_table", magic_table);
		add("magic_end_table", magic_end_table);
		add("magic_coffee_table", magic_coffee_table);
		add("magic_glass_table", magic_glass_table);
		add("magic_chair", magic_chair);
		add("magic_modern_chair", magic_modern_chair);
		add("magic_striped_chair", magic_striped_chair);
		add("magic_stool_chair", magic_stool_chair);
		add("magic_counter", magic_counter);
		add("magic_drawer_counter", magic_drawer_counter);
		add("magic_double_drawer_counter", magic_double_drawer_counter);
		add("magic_cupboard_counter", magic_cupboard_counter);
		add("mahogany_wardrobe", mahogany_wardrobe);
		add("mahogany_modern_wardrobe", mahogany_modern_wardrobe);
		add("mahogany_double_wardrobe", mahogany_double_wardrobe);
		add("mahogany_bookshelf", mahogany_bookshelf);
		add("mahogany_bookshelf_cupboard", mahogany_bookshelf_cupboard);
		add("mahogany_drawer", mahogany_drawer);
		add("mahogany_double_drawer", mahogany_double_drawer);
		add("mahogany_bookshelf_drawer", mahogany_bookshelf_drawer);
		add("mahogany_lower_bookshelf_drawer", mahogany_lower_bookshelf_drawer);
		add("mahogany_large_drawer", mahogany_large_drawer);
		add("mahogany_lower_triple_drawer", mahogany_lower_triple_drawer);
		add("mahogany_triple_drawer", mahogany_triple_drawer);
		add("mahogany_desk", mahogany_desk);
		add("mahogany_covered_desk", mahogany_covered_desk);
		add("mahogany_modern_desk", mahogany_modern_desk);
		add("mahogany_table", mahogany_table);
		add("mahogany_end_table", mahogany_end_table);
		add("mahogany_coffee_table", mahogany_coffee_table);
		add("mahogany_glass_table", mahogany_glass_table);
		add("mahogany_chair", mahogany_chair);
		add("mahogany_modern_chair", mahogany_modern_chair);
		add("mahogany_striped_chair", mahogany_striped_chair);
		add("mahogany_stool_chair", mahogany_stool_chair);
		add("mahogany_counter", mahogany_counter);
		add("mahogany_drawer_counter", mahogany_drawer_counter);
		add("mahogany_double_drawer_counter", mahogany_double_drawer_counter);
		add("mahogany_cupboard_counter", mahogany_cupboard_counter);
		add("palm_wardrobe", palm_wardrobe);
		add("palm_modern_wardrobe", palm_modern_wardrobe);
		add("palm_double_wardrobe", palm_double_wardrobe);
		add("palm_bookshelf", palm_bookshelf);
		add("palm_bookshelf_cupboard", palm_bookshelf_cupboard);
		add("palm_drawer", palm_drawer);
		add("palm_double_drawer", palm_double_drawer);
		add("palm_bookshelf_drawer", palm_bookshelf_drawer);
		add("palm_lower_bookshelf_drawer", palm_lower_bookshelf_drawer);
		add("palm_large_drawer", palm_large_drawer);
		add("palm_lower_triple_drawer", palm_lower_triple_drawer);
		add("palm_triple_drawer", palm_triple_drawer);
		add("palm_desk", palm_desk);
		add("palm_covered_desk", palm_covered_desk);
		add("palm_modern_desk", palm_modern_desk);
		add("palm_table", palm_table);
		add("palm_end_table", palm_end_table);
		add("palm_coffee_table", palm_coffee_table);
		add("palm_glass_table", palm_glass_table);
		add("palm_chair", palm_chair);
		add("palm_modern_chair", palm_modern_chair);
		add("palm_striped_chair", palm_striped_chair);
		add("palm_stool_chair", palm_stool_chair);
		add("palm_counter", palm_counter);
		add("palm_drawer_counter", palm_drawer_counter);
		add("palm_double_drawer_counter", palm_double_drawer_counter);
		add("palm_cupboard_counter", palm_cupboard_counter);
		add("redwood_wardrobe", redwood_wardrobe);
		add("redwood_modern_wardrobe", redwood_modern_wardrobe);
		add("redwood_double_wardrobe", redwood_double_wardrobe);
		add("redwood_bookshelf", redwood_bookshelf);
		add("redwood_bookshelf_cupboard", redwood_bookshelf_cupboard);
		add("redwood_drawer", redwood_drawer);
		add("redwood_double_drawer", redwood_double_drawer);
		add("redwood_bookshelf_drawer", redwood_bookshelf_drawer);
		add("redwood_lower_bookshelf_drawer", redwood_lower_bookshelf_drawer);
		add("redwood_large_drawer", redwood_large_drawer);
		add("redwood_lower_triple_drawer", redwood_lower_triple_drawer);
		add("redwood_triple_drawer", redwood_triple_drawer);
		add("redwood_desk", redwood_desk);
		add("redwood_covered_desk", redwood_covered_desk);
		add("redwood_modern_desk", redwood_modern_desk);
		add("redwood_table", redwood_table);
		add("redwood_end_table", redwood_end_table);
		add("redwood_coffee_table", redwood_coffee_table);
		add("redwood_glass_table", redwood_glass_table);
		add("redwood_chair", redwood_chair);
		add("redwood_modern_chair", redwood_modern_chair);
		add("redwood_striped_chair", redwood_striped_chair);
		add("redwood_stool_chair", redwood_stool_chair);
		add("redwood_counter", redwood_counter);
		add("redwood_drawer_counter", redwood_drawer_counter);
		add("redwood_double_drawer_counter", redwood_double_drawer_counter);
		add("redwood_cupboard_counter", redwood_cupboard_counter);
		add("umbran_wardrobe", umbran_wardrobe);
		add("umbran_modern_wardrobe", umbran_modern_wardrobe);
		add("umbran_double_wardrobe", umbran_double_wardrobe);
		add("umbran_bookshelf", umbran_bookshelf);
		add("umbran_bookshelf_cupboard", umbran_bookshelf_cupboard);
		add("umbran_drawer", umbran_drawer);
		add("umbran_double_drawer", umbran_double_drawer);
		add("umbran_bookshelf_drawer", umbran_bookshelf_drawer);
		add("umbran_lower_bookshelf_drawer", umbran_lower_bookshelf_drawer);
		add("umbran_large_drawer", umbran_large_drawer);
		add("umbran_lower_triple_drawer", umbran_lower_triple_drawer);
		add("umbran_triple_drawer", umbran_triple_drawer);
		add("umbran_desk", umbran_desk);
		add("umbran_covered_desk", umbran_covered_desk);
		add("umbran_modern_desk", umbran_modern_desk);
		add("umbran_table", umbran_table);
		add("umbran_end_table", umbran_end_table);
		add("umbran_coffee_table", umbran_coffee_table);
		add("umbran_glass_table", umbran_glass_table);
		add("umbran_chair", umbran_chair);
		add("umbran_modern_chair", umbran_modern_chair);
		add("umbran_striped_chair", umbran_striped_chair);
		add("umbran_stool_chair", umbran_stool_chair);
		add("umbran_counter", umbran_counter);
		add("umbran_drawer_counter", umbran_drawer_counter);
		add("umbran_double_drawer_counter", umbran_double_drawer_counter);
		add("umbran_cupboard_counter", umbran_cupboard_counter);
		add("willow_wardrobe", willow_wardrobe);
		add("willow_modern_wardrobe", willow_modern_wardrobe);
		add("willow_double_wardrobe", willow_double_wardrobe);
		add("willow_bookshelf", willow_bookshelf);
		add("willow_bookshelf_cupboard", willow_bookshelf_cupboard);
		add("willow_drawer", willow_drawer);
		add("willow_double_drawer", willow_double_drawer);
		add("willow_bookshelf_drawer", willow_bookshelf_drawer);
		add("willow_lower_bookshelf_drawer", willow_lower_bookshelf_drawer);
		add("willow_large_drawer", willow_large_drawer);
		add("willow_lower_triple_drawer", willow_lower_triple_drawer);
		add("willow_triple_drawer", willow_triple_drawer);
		add("willow_desk", willow_desk);
		add("willow_covered_desk", willow_covered_desk);
		add("willow_modern_desk", willow_modern_desk);
		add("willow_table", willow_table);
		add("willow_end_table", willow_end_table);
		add("willow_coffee_table", willow_coffee_table);
		add("willow_glass_table", willow_glass_table);
		add("willow_chair", willow_chair);
		add("willow_modern_chair", willow_modern_chair);
		add("willow_striped_chair", willow_striped_chair);
		add("willow_stool_chair", willow_stool_chair);
		add("willow_counter", willow_counter);
		add("willow_drawer_counter", willow_drawer_counter);
		add("willow_double_drawer_counter", willow_double_drawer_counter);
		add("willow_cupboard_counter", willow_cupboard_counter);
	}
	
	private static void add(String name, Block b)
    {
    	Registry.register(Registries.BLOCK, new Identifier(McwFurnituresBOP.MODID, name), b);
    	blockItem(b, name);
	}
    
    private static void blockItem(Block b, String n)
    {
        Registry.register(Registries.ITEM, new Identifier(McwFurnituresBOP.MODID, n), new BlockItem(b, new Item.Settings()));
    }
}