modLoader="javafml"
loaderVersion="[40,)"
license="All rights reserved"
issueTrackerURL="https://github.com/Samlegamer/Macaw-s-Furnitures-Compat/issues" #optional

[[mods]] #mandatory
modId="mcwfurnituresbyg"
version="1.18.2-1.2"
displayName="Macaw's Furnitures - BYG"
displayURL="https://www.curseforge.com/minecraft/mc-mods/macaws-furnitures-oh-the-biomes-youll-go"
logoFile="logo.png"
credits="sketch_macaw"
authors="Samlegamer"

description='''
Compatibility Oh the Biomes You'll Go with Macaw's Furnitures for Minecraft 1.18.2.
'''

[[dependencies.mcwfurnituresbyg]]
    modId="forge"
    mandatory=true
    versionRange="[40,)"
    ordering="NONE"
    side="BOTH"

[[dependencies.mcwfurnituresbyg]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.18.2,1.19)"
    ordering="NONE"
    side="BOTH"
